### ISSUE TITLE
Plugin notifications get_context_data() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by iarp** [django-wiki/django-wiki#1000]
Django 2.2.5
Python 3.7

https://github.com/django-wiki/django-wiki/blob/master/src/wiki/plugins/notifications/views.py#L48

Raises the following error

> TypeError at /_plugin/notifications/
>get_context_data() takes 1 positional argument but 2 were given

I also see the same issue on line 43 in the same file: https://github.com/django-wiki/django-wiki/blob/master/src/wiki/plugins/notifications/views.py#L43

**Comment by benjaoming** [comment]
This was probably fixed in #978

The reason it didn't get merged was because tests were added in a different PR that wasn't ready.

I'll merge #978 now.
