### ISSUE TITLE
Issue with overriding default django-wiki

### ISSUE THREAD

**Issue by slinkymanbyday** [django-wiki/django-wiki#1004]
Hi,
My end goal is to override the Settings page. 
Some details of my setup:
Python 3.6.9
Django 2.2.5
wiki (both v0.5.0 and current master)

The way I'm trying to do this is the following:

apps.py:
```
from wiki.apps import WikiConfig

class DifferentWikiConfig(WikiConfig):
    default_site = 'different_wiki.sites.DifferentWikiSite'
```
sites.py
```
from wiki.sites import WikiSite
from .views import DifferentSettings

class DifferentWikiSite(WikiSite):
    article_settings_view = DifferentSettings.as_view()
```
views.py

```
from wiki.views.article import Settings
class DifferentSettings(Settings):
    pass
```

with the above I get the following error:
'DifferentWikiSite' object has no attribute 'user'

it works fine if i don't modify article_settings_view (if I just have pass on DifferentWikiSite

it seems that the login_required decorator is being passed a DifferentWikiSite instance instead of a request instance. not really sure why that is happening. Any body able to help? I just can't seem to figure out why a Site instance is being passed instead of a request object.

**Comment by benjaoming** [comment]
Hi @slinkymanbyday 

As you may have missed, the issue tracker is dedicated for bugs, features and so on: https://github.com/django-wiki/django-wiki/blob/master/SUPPORT.rst

Providing a full traceback of your exception is a good idea, otherwise it's hard to see what's going on.
