### ISSUE TITLE
Call for maintainers 2022

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#1007]
This project needs additional maintainers.

If you are interested in the future of django-wiki, please post a comment here or send an email to  benjamin@overtag.dk 

Great stuff to be done, doing just one of these is enough!

* Doing PR reviews
* Triaging issues
* Cutting out new releases
* Pushing for big tech updates - maintainers don't necessarily do the big changes - a contributor might come forward with a larger change set that needs assistance to get in.

This call is done with a serious concern to security, if you have no credentials and I don't know you at all, it's not possible to give you permissions, but as a new contributor, you are valued and can definitely create initiatives or be assigned issues!

**Comment by oscarmcm** [comment]
Hey @benjaoming I'm open to help with the maintaining of Django-Wiki. If there's a path or a todo list of things you want to focus I'm all hands to spent a few hours per day over it.

**Comment by benjaoming** [comment]
Hi @oscarmcm :wave: 

This sounds amazing. I'll send you an email!

**Comment by benjaoming** [comment]
Thanks to @oscarmcm joining (welcome!!), we are currently 2 active maintainers. So I'm gonna close this issue now.

Please feel free to pin any other highly relevant issues @oscarmcm.
