### ISSUE TITLE
Can't delete Article with USE_THOUSAND_SEPARATOR = True

### ISSUE THREAD

**Issue by tim3towers** [django-wiki/django-wiki#1013]
When USE_THOUSAND_SEPARATOR in django settings is set to True, deleting an article yields in an error bacause the form partly fails validation and the revision id is missing in cleaned data. This is because the id set in the hidden field in wiki/templates/wiki/delete.html is automatically formatted (e.g. 1.333 instead of 1333).
When modifying the template like this:
`{{ article.current_revision.id|safe }}`
deletion is possible.

**Comment by benjaoming** [comment]
Thank you for the report @tim3towers !

Is this something that you would be willing to open a PR for?

I'll make sure to get a new release out, as there are a couple of other fixes waiting to be released as well..
