### ISSUE TITLE
v0.5 Django <2.3 dependency

### ISSUE THREAD

**Issue by kaprests** [django-wiki/django-wiki#1026]
When using pipenv, and trying to install django >= 2.3 with django-wiki installed, I am unable to lock dependencies due to django-wiki requireing django<=2.3 even though it supposedly supports django 3.0. Is there perhaps some issue with how django-wiki communicates its dependencies to pipenv?

The issue does not arise with django-wiki verison 0.6b1.

**Comment by slinkymanbyday** [comment]
@benjaoming 
as 0.5.x doesn't actually support django 3 due to locked dependencies, should that be removed from the readme?

@kaprests  
for proper django3 support you will need 0.6b1 and above due to 0.5 linking to the older versions of dependencies which did not support django3

**Comment by benjaoming** [comment]
Really good point that you raise @kaprests - we left this dangling, as the support wasn't actually completed until months after it was implemented. We were stalled, waiting for a new sorl-thumbnail release and meanwhile committed so many things to master, that 0.6 became necessary :)

Thanks for raising this!
