### ISSUE TITLE
Double-scaped HTML character codes, <, >, & etc

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#1038]
Tried upgrading Markdown to 3.2 with no luck. Possibly related: https://github.com/Python-Markdown/markdown/issues/802

![image](https://user-images.githubusercontent.com/374612/78242946-3394a800-74e3-11ea-9a1f-3417068d3037.png)

**Comment by oscarmcm** [comment]
Fixed in #1039
