### ISSUE TITLE
Improve ToC plugin to enable feature parity between it an the Article List plugin

### ISSUE THREAD

**Issue by lucianoratamero** [django-wiki/django-wiki#1042]
One of the biggest issues I'm currently having is that we're using django-wiki as a knowledge base, and since we have really big articles with small sections, our ToC is huge, and there is no way to customize it (we currently rely on the python-markdown extension).

The solution for that would be for the ToC plugin to work just like the Article List plugin, enabling us to have a 'depth' kwarg for better selection of which levels of headers are going to be presented.

**Comment by lucianoratamero** [comment]
I'll probably be working on this myself, but any pointers/contributions would be welcome!

**Comment by benjaoming** [comment]
That sounds like a really great contribution, maybe you can patch up the `[toc]` macro in `wiki.plugins.macros.mdx.macro` to support `depth:123` just like `[article_list]` ?

PR is definitely welcome.
