### ISSUE TITLE
Plans to support a WYSIWYG editor?

### ISSUE THREAD

**Issue by guettli** [django-wiki/django-wiki#1045]
Plans to support a WYSIWYG editor?

Maybe CKEditor

**Comment by benjaoming** [comment]
A new editor would be very welcome, and attempts are made in django-wiki to make the editor itself pluggable. SimpleMDE seems to have been the favorite when people were talking about it:

https://github.com/django-wiki/django-wiki/issues/537
https://github.com/django-wiki/django-wiki/issues/587
https://github.com/django-wiki/django-wiki/issues/551

**Comment by guettli** [comment]
Why markdown, and not HTML?

**Comment by benjaoming** [comment]
Not sure what you mean - HTML is not a very semantic language @guettli 

Choices are elaborated here: https://github.com/django-wiki/django-wiki#manifesto
