### ISSUE TITLE
Is there available boilerplate for django-wiki?

### ISSUE THREAD

**Issue by snoop2head** [django-wiki/django-wiki#1050]
Are there any available boilerplate (or plans to make one) for django-wiki?

**Comment by benjaoming** [comment]
There used to be a template, but it wasn't maintained. LMK if you are interested in updating it!

https://github.com/django-wiki/django-wiki-project-template

CC: @valberg

**Comment by snoop2head** [comment]
Thanks for the reference @benjaoming !
I make my demo project with django-wiki in order to understand the library first.

**Comment by benjaoming** [comment]
Thanks so much too @snoop2head - your initial experiences are valuable to improve documentation etc. for other new users! Much appreciated!
