### ISSUE TITLE
Getting an error when uploading an image, using django-storages S3Boto3Storage as my backend.

### ISSUE THREAD

**Issue by zyonash** [django-wiki/django-wiki#1062]
`[Wed Jul 29 00:36:18.866020 2020] [:error] [pid 2574] AttributeError: 'str' object has no attribute 'open'`

My current settings for enabling S3 as my default storage:

`WIKI_STORAGE_BACKEND = 'storages.backends.s3boto3.S3Boto3Storage'`
`AWS_STORAGE_BUCKET_NAME = 'cloud-wiki-nonprod-files'`
`AWS_S3_REGION_NAME = 'us-east-1'`

Am I missing something obvious here?  I can't seem to find any good documentation on enabling S3 as your storage backend for the wiki.

**Comment by benjaoming** [comment]
@zyonash thanks for the report

Would you be able to see if the workaround from https://github.com/django-wiki/django-wiki/issues/602 works for you, too? I don't use S3 backends, but if there's a bug in it, a PR is most welcome!

**Comment by zyonash** [comment]
I did indeed try that workaround, but it doesn't seem to be making any difference.  I've seen several people submit issues with using the S3 backend but most of them have been closed, making me wonder if people have figured it out on their own without updating the documentation.

**Comment by daesu** [comment]
It's a lifetime ago since I touched this but when I was used it I was using the old (deprecated) storage option `s3boto.S3BotoStorage` instead of the new `s3boto3.S3Boto3Storage`.

@zyonash could you show your current configuration including the custom storage you are setting if any? Have you tried explicitly setting `WIKI_IMAGES_STORAGE_BACKEND` ?

**Comment by zyonash** [comment]
Thanks for responding.  Here are my settings:

```

class S3CustomStorage(S3Boto3Storage):
    def _normalize_name(self, name):
        return name

WIKI_STORAGE_BACKEND = 'cloud_wiki.settings.nonprod.S3CustomStorage'
AWS_STORAGE_BUCKET_NAME = 'cloud-wiki-nonprod-files'
AWS_S3_REGION_NAME = 'us-east-1'
```

I have not tried explicitly setting WIKI_IMAGES_STORAGE_BACKEND, I can certainly try that next.

**Comment by zyonash** [comment]
Setting WIKI_IMAGES_STORAGE_BACKEND explicitly did not help - here's a more complete stack trace:

[Thu Aug 13 13:03:02.532557 2020] [:error] [pid 11976] Thumbnail tag failed
[Thu Aug 13 13:03:02.532582 2020] [:error] [pid 11976] Traceback (most recent call last):
[Thu Aug 13 13:03:02.532586 2020] [:error] [pid 11976]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/sorl/thumbnail/templatetags/thumbnail.py", line 59, in render
[Thu Aug 13 13:03:02.532589 2020] [:error] [pid 11976]     return self._render(context)
[Thu Aug 13 13:03:02.532592 2020] [:error] [pid 11976]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/sorl/thumbnail/templatetags/thumbnail.py", line 139, in _render
[Thu Aug 13 13:03:02.532596 2020] [:error] [pid 11976]     thumbnail = get_thumbnail(file_, geometry, **options)
[Thu Aug 13 13:03:02.532599 2020] [:error] [pid 11976]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/sorl/thumbnail/shortcuts.py", line 8, in get_thumbnail
[Thu Aug 13 13:03:02.532602 2020] [:error] [pid 11976]     return default.backend.get_thumbnail(file_, geometry_string, **options)
[Thu Aug 13 13:03:02.532605 2020] [:error] [pid 11976]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/sorl/thumbnail/base.py", line 106, in get_thumbnail
[Thu Aug 13 13:03:02.532608 2020] [:error] [pid 11976]     source_image = default.engine.get_image(source)
[Thu Aug 13 13:03:02.532611 2020] [:error] [pid 11976]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/sorl/thumbnail/engines/pil_engine.py", line 73, in get_image
[Thu Aug 13 13:03:02.532613 2020] [:error] [pid 11976]     buffer = BufferIO(source.read())
[Thu Aug 13 13:03:02.532616 2020] [:error] [pid 11976]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/sorl/thumbnail/images.py", line 163, in read
[Thu Aug 13 13:03:02.532619 2020] [:error] [pid 11976]     f = self.storage.open(self.name)
[Thu Aug 13 13:03:02.532623 2020] [:error] [pid 11976] AttributeError: 'str' object has no attribute 'open'
[Thu Aug 13 13:03:02.532628 2020] [:error] [pid 11976]

**Comment by benjaoming** [comment]
> `AttributeError: 'str' object has no attribute 'open'`

You should set WIKI_STORAGE_BACKEND to a storage object, or a callable which returns a storage object (such as your storage class). Strings with dotted paths aren't supported AFAICT. See: https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.FileField.storage

**Comment by teury** [comment]
This is the configuration that I have used in uploading files and it has not given me problems. 
```
AWS_PUBLIC_MEDIA_LOCATION = 'media/public'

class PublicMediaStorage(S3Boto3Storage):
    location = AWS_PUBLIC_MEDIA_LOCATION
    file_overwrite = False
```

DEFAULT_FILE_STORAGE = 'mysite.storage_backends.PublicMediaStorage'

**Comment by zyonash** [comment]
@teury Does this configuration allow you to upload images to an S3 bucket, i.e.? 

I gave it a shot and I'm getting this error now:

```
[Fri Aug 14 18:25:12.613335 2020] [:error] [pid 8414]     if not VALID_BUCKET.search(bucket) and not VALID_S3_ARN.search(bucket):
[Fri Aug 14 18:25:12.613339 2020] [:error] [pid 8414] AttributeError: 'NoneType' object has no attribute 'type'
```

I did add `AWS_STORAGE_BUCKET_NAME = 'cloud-wiki-nonprod-files'`, as I didn't see in your configuration a way for the backend to know which bucket to ship files to.

Thanks!

**Comment by teury** [comment]
@zyonash 
This is the complete configuration that I have used, and it has not shown me upload problems.

**storage_backends.py**
```
from django.conf import settings
from storages.backends.s3boto3 import S3Boto3Storage

class StaticStorage(S3Boto3Storage):
    location = settings.AWS_STATIC_LOCATION

class PublicMediaStorage(S3Boto3Storage):
    location = settings.AWS_PUBLIC_MEDIA_LOCATION
    file_overwrite = False

class PrivateMediaStorage(S3Boto3Storage):
    location = settings.AWS_PRIVATE_MEDIA_LOCATION
    default_acl = 'private'
    file_overwrite = False
    custom_domain = False

```


**settings/prod.py**

```
AWS_ACCESS_KEY_ID = '**********'
AWS_SECRET_ACCESS_KEY = '**********'
AWS_STORAGE_BUCKET_NAME = 'BUCKET NAME'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

AWS_STATIC_LOCATION = 'static'
STATICFILES_STORAGE = 'mysite.storage_backends.StaticStorage'
STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_STATIC_LOCATION)

AWS_PUBLIC_MEDIA_LOCATION = 'media/public'
DEFAULT_FILE_STORAGE = 'mysite.storage_backends.PublicMediaStorage'
AWS_PUBLIC_MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_PUBLIC_MEDIA_LOCATION)

AWS_PRIVATE_MEDIA_LOCATION = 'media/private'
PRIVATE_FILE_STORAGE = 'mysite.storage_backends.PrivateMediaStorage'
```

I used it from this guide https://simpleisbetterthancomplex.com/tutorial/2017/08/01/how-to-setup-amazon-s3-in-a-django-project.html

---------

**If you still have errors, I will have to try to replicate the error on a fresh install.**

**Comment by zyonash** [comment]
Thanks @teury.

I'm trying to basically 1:1 mirror your settings this time, and I'm still getting this error that happens deep within botocore's handlers.py file:

`File "/opt/python/run/venv/local/lib/python3.6/site-packages/botocore/handlers.py", line 200, in validate_bucket_name
  if not VALID_BUCKET.search(bucket) and not VALID_S3_ARN.search(bucket):
  TypeError: expected string or bytes-like object`

It's weird.  It makes me wonder if there's a bug with botocore itself, because the VALID_BUCKET.search(bucket) is just applying a regular expression and seeing if the bucket name is valid.  I'm definitely giving it a valid string.

**Comment by zyonash** [comment]
Well, damn - figured it out.

https://stackoverflow.com/questions/24746582/s3-bucket-returns-nonetype

If you import S3Boto3Storage, it tries getting the bucket name from settings even though it hasn't been set yet.  This was definitely the issue!  Importing isn't necessary since you set it as a string.
