### ISSUE TITLE
Memcached portability error — use cleaner cache keys for users?

### ISSUE THREAD

**Issue by bctiemann** [django-wiki/django-wiki#1065]
I noticed that django-wiki is susceptible to this Django error:
https://code.djangoproject.com/ticket/31654

Which was fixed here:
https://github.com/django/django/commit/b2b2723512dd0024567fba0c680424ebb7fa1149

But I wanted to bring up the actual cause of the error, which might be worth fixing, because the Django fix above only masks the problem (which is that it attempts to warn the developer when you're using cache keys that would cause errors if you ever wanted to use memcached for your cache backend).

Specifically, django-wiki uses cache keys like:

':1:wiki:article:1:en-us:Brian Tiemann'

Which has a space in it, which is apparently incompatible with memcached (hence the warning message in Django).

For distinguishing cache keys based on user, how about using something sanitized or slugified, or even just go by the username or User.id field?

**Comment by benjaoming** [comment]
Hi @bctiemann - thanks for the report! 

```
    def get_cache_content_key(self, user=None):
        """Returns per-article-user cache key."""
        return "{key}:{user}".format(
            key=self.get_cache_key(), user=user.get_username() if user else ""
        )
```

In the code, `get_username()` would normally (?) return something without a space. Should be fixed, anyhow, because usernames with a space is AFAIK allowed and will happen.
