### ISSUE TITLE
Template customization: Extending CSS using sekizai_tags in base.html requires to completely replace a block

### ISSUE THREAD

**Issue by iburadempa** [django-wiki/django-wiki#1079]
For template customization the documentation suggests to extend base_site.html using a custom base.html. When doing so and trying to add custom CSS I had to use sekizai_tags, because there is only this possibility in the html head:

https://github.com/django-wiki/django-wiki/blob/07587cd7ad76d524710b424aa9bf4d85b16756b4/src/wiki/templates/wiki/base_site.html#L14

When using sekizai_tags in an extending template (base.html in my case) one does however need a block (cf. [sekizai docs](https://django-sekizai.readthedocs.io/en/latest/#restrictions) / warning 3 and [this example](https://github.com/django-cms/django-sekizai/issues/36#issuecomment-50616700)). (I used block  wiki_header_navlinks.) For that block itself the sekizai add functionality does not work however; its content will be completely replaced. I am thus forced to completely replace a block if I just want to add CSS.

My suggestion would therefore be to add a conventional block named "stylesheets" to the html head which could be used for that.

In addition and unrelated, I'd like to suggest to enclose at least these lines
https://github.com/django-wiki/django-wiki/blob/07587cd7ad76d524710b424aa9bf4d85b16756b4/src/wiki/templates/wiki/base_site.html#L8-L9
with block tags to be able to customize them and add custom html head meta tags.

**Comment by benjaoming** [comment]
> I am thus forced to completely replace a block if I just want to add CSS.

That should really not be the case.

Have you tried including the block's parent contents with `{{ block.super }}`?

> My suggestion would therefore be to add a conventional block named "stylesheets"

I think that could be done, but perhaps it should be prefixed with `wiki_` so it doesn't name clash with other people's templates.

> In addition and unrelated, I'd like to suggest to enclose at least these lines

I think that might be the kind of block-craze that's best to avoid. If you want to be able to customize every individual line in the existing `base_site.html`, it could be easier to copy-past its contents. It's not a file that changes very often.

**Comment by iburadempa** [comment]
Yes, `{{ block.super }}` works and although the (random) block name may be misleading for developers one could live with that,  if your strategy is not to add more block-modularity, but instead recommend to maintain a modified copy.

**Comment by benjaoming** [comment]
> but instead recommend to maintain a modified copy

Yes, it's definitely not meant as an inconvenience but a sincere recommendation :+1: 

LMK if there is anything that cannot be done in a perceived optimal way.
