### ISSUE TITLE
Release to support django 3.1

### ISSUE THREAD

**Issue by bellini666** [django-wiki/django-wiki#1081]
Hi,

The current release on pypi is limiting the ability to upgrade to django 3.1. And, as far as I can tell, there's no incompatibilities with the version 0.6 and django 3.1.

Would it be possible to release a 0.6.1 release or something like that loosening that requirement?

**Comment by benjaoming** [comment]
0.7 has been released, hope it works :+1:

**Comment by bellini666** [comment]
@benjaoming almost, `django-nyt` still doesn't allow django 3.1 which doesn't allow me to update it. 

As a side-note: This would be ok on older versions of pip, but its new resolver (https://discuss.python.org/t/announcement-pip-20-2-release/4863) is more strict and will not allow those kind of incompatibilities between dependencies. Some manager, like python poetry (https://python-poetry.org/), which I'm using on my projects, already enforces that.

**Comment by benjaoming** [comment]
@bellini666 thanks for pointing that out, I wasn't aware. Will see if we can bump the Django dependency in django-nyt as well without issues.

I wonder if we can reproduce this in the tests as well, since it's a bit sad that the new Django 3.1 test matrix entries are giving false positives.

**Comment by bellini666** [comment]
@benjaoming maybe using the `--use-feature=2020-resolver` in `pip install` will reproduce the error for pip?

The poetry problem can be reproduced by simply creating a project that depends on both `django (^3.1)` and `wiki (^0.7)` (which translates to `django>=3.1` and `wiki>=0.7`). That will give this error:

```
  Because no versions of wiki match >0.7,<0.8
   and wiki (0.7) depends on django-nyt (>=1.1.5,<1.2), wiki (>=0.7,<0.8) requires django-nyt (>=1.1.5,<1.2).
  Because django-nyt (1.1.5) depends on django (>=1.11,<3.1)
   and no versions of django-nyt match >1.1.5,<1.2, django-nyt (>=1.1.5,<1.2) requires django (>=1.11,<3.1).
  Thus, wiki (>=0.7,<0.8) requires django (>=1.11,<3.1).
  So, because tmp depends on both Django (^3.1.2) and wiki (^0.7), version solving failed.
```

**Comment by benjaoming** [comment]
@bellini666 django-nyt has been updated to add Django 3.1 support, and I have just verified that it works with `--use-feature=2020-resolver`. Thanks for reporting :+1:
