### ISSUE TITLE
Support for 24-hour time format

### ISSUE THREAD

**Issue by ghost** [django-wiki/django-wiki#1087]
It would be nice to customize the time format used, such as when an article was last modified. I miss 24-hour format. It could be a setting per installation and/or per account.

It would also be nice with support for ISO 8601 dates like 2020-11-19 but that might be a separate issue.

> This article was last modified: Nov. 19, 2020, 1:35 p.m.

Why do I want it? As a Swedish user it puts more cognitive load on my brain to parse the 12-hour format and to see dates in an unnatural order.

**Comment by benjaoming** [comment]
It seems it could be fixed here:

https://github.com/django-wiki/django-wiki/blob/b0783b3dffab6dde36c2415defaf080636a16b91/src/wiki/templates/wiki/includes/revision_info.html#L10

Have you defined `LANGUAGE_CODE` on your project?

**Comment by LabanSkollerDefensify** [comment]
Thanks for the tip. Yeah I guess I could change a template in just our instance. Now the instance is gone however. I had SSH access to the server which doesn't exist anymore. A colleague set it up.

Regarding LANGUAGE_CODE, if I interpret it correctly that will only change the language, right? I still want US English.

But now this is no issue for me until next time I see a Django Wiki instance. Feel free to handle this issue accordingly but I think every wiki shall have this feature.

**Comment by benjaoming** [comment]
> Thanks for the tip. Yeah I guess I could change a template in just our instance. 

Ah no, I was referencing the template in django-wiki, I'd be happy to review a PR and get it released :)

**Comment by LabanSkollerDefensify** [comment]
Ah, coolt. But I think this should be accompanied by a system and/or user setting. I have no Django experience at all even though I love Python.

**Comment by The-town** [comment]
Hello.
The date and time displayed in the footer on the article seem to be controlled by the following code.

https://github.com/django-wiki/django-wiki/blob/56ae3acbc13580e322e38b86cd68d1e16cab921f/src/wiki/templates/wiki/article.html#L42-L44

When customizing the date and time, I think that use a [built-in filter date](https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#date).
For example:
`{{ article.current_revision.modified | date:"D d M Y" }}`


I suggest that enable users to insert a specific footer for customizing the date and time by extending the `base.html` file.

**Comment by benjaoming** [comment]
Hi @The-town 

You can directly format date and datetime objects to the actively configured and localized setting with `{{ datetime_object|date:"DATETIME_FORMAT" }}`

See: https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#date

**Comment by oscarmcm** [comment]
Closing this issue as using [`DATE_FORMAT`](https://docs.djangoproject.com/en/4.0/ref/settings/#date-format) is enough to solve it.
