### ISSUE TITLE
French translation issue

### ISSUE THREAD

**Issue by HugoDelval** [django-wiki/django-wiki#1092]
Hi,

just letting you know that there is a small french translation issue, which translates `&nbsp;` to `& nbsp;`, making the HTML-entity visible in the attachment section of an article: 

![image](https://user-images.githubusercontent.com/9109308/103526134-b4bd0900-4e80-11eb-8fa7-203c9498aa3e.png)

Hope this can be useful! I tried to join the https://www.transifex.com/django-wiki/django-wiki/ team to propose the change but I don't think I can.

Great project, keep it up! :muscle:

**Comment by benjaoming** [comment]
Hi Hugo

Sorry that this took so long - I have just approved it, please ping me back and I'll pull in any changes, much obliged :pray:

**Comment by HugoDelval** [comment]
Hi @benjaoming I've updated 2 translations, this one and another one in the `Permissions` section which was badly copy-pasted (it's my guess at least)

I'll update some more if I find any problem. Thanks a lot and great project! :muscle:

**Comment by benjaoming** [comment]
Thanks for looking into this as well @HugoDelval - great to have quality and useful translations.

**Comment by benjaoming** [comment]
The fix will be part of the next release.
