### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by FumbleBe** [django-wiki/django-wiki#1097]
django-admin.py --version
3.1.5

python --version
Python 3.9.1

uname -a
Linux  4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

pipenv graph | grep wiki
wiki==0.7.2

It seems that notifications is not working.
If a user subscribe to an article modifications. When another user modify this article, the number in the navbar is not incremented, and "notifications" disappear from user drop-down menu in navbar (you can reproduce this on the demo server).
![2021-01-08_16h05_08](https://user-images.githubusercontent.com/14941083/104032251-2fae5880-51ce-11eb-8543-8f23a0267e52.png)

If you hit "clear notifications list", "No notifications" reaper in drop-down

![2021-01-08_16h27_43](https://user-images.githubusercontent.com/14941083/104032454-769c4e00-51ce-11eb-8c1c-2d1f0b497fd1.png)

**Comment by benjaoming** [comment]
Confirming this issue. While I don't see any JavaScript errors, I do see the correct JSON being fetched. So it's definitely a new issue in the frontend/JS department.

![image](https://user-images.githubusercontent.com/374612/104494226-74732e80-55d6-11eb-8c46-91fd0fcecad4.png)

If you are able to fix it, I will gladly have a look, merge and release :pray:
