### ISSUE TITLE
Error when editing a page (version 0.7.3)

### ISSUE THREAD

**Issue by ChistobAlex** [django-wiki/django-wiki#1108]
Error when editing the page. In the debugger a message is displayed (Screenshot) and in the editor the items "macros" and "pictures" are not available. (Screenshot).

Unfortunately this error repeats from version to version. At the moment I'm having problems with version 0.7.3

![2021-02-12_11-32-36](https://user-images.githubusercontent.com/20241964/107746198-77bd1f80-6d26-11eb-8533-994aa3822d6f.png)
![2021-02-12_11-34-59](https://user-images.githubusercontent.com/20241964/107746203-7a1f7980-6d26-11eb-8ed7-407a60c1959c.png)
![2021-02-12_11-36-23](https://user-images.githubusercontent.com/20241964/107746276-98857500-6d26-11eb-9d72-f5e38178333c.png)

**Comment by benjaoming** [comment]
Hi @ChistobAlex 

I cannot tell what the exception is from these screenshots. You'll have to run django-wiki with `DEBUG = True` and post a proper and full traceback.

(Normally screenshots can supplement a traceback text and log output, but they cannot stand on their own)

These panels work fine in the demo.
