### ISSUE TITLE
font awesome external-link icon is broken

### ISSUE THREAD

**Issue by ryan-esty** [django-wiki/django-wiki#1111]
We just updated to the latest wiki and fa-external-link is no longer displaying the icon for external links in the wiki.
I believe when the project was updated for font awesome fa-external-link changed to fa-external-link-alt and needs to be changed below:
https://github.com/django-wiki/django-wiki/blob/a691267773c218479fe60c8ef04b7a2dd02fb393/src/wiki/plugins/links/mdx/urlize.py#L143

If I'm not mistaken the pro-version of font awesome still has fa-external-link but I'm not sure if there were plans on handling that.

**Comment by benjaoming** [comment]
The icon is restored!

Thank you so much for reporting this @ryan-esty 

![Uploading image.png…]()
