### ISSUE TITLE
Absolute links can be wiki links – how to parameterize tests?

### ISSUE THREAD

**Issue by Anaphory** [django-wiki/django-wiki#1114]
One red link test, as well as the markdown extension of the red link plugin (otherwise the test would fail, of course), assume that absolute links are external links. This is not true if the wiki root is the document root.
Where does this assumption come from? Why should it be there? If I imagine a flat wiki, where most articles are immediate children of the wiki root, then nearly all internal links are in fact best phrased as absolute links, aren't they?

I asked nearly the same question, although from a different and slightly more naïve perspective, [in the google group](https://groups.google.com/g/django-wiki/c/ympYo09BYJU).

https://github.com/django-wiki/django-wiki/blob/321c0ad913dc0937350da6420079961d5ac48eaa/tests/plugins/redlinks/test_redlinks.py#L28-L30

**Comment by Anaphory** [comment]
This discrepancy is even more visible in

https://github.com/django-wiki/django-wiki/blob/3843e51ed280f2da6d18bdd30be250916a570ab7/tests/plugins/macros/test_links.py#L7-L14

Clearly, by design, this wiki link should be an internal link, yet the test asserts that this link be styled `wiki-external`.

**Comment by Anaphory** [comment]
How could we parameterize the tests over both the case where the wiki root is the root of the server's paths and where the wiki root is not the root of the server's paths? I think this would be useful, but I don't understand the testing infrastructure well enough.

**Comment by Anaphory** [comment]
There are some URL manipulations in [test_urls.py](https://github.com/django-wiki/django-wiki/blob/master/tests/core/test_urls.py).
Naïvely, I would add a new test class where it matters that essentially derives from the base TestCase I want to modify and ‘mixes in’ (not literally, I guess?) test_urls.ArticleModelReverseMethodTest. Would that be a sensible way to go about this?

**Comment by benjaoming** [comment]
> One red link test, as well as the markdown extension of the red link plugin (otherwise the test would fail, of course), assume that absolute links are external links. This is not true if the wiki root is the document root.
Where does this assumption come from? Why should it be there?

I'm not sure where the assumption comes from. It sounds wrong. Absolute links like `/wiki/article-slug` should some be external.

But you can have django-wiki active at different places in the Django urlconf. So for instance. `/admin` or `/static/` can exist as a link in a wiki article but be treated as an external link. I think that this may have been the intention?

**Comment by Anaphory** [comment]
I think with mixin of the url test urlconfig into the red link tests (part of #1115), this is solved for now.
