### ISSUE TITLE
French translation issue

### ISSUE THREAD

**Issue by paulgreg** [django-wiki/django-wiki#1149]
Hello,

I notice a bad french translation for «  Page d'acceuil » : it’s « Page d'accueil ».

I’m willing to fix translation issue myself (that one and other one if I see others) but I don’t know how to do that. 
I created an account on transiflex (paulgreg) a few days ago in hope to do a « pull request » but transiflex doesn’t seems to work like github.

**Comment by benjaoming** [comment]
Hi @paulgreg - thanks for reporting this, I've made the change on Transifex

It's been fixed, but with that sort of very basic error, perhaps it would be great with an additional review? You are welcome to send a request to join the French translation team on Transifex.

Thanks!

**Comment by benjaoming** [comment]
I've approved the request to join the French team :+1:
