### ISSUE TITLE
Preview gives me a multiple X-Frame-Options error

### ISSUE THREAD

**Issue by ericlighthofmann** [django-wiki/django-wiki#1151]
Hi - here's the error I receive when trying to use the preview feature:

Refused to display 'https://mysite.com/' in a frame because it set multiple 'X-Frame-Options' headers with conflicting values ('SAMEORIGIN, DENY'). Falling back to 'deny'

Any ideas?

**Comment by benjaoming** [comment]
It could sound like you are setting the same HTTP header in several places. Perhaps the `DENY` is dispatched by Django (that's the default setting) and a `SAMEORIGIN` is set by your out HTTP server.

See: https://docs.djangoproject.com/en/3.2/ref/clickjacking/
