### ISSUE TITLE
Error 500 when trying to create a new user with an existing username

### ISSUE THREAD

**Issue by paulgreg** [django-wiki/django-wiki#1152]
To reproduce :
1. create a first user
2. create a new user with same username as first one
3. IntegrityError at /_accounts/sign-up/ - (1062, "Duplicate entry '...' for key 'username'") (500 in production)

Expected :
An error message on creation form telling user that username already exists and asking him to user another one.

**Comment by benjaoming** [comment]
Thanks for opening this - I imagine that the ModelForm in front of the User model isn't compliant with the model's validation. As you say, it should be validating the uniqueness of the username.
