### ISSUE TITLE
Block new user creation if email already exists in database

### ISSUE THREAD

**Issue by paulgreg** [django-wiki/django-wiki#1153]
It is possible to create a new user with an existing email in database.

I don’t think it’s a good idea since user may create a new account when he forgot he’s already got one.

I would suggest to block user creation if email is already in database and propose a way to recover username or password if forgotten.

**Comment by benjaoming** [comment]
Hi @paulgreg - it's normal to implement a different behavior for user account handling - both login and signup. Basically, you could replace Django's User model with something where the email address becomes the username.

You can read more about the subject here: https://docs.djangoproject.com/en/3.2/topics/auth/customizing/

As django-wiki isn't actually trying to provide this functionality but merely have the most fundamental signup/login view for whatever User model is used, I will close this issue.

If you can provide anything on top of the current behavior that doesn't require changing the user model or authentication plugin, you are more than welcome to do so :+1:

**Comment by paulgreg** [comment]
Ok. I will customize the signup/login on my app.
Thanks.
