### ISSUE TITLE
Search in Attachment report Python Exception when actual files containning the keyword missing from harddrive

### ISSUE THREAD

**Issue by kylecapricious2** [django-wiki/django-wiki#1162]
![image](https://user-images.githubusercontent.com/25790388/149649947-88ffa3ce-9efd-4b14-9d38-9de1410c7630.png)

![image](https://user-images.githubusercontent.com/25790388/149649959-ee3447a3-a436-45b8-aca9-23e90f0b4a7c.png)

If the actual file(say note-an-en-grammar.docx.upload) corresponding to an attachment record were missing(due to all sorts of reason, like improper disk backup when migrating from server to server.... ), it would not impact the attachment page, and the attachment list table shows a "0KB" size, thanks to the "exception-proof" style  get_size() in  https://github.com/django-wiki/django-wiki/blob/1a7849097b75aaf792ecb9b1a64526a768c41ed8/src/wiki/plugins/attachments/models.py .

However, if user were to search a keyword contained in the above example in attachment search form , say keyword "a", normally it should show the search record "note-an-en-grammar.docx". But due to an "exception-non-free" approach to calculate file size, it triggers an exception saying the file is not there. It does not matter even if the attachment record is deleted from the list - it could still trigger such exception when searching keywords contained in the filename, because deleting record in the attachment page is only placing a "delete' mark, the search would still try to show it as a search result, thus triggering the same issue mention above.

Not sure if this is a bug.

**Comment by benjaoming** [comment]
Thanks for reporting this! The issue was a simple and easy one to fix.
