### ISSUE TITLE
Switch to GitHub workflows?

### ISSUE THREAD

**Issue by atombrella** [django-wiki/django-wiki#1168]
GitHub workflows/actions have matured, and it's integrated directly with the repository, unlike CircleCI. There are also more free minutes on GitHub workflows. 

Somewhat related, if you'd like, it's also possible to configure [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

This issue could be marked as `easy-pickings`, if you like the idea.

**Comment by benjaoming** [comment]
As maintainer, I've had a good time with CircleCI. Are there any features missing in the current integration?

I see it as a strategic blunder to turn Github into a 100% vendor lock-in for everything Open Source. It's also nice to have multiple horses in the race, so we continue to be familiar with and understand alternatives to Github.

**Comment by atombrella** [comment]
> As maintainer, I've had a good time with CircleCI. Are there any features missing in the current integration?

Not really. GitHub workflows can do a bit more with some event types and when branches shou, I think.

Anyway, one thing that CircleCI does support which would make the `config.yaml` file a bit easier to maintain is a [matrix](https://circleci.com/blog/circleci-matrix-jobs/)

> I see it as a strategic blunder to turn Github into a 100% vendor lock-in for everything Open Source. It's also nice to have multiple horses in the race, so we continue to be familiar with and understand alternatives to Github.

That's a good and valid argument :)

**Comment by benjaoming** [comment]
> Anyway, one thing that CircleCI does support which would make the config.yaml file a bit easier to maintain is a [matrix](https://circleci.com/blog/circleci-matrix-jobs/)

Yes, would love to see that in action -- I remember getting stuck trying to execute several different version of Python requiring different images. That's why the current implementation landed where it is, but I hardly think that it's the best solution.

**Comment by benjaoming** [comment]
Thanks for opening this! I think we can reopen this if the need becomes more acute :+1:
