### ISSUE TITLE
latest demo seems to have lost its css

### ISSUE THREAD

**Issue by yengip** [django-wiki/django-wiki#1191]
I just tried looking at the latest demo.  It renders with no style and shows errors on the console: 
"Failed to load resource: the server responded with a status of 404 (Not Found) colorbox.css"
"Failed to load resource: the server responded with a status of 404 (Not Found) wiki-bootstrap.min.css"

**Comment by benjaoming** [comment]
Thanks! The demo server is on an outdated platform, fixing!

**Comment by benjaoming** [comment]
Alright, the server has been upgraded, thanks a lot for quickly posting this :
