### ISSUE TITLE
Use pyproject.toml, replace setup.cfg and setup.py

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#1199]
This project can use https://github.com/pypa/build

We should migrate all logic from setup.cfg and setup.py to pyproject.toml.

* The release command in Makefile should be updated.
* Instead of `from wiki import __version__`, we need to hard-code the version string in pyproject.toml

Nice-to-have:

* A tool to bump versions

**Comment by oscarmcm** [comment]
Discussion for this issue is happening at #1226
