### ISSUE TITLE
Optimized ArticleRevision queries and added tests for the same #1202

### ISSUE THREAD

**Issue by Dev-Mehta** [django-wiki/django-wiki#1203]
Hey folks, this is my first time contributing to this repository and I have noticed that there might be some scope for performance improvement in some areas.

To explore the same, I have written one test for `ArticleRevision` model and added it to [`tests/core/test_models.py`](https://github.com/Dev-Mehta/django-wiki/blob/Dev-Mehta-Optimization-Of-Queries/tests/core/test_models.py#L154-L189).

Can someone check the code and verify whether it is fine, if yes I can optimize queries for all models.

Sample Test Result:
![image](https://user-images.githubusercontent.com/55938019/183664359-a94ef270-ed63-4951-8026-a08970b1086b.png)

Pull Request Link: #1202

**Comment by oscarmcm** [comment]
Fixed in #1202
