### ISSUE TITLE
on_revision_delete > out of index range

### ISSUE THREAD

**Issue by JasonQVan** [django-wiki/django-wiki#1221]
I propose #1220 for the following code. The error occurs when you try to replace an attachment while selecting the checkbox for "Remove previous attachment revisions and their files (to save space)?. This code should make sure that len(path) is not 0 and set max_depth to default of 1. 

https://github.com/django-wiki/django-wiki/blob/d1f4589554b28401dbe252b2cf3c68abd36bd89c/src/wiki/plugins/attachments/models.py#L174-L178

**Comment by oscarmcm** [comment]
Fixed in #1220
