### ISSUE TITLE
SHOW_MAX_CHILDREN setting is ignored

### ISSUE THREAD

**Issue by mck9** [django-wiki/django-wiki#1231]
There is a hardcoded value of 20 in wiki/views/mixins.py
<pre>
kwargs["children_slice"] = self.children_slice[:20]
kwargs["children_slice_more"] = len(self.children_slice) > 20
</pre>

**Comment by benjaoming** [comment]
Looks like you are right. It's like the setting is only used to fetch that amount of children, but then it gets sliced to 20 no matter what. Setting it to 30 would still trim it to 20.

If you can fix and test this (manually is fine), that would be most welcome :+1:
