### ISSUE TITLE
Broken Django-Wiki demo

### ISSUE THREAD

**Issue by oscarmcm** [django-wiki/django-wiki#1278]
### Discussed in https://github.com/django-wiki/django-wiki/discussions/1277

<div type='discussions-op-text'>

<sup>Originally posted by **cyberpunk256** April 12, 2023</sup>
demo link doesnt work</div>

**Comment by oscarmcm** [comment]
@benjaoming have any log that can helps with this?

**Comment by benjaoming** [comment]
haha... it's because GitHub has changed their SSH host keys :face_exhaling: 

but it's also because I haven't configured any notifications on the site's uptime, which is weird... doing that now :)

**Comment by benjaoming** [comment]
This one again https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

Spent so much time on that :(

**Comment by oscarmcm** [comment]
Yeah, happened to me this week too.
