### ISSUE TITLE
Grant more permissions in demo

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#1290]
## Expected Behavior

We need to use the wiki to show and test django-wiki, which involves having admin rights.

## Current Behavior

Current demo site doesn't grant any useful permissions to the `admin:admin` user. So it's impossible edit and add articles :/

## Context (Environment)

https://demo.django-wiki.org/

**Comment by oscarmcm** [comment]
@benjaoming what kind of permissions do we need to grant to the admin user?

**Comment by benjaoming** [comment]
@oscarmcm I'm leaning towards superuser. The entire application and database is destroyed pretty often. I think it's nice to be able to quickly triage or ask people to reproduce issues on the demo. It's of course also nice for someone getting familiar with django-wiki to be able to navigate everywhere, create users, see the django admin etc.
