### ISSUE TITLE
[Bug]:X-Frame-Options Cross-Domain Issue

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#1293]
### Discussed in https://github.com/django-wiki/django-wiki/discussions/1291

<div type='discussions-op-text'>

<sup>Originally posted by **liuxiawei** June 11, 2023</sup>
### Describe the bug

In class MergeView, It should add `@method_decorator(xframe_options_sameorigin)` in line 913
![image](https://github.com/django-wiki/django-wiki/assets/5093541/637bca17-1b7b-4bfc-833f-54c76e418e2a)
Or it would be error while merge article

### Steps to reproduce.

1. Go to 'Article history'
2. Click on 'Merge Selected with current ...'

### Python Version

3.10.8

### Django Version

4.2

### Extra context

Firefox</div>

**Comment by benjaoming** [comment]
@liuxiawei thanks for reporting this!! since you already did most of the work reporting this: is it a bug that you would be able to put in a PR to solve?

**Comment by liuxiawei** [comment]
Of course, I would be honored to contribute to this project and add my own contribution.

**Comment by benjaoming** [comment]
Fixed in #1294 - great work @liuxiawei :raised_hands:
