### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by gmummaw** [django-wiki/django-wiki#177]
I'm having problems with getting images to show up.

Pages show "Image not found" but I can still browse images, they upload successfully, they just don't show.

I can see in my media folder that images are going into there (/media/wiki/images/1/043d6f8db89b72f0a9c39a4030363e78/picture.png).

Have gone through the process of setting up django-wiki in a project several times and have come to this same problem. Help is greatly appreciated, I really like django-wiki.

STATIC_URL, MEDIA_URL and STATIC_ROOT, MEDIA_ROOT are all set like so:

MEDIA_ROOT = os.path.join(PROJECT_PATH, "media")
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(PROJECT_PATH, "static")
STATIC_URL = '/static/'

**Comment by Forethinker** [comment]
I am facing this problem on wiki 0.1 / ubuntu LTS 14.04.2. Nothing shows up when I enable `THUMBNAIL_DEBUG` and the images do not resolve when I look them up manually. I install all the dependencies:

    sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk

and and install the pillow: `pip install pillow`:

    --------------------------------------------------------------------
    PIL SETUP SUMMARY                                                   
    --------------------------------------------------------------------
    version      Pillow 2.8.1                                           
    platform     linux2 2.7.6 (default, Mar 22 2014, 22:59:56)          
                 [GCC 4.8.2]                                            
    --------------------------------------------------------------------
    --- TKINTER support available                                       
    --- JPEG support available                                          
    *** OPENJPEG (JPEG2000) support not available                       
    --- ZLIB (PNG/ZIP) support available                                
    --- LIBTIFF support available                                       
    --- FREETYPE2 support available                                     
    --- LITTLECMS2 support available                                    
    --- WEBP support available                                          
    --- WEBPMUX support available                                       

Setting MEDIA_ROOT and STATIC_ROOT didn't do anything. What am I missing here? I installed `django-wiki` using the following command:

    pip install git+git://github.com/benjaoming/django-wiki.git

**Comment by rschwiebert** [comment]
I'm having this same problem with a png. 

Imagine five png files in parallel subfolders of the static folder. All five appear to be served correctly from the CDN, and their urls are fine in the HTML sourcecode. You can click the links on those urls for the first four and the static image appears. But on the fifth one, it inexplicably redirects you to the one with the appended slash. Removing the slash from the end of that url, you wind up seeing the asset just as with the first four.

That's where I'm stuck. I have no idea why the one file apparently behaves differently from the other four. Their names are even nearly identical.
