### ISSUE TITLE
Bootstrapped Editor UI

### ISSUE THREAD

**Issue by robmoggach** [django-wiki/django-wiki#200]
Seems like this is the only piece that isn't bootstrapped...
Would be nice to use https://github.com/addyosmani/jquery-ui-bootstrap.git

**Comment by benjaoming** [comment]
We'll change the default editor to SimpleMDE. These javascript libraries look nice, but I think it's better for the default editor to be a widely-used pick.

Thanks for doing research and coming up with ideas :)
