### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by heinrich5991** [django-wiki/django-wiki#209]
Since Django 1.5 supports python 3, it would be nice if this project would, too.

**Comment by benjaoming** [comment]
Using pyqver to test Python 2 compatibility
=================================

Method:

    find ../django-wiki/ -name '*.py' -exec echo -n "{} " \; | xargs python pyqver2.py -m 2.6

Since pyqver doesn't check for old-style Exception syntax, we'll grep for that, too...

    find ../django-wiki/ -name '*.py' -exec echo -n "{} " \; | xargs egrep 'except [^(]+,'

Command finds all .py files and feeds them to pyqver2.py. The results are in:

    2.2	../django-wiki/runtests.py
    2.6	../django-wiki/custom_user_auth_south_refactor.py
    2.2	../django-wiki/wiki/urls.py
    2.6	../django-wiki/wiki/models/urlpath.py
    2.5	../django-wiki/wiki/models/pluginbase.py
    2.2	../django-wiki/wiki/models/__init__.py
    2.6	../django-wiki/wiki/models/article.py
    2.5	../django-wiki/wiki/south_migrations/0002_auto__add_field_articleplugin_created.py
    2.5	../django-wiki/wiki/south_migrations/0010_auto__chg_field_imagerevision_image.py
    2.5	../django-wiki/wiki/south_migrations/0013_auto__chg_field_attachmentrevision_previous_revision__chg_field_revisi.py
    2.5	../django-wiki/wiki/south_migrations/0005_auto__chg_field_urlpath_article.py
    2.5	../django-wiki/wiki/south_migrations/0004_populate_urlpath__article.py
    2.5	../django-wiki/wiki/south_migrations/0006_auto__add_attachmentrevision__add_image__add_attachment.py
    2.5	../django-wiki/wiki/south_migrations/0012_auto__chg_field_attachmentrevision_user__chg_field_attachmentrevision_.py
    2.0	../django-wiki/wiki/south_migrations/__init__.py
    2.5	../django-wiki/wiki/south_migrations/0001_initial.py
    2.5	../django-wiki/wiki/south_migrations/0008_auto__add_simpleplugin__add_revisionpluginrevision__add_imagerevision_.py
    2.5	../django-wiki/wiki/south_migrations/0003_auto__add_field_urlpath_article.py
    2.5	../django-wiki/wiki/south_migrations/0009_auto__add_field_imagerevision_width__add_field_imagerevision_height.py
    2.5	../django-wiki/wiki/south_migrations/0011_auto__chg_field_imagerevision_width__chg_field_imagerevision_height.py
    2.5	../django-wiki/wiki/south_migrations/0007_auto__add_articlesubscription.py
    2.6	../django-wiki/wiki/management/commands/wikiviz.py
    2.0	../django-wiki/wiki/management/commands/__init__.py
    2.0	../django-wiki/wiki/management/__init__.py
    2.5	../django-wiki/wiki/forms.py
    2.2	../django-wiki/wiki/tests/base.py
    2.1	../django-wiki/wiki/tests/__init__.py
    2.1	../django-wiki/wiki/tests/testdata/urls.py
    2.0	../django-wiki/wiki/tests/testdata/__init__.py
    2.2	../django-wiki/wiki/tests/testdata/models.py
    2.6	../django-wiki/wiki/tests/test_basic.py
    2.1	../django-wiki/wiki/__init__.py
    2.2	../django-wiki/wiki/apps.py
    2.2	../django-wiki/wiki/views/mixins.py
    2.0	../django-wiki/wiki/views/__init__.py
    2.5	../django-wiki/wiki/views/article.py
    2.2	../django-wiki/wiki/views/accounts.py
    2.2	../django-wiki/wiki/core/exceptions.py
    2.2	../django-wiki/wiki/core/markdown/__init__.py
    2.0	../django-wiki/wiki/core/markdown/mdx/__init__.py
    2.2	../django-wiki/wiki/core/markdown/mdx/previewlinks.py
    2.3	../django-wiki/wiki/core/http.py
    2.1	../django-wiki/wiki/core/diff.py
    2.0	../django-wiki/wiki/core/__init__.py
    2.1	../django-wiki/wiki/core/compat.py
    2.2	../django-wiki/wiki/core/plugins/base.py
    2.2	../django-wiki/wiki/core/plugins/loader.py
    2.0	../django-wiki/wiki/core/plugins/__init__.py
    2.1	../django-wiki/wiki/core/plugins/registry.py
    2.2	../django-wiki/wiki/core/permissions.py
    2.1	../django-wiki/wiki/core/utils.py
    2.2	../django-wiki/wiki/decorators.py
    2.5	../django-wiki/wiki/conf/settings.py
    2.0	../django-wiki/wiki/conf/__init__.py
    2.1	../django-wiki/wiki/editors/base.py
    2.2	../django-wiki/wiki/editors/markitup.py
    2.1	../django-wiki/wiki/editors/__init__.py
    2.0	../django-wiki/wiki/plugins/mediawikiimport/management/commands/__init__.py
    2.3	../django-wiki/wiki/plugins/mediawikiimport/management/commands/mediawiki_import.py
    2.0	../django-wiki/wiki/plugins/mediawikiimport/management/__init__.py
    2.0	../django-wiki/wiki/plugins/mediawikiimport/__init__.py
    2.4	../django-wiki/wiki/plugins/links/views.py
    2.1	../django-wiki/wiki/plugins/links/settings.py
    2.0	../django-wiki/wiki/plugins/links/__init__.py
    2.2	../django-wiki/wiki/plugins/links/wiki_plugin.py
    2.2	../django-wiki/wiki/plugins/links/mdx/djangowikilinks.py
    2.0	../django-wiki/wiki/plugins/links/mdx/__init__.py
    2.2	../django-wiki/wiki/plugins/links/mdx/urlize.py
    2.1	../django-wiki/wiki/plugins/links/models.py
    2.2	../django-wiki/wiki/plugins/haystack/views.py
    2.4	../django-wiki/wiki/plugins/haystack/__init__.py
    2.2	../django-wiki/wiki/plugins/haystack/search_indexes.py
    2.1	../django-wiki/wiki/plugins/attachments/urls.py
    2.5	../django-wiki/wiki/plugins/attachments/south_migrations/0002_auto__chg_field_attachmentrevision_previous_revision__chg_field_attach.py
    2.0	../django-wiki/wiki/plugins/attachments/south_migrations/__init__.py
    2.5	../django-wiki/wiki/plugins/attachments/south_migrations/0001_initial.py
    2.5	../django-wiki/wiki/plugins/attachments/views.py
    2.2	../django-wiki/wiki/plugins/attachments/forms.py
    2.5	../django-wiki/wiki/plugins/attachments/settings.py
    2.2	../django-wiki/wiki/plugins/attachments/markdown_extensions.py
    2.6	../django-wiki/wiki/plugins/attachments/tests/test_views.py
    2.1	../django-wiki/wiki/plugins/attachments/tests/__init__.py
    2.1	../django-wiki/wiki/plugins/attachments/__init__.py
    2.5	../django-wiki/wiki/plugins/attachments/wiki_plugin.py
    2.6	../django-wiki/wiki/plugins/attachments/models.py
    2.2	../django-wiki/wiki/plugins/attachments/admin.py
    2.1	../django-wiki/wiki/plugins/macros/settings.py
    2.0	../django-wiki/wiki/plugins/macros/__init__.py
    2.2	../django-wiki/wiki/plugins/macros/wiki_plugin.py
    2.4	../django-wiki/wiki/plugins/macros/mdx/toc.py
    2.0	../django-wiki/wiki/plugins/macros/mdx/__init__.py
    2.2	../django-wiki/wiki/plugins/macros/mdx/wikilinks.py
    2.2	../django-wiki/wiki/plugins/macros/mdx/macro.py
    2.4	../django-wiki/wiki/plugins/macros/templatetags/wiki_macro_tags.py
    2.0	../django-wiki/wiki/plugins/macros/templatetags/__init__.py
    2.0	../django-wiki/wiki/plugins/images/south_migrations/__init__.py
    2.5	../django-wiki/wiki/plugins/images/south_migrations/0001_initial.py
    2.5	../django-wiki/wiki/plugins/images/south_migrations/0002_auto__add_imagerevision__del_field_image_image.py
    2.4	../django-wiki/wiki/plugins/images/views.py
    2.2	../django-wiki/wiki/plugins/images/forms.py
    2.5	../django-wiki/wiki/plugins/images/settings.py
    2.2	../django-wiki/wiki/plugins/images/markdown_extensions.py
    2.1	../django-wiki/wiki/plugins/images/__init__.py
    2.2	../django-wiki/wiki/plugins/images/wiki_plugin.py
    2.6	../django-wiki/wiki/plugins/images/models.py
    2.1	../django-wiki/wiki/plugins/images/templatetags/wiki_thumbnails.py
    2.0	../django-wiki/wiki/plugins/images/templatetags/__init__.py
    2.4	../django-wiki/wiki/plugins/images/templatetags/wiki_images_tags.py
    2.2	../django-wiki/wiki/plugins/images/admin.py
    2.0	../django-wiki/wiki/plugins/__init__.py
    2.0	../django-wiki/wiki/plugins/notifications/south_migrations/__init__.py
    2.2	../django-wiki/wiki/plugins/notifications/south_migrations/0001_initial.py
    2.4	../django-wiki/wiki/plugins/notifications/views.py
    2.0	../django-wiki/wiki/plugins/notifications/management/commands/__init__.py
    2.3	../django-wiki/wiki/plugins/notifications/management/commands/wiki_notifications_create_defaults.py
    2.0	../django-wiki/wiki/plugins/notifications/management/__init__.py
    2.5	../django-wiki/wiki/plugins/notifications/forms.py
    2.5	../django-wiki/wiki/plugins/notifications/settings.py
    2.1	../django-wiki/wiki/plugins/notifications/util.py
    2.1	../django-wiki/wiki/plugins/notifications/__init__.py
    2.2	../django-wiki/wiki/plugins/notifications/wiki_plugin.py
    2.6	../django-wiki/wiki/plugins/notifications/models.py
    2.0	../django-wiki/wiki/plugins/help/views.py
    2.0	../django-wiki/wiki/plugins/help/__init__.py
    2.2	../django-wiki/wiki/plugins/help/wiki_plugin.py
    2.1	../django-wiki/wiki/plugins/help/models.py
    2.2	../django-wiki/wiki/managers.py
    2.0	../django-wiki/wiki/templatetags/__init__.py
    2.4	../django-wiki/wiki/templatetags/wiki_tags.py
    2.2	../django-wiki/wiki/admin.py
    2.0	../django-wiki/docs/__init__.py
    2.1	../django-wiki/docs/conf.py
    2.2	../django-wiki/setup.py
    2.1	../django-wiki/testproject/manage.py
    2.1	../django-wiki/testproject/testproject/urls.py
    2.0	../django-wiki/testproject/testproject/__init__.py
    2.1	../django-wiki/testproject/testproject/settings/codehilite.py
    2.1	../django-wiki/testproject/testproject/settings/haystack.py
    2.2	../django-wiki/testproject/testproject/settings/sendfile.py
    2.2	../django-wiki/testproject/testproject/settings/__init__.py
    2.0	../django-wiki/testproject/testproject/settings/local.py
    2.1	../django-wiki/testproject/testproject/settings/customauthuser.py
    2.1	../django-wiki/testproject/testproject/wsgi.py

**Comment by benjaoming** [comment]
Using pyqver for Python 3
====================

    3.0	../django-wiki/runtests.py
    3.0	../django-wiki/custom_user_auth_south_refactor.py
    3.0	../django-wiki/wiki/urls.py
    3.0	../django-wiki/wiki/models/urlpath.py
    3.0	../django-wiki/wiki/models/pluginbase.py
    3.0	../django-wiki/wiki/models/__init__.py
    3.0	../django-wiki/wiki/models/article.py
    3.0	../django-wiki/wiki/south_migrations/0002_auto__add_field_articleplugin_created.py
    3.0	../django-wiki/wiki/south_migrations/0010_auto__chg_field_imagerevision_image.py
    3.0	../django-wiki/wiki/south_migrations/0013_auto__chg_field_attachmentrevision_previous_revision__chg_field_revisi.py
    3.0	../django-wiki/wiki/south_migrations/0005_auto__chg_field_urlpath_article.py
    3.0	../django-wiki/wiki/south_migrations/0004_populate_urlpath__article.py
    3.0	../django-wiki/wiki/south_migrations/0006_auto__add_attachmentrevision__add_image__add_attachment.py
    3.0	../django-wiki/wiki/south_migrations/0012_auto__chg_field_attachmentrevision_user__chg_field_attachmentrevision_.py
    3.0	../django-wiki/wiki/south_migrations/__init__.py
    3.0	../django-wiki/wiki/south_migrations/0001_initial.py
    3.0	../django-wiki/wiki/south_migrations/0008_auto__add_simpleplugin__add_revisionpluginrevision__add_imagerevision_.py
    3.0	../django-wiki/wiki/south_migrations/0003_auto__add_field_urlpath_article.py
    3.0	../django-wiki/wiki/south_migrations/0009_auto__add_field_imagerevision_width__add_field_imagerevision_height.py
    3.0	../django-wiki/wiki/south_migrations/0011_auto__chg_field_imagerevision_width__chg_field_imagerevision_height.py
    3.0	../django-wiki/wiki/south_migrations/0007_auto__add_articlesubscription.py
    3.0	../django-wiki/wiki/management/commands/wikiviz.py
    3.0	../django-wiki/wiki/management/commands/__init__.py
    3.0	../django-wiki/wiki/management/__init__.py
    3.0	../django-wiki/wiki/forms.py
    3.0	../django-wiki/wiki/tests/base.py
    3.0	../django-wiki/wiki/tests/__init__.py
    3.0	../django-wiki/wiki/tests/testdata/urls.py
    3.0	../django-wiki/wiki/tests/testdata/__init__.py
    3.0	../django-wiki/wiki/tests/testdata/models.py
    3.0	../django-wiki/wiki/tests/test_basic.py
    3.0	../django-wiki/wiki/__init__.py
    3.0	../django-wiki/wiki/apps.py
    3.0	../django-wiki/wiki/views/mixins.py
    3.0	../django-wiki/wiki/views/__init__.py
    3.0	../django-wiki/wiki/views/article.py
    3.0	../django-wiki/wiki/views/accounts.py
    3.0	../django-wiki/wiki/core/exceptions.py
    3.0	../django-wiki/wiki/core/markdown/__init__.py
    3.0	../django-wiki/wiki/core/markdown/mdx/__init__.py
    3.0	../django-wiki/wiki/core/markdown/mdx/previewlinks.py
    3.0	../django-wiki/wiki/core/http.py
    3.0	../django-wiki/wiki/core/diff.py
    3.0	../django-wiki/wiki/core/__init__.py
    3.0	../django-wiki/wiki/core/compat.py
    3.0	../django-wiki/wiki/core/plugins/base.py
    3.0	../django-wiki/wiki/core/plugins/loader.py
    3.0	../django-wiki/wiki/core/plugins/__init__.py
    3.0	../django-wiki/wiki/core/plugins/registry.py
    3.0	../django-wiki/wiki/core/permissions.py
    3.0	../django-wiki/wiki/core/utils.py
    3.0	../django-wiki/wiki/decorators.py
    3.0	../django-wiki/wiki/conf/settings.py
    3.0	../django-wiki/wiki/conf/__init__.py
    3.0	../django-wiki/wiki/editors/base.py
    3.0	../django-wiki/wiki/editors/markitup.py
    3.0	../django-wiki/wiki/editors/__init__.py
    3.0	../django-wiki/wiki/plugins/mediawikiimport/management/commands/__init__.py
    3.0	../django-wiki/wiki/plugins/mediawikiimport/management/commands/mediawiki_import.py
    3.0	../django-wiki/wiki/plugins/mediawikiimport/management/__init__.py
    3.0	../django-wiki/wiki/plugins/mediawikiimport/__init__.py
    3.0	../django-wiki/wiki/plugins/links/views.py
    3.0	../django-wiki/wiki/plugins/links/settings.py
    3.0	../django-wiki/wiki/plugins/links/__init__.py
    3.0	../django-wiki/wiki/plugins/links/wiki_plugin.py
    3.0	../django-wiki/wiki/plugins/links/mdx/djangowikilinks.py
    3.0	../django-wiki/wiki/plugins/links/mdx/__init__.py
    3.0	../django-wiki/wiki/plugins/links/mdx/urlize.py
    3.0	../django-wiki/wiki/plugins/links/models.py
    3.0	../django-wiki/wiki/plugins/haystack/views.py
    3.0	../django-wiki/wiki/plugins/haystack/__init__.py
    3.0	../django-wiki/wiki/plugins/haystack/search_indexes.py
    3.0	../django-wiki/wiki/plugins/attachments/urls.py
    3.0	../django-wiki/wiki/plugins/attachments/south_migrations/0002_auto__chg_field_attachmentrevision_previous_revision__chg_field_attach.py
    3.0	../django-wiki/wiki/plugins/attachments/south_migrations/__init__.py
    3.0	../django-wiki/wiki/plugins/attachments/south_migrations/0001_initial.py
    3.0	../django-wiki/wiki/plugins/attachments/views.py
    3.0	../django-wiki/wiki/plugins/attachments/forms.py
    3.0	../django-wiki/wiki/plugins/attachments/settings.py
    3.0	../django-wiki/wiki/plugins/attachments/markdown_extensions.py
    3.0	../django-wiki/wiki/plugins/attachments/tests/test_views.py
    3.0	../django-wiki/wiki/plugins/attachments/tests/__init__.py
    3.0	../django-wiki/wiki/plugins/attachments/__init__.py
    3.0	../django-wiki/wiki/plugins/attachments/wiki_plugin.py
    3.0	../django-wiki/wiki/plugins/attachments/models.py
    3.0	../django-wiki/wiki/plugins/attachments/admin.py
    3.0	../django-wiki/wiki/plugins/macros/settings.py
    3.0	../django-wiki/wiki/plugins/macros/__init__.py
    3.0	../django-wiki/wiki/plugins/macros/wiki_plugin.py
    3.0	../django-wiki/wiki/plugins/macros/mdx/toc.py
    3.0	../django-wiki/wiki/plugins/macros/mdx/__init__.py
    3.0	../django-wiki/wiki/plugins/macros/mdx/wikilinks.py
    3.0	../django-wiki/wiki/plugins/macros/mdx/macro.py
    3.0	../django-wiki/wiki/plugins/macros/templatetags/wiki_macro_tags.py
    3.0	../django-wiki/wiki/plugins/macros/templatetags/__init__.py
    3.0	../django-wiki/wiki/plugins/images/south_migrations/__init__.py
    3.0	../django-wiki/wiki/plugins/images/south_migrations/0001_initial.py
    3.0	../django-wiki/wiki/plugins/images/south_migrations/0002_auto__add_imagerevision__del_field_image_image.py
    3.0	../django-wiki/wiki/plugins/images/views.py
    3.0	../django-wiki/wiki/plugins/images/forms.py
    3.0	../django-wiki/wiki/plugins/images/settings.py
    3.0	../django-wiki/wiki/plugins/images/markdown_extensions.py
    3.0	../django-wiki/wiki/plugins/images/__init__.py
    3.0	../django-wiki/wiki/plugins/images/wiki_plugin.py
    3.0	../django-wiki/wiki/plugins/images/models.py
    3.0	../django-wiki/wiki/plugins/images/templatetags/wiki_thumbnails.py
    3.0	../django-wiki/wiki/plugins/images/templatetags/__init__.py
    3.0	../django-wiki/wiki/plugins/images/templatetags/wiki_images_tags.py
    3.0	../django-wiki/wiki/plugins/images/admin.py
    3.0	../django-wiki/wiki/plugins/__init__.py
    3.0	../django-wiki/wiki/plugins/notifications/south_migrations/__init__.py
    3.0	../django-wiki/wiki/plugins/notifications/south_migrations/0001_initial.py
    3.0	../django-wiki/wiki/plugins/notifications/views.py
    3.0	../django-wiki/wiki/plugins/notifications/management/commands/__init__.py
    3.0	../django-wiki/wiki/plugins/notifications/management/commands/wiki_notifications_create_defaults.py
    3.0	../django-wiki/wiki/plugins/notifications/management/__init__.py
    3.0	../django-wiki/wiki/plugins/notifications/forms.py
    3.0	../django-wiki/wiki/plugins/notifications/settings.py
    3.0	../django-wiki/wiki/plugins/notifications/util.py
    3.0	../django-wiki/wiki/plugins/notifications/__init__.py
    3.0	../django-wiki/wiki/plugins/notifications/wiki_plugin.py
    3.0	../django-wiki/wiki/plugins/notifications/models.py
    3.0	../django-wiki/wiki/plugins/help/views.py
    3.0	../django-wiki/wiki/plugins/help/__init__.py
    3.0	../django-wiki/wiki/plugins/help/wiki_plugin.py
    3.0	../django-wiki/wiki/plugins/help/models.py
    3.0	../django-wiki/wiki/managers.py
    3.0	../django-wiki/wiki/templatetags/__init__.py
    3.0	../django-wiki/wiki/templatetags/wiki_tags.py
    3.0	../django-wiki/wiki/admin.py
    3.0	../django-wiki/docs/__init__.py
    3.0	../django-wiki/docs/conf.py
    3.0	../django-wiki/setup.py
    3.0	../django-wiki/testproject/manage.py
    3.0	../django-wiki/testproject/testproject/urls.py
    3.0	../django-wiki/testproject/testproject/__init__.py
    3.0	../django-wiki/testproject/testproject/settings/codehilite.py
    3.0	../django-wiki/testproject/testproject/settings/haystack.py
    3.0	../django-wiki/testproject/testproject/settings/sendfile.py
    3.0	../django-wiki/testproject/testproject/settings/__init__.py
    3.0	../django-wiki/testproject/testproject/settings/local.py
    3.0	../django-wiki/testproject/testproject/settings/customauthuser.py
    3.0	../django-wiki/testproject/testproject/wsgi.py

**Comment by benjaoming** [comment]
So apart from tests passing, a couple of auto-generator tools, we now have this pyqver tool scanning code for python 2 and 3 compatibility. I don't think we can do much better now.

So I'm closing this :)
