### ISSUE TITLE
Add alternate display text to attachment

### ISSUE THREAD

**Issue by chadmv** [django-wiki/django-wiki#214]
It would be nice to be able to add alternate text for an attachment.  Currently it creates a link using the file name of the attachment.

```
# Currently limited to this:
[attachment:17]

# Propose something like
[An interesting pdf](attachment:17)
# or
[attachment:17 title:"A cool link"]
```

**Comment by mkane848** [comment]
Running into this as well, is there a supported way to either overwrite the default filename or force it to display the Description instead?

**Comment by benjaoming** [comment]
This proposal is better because it doesn't interfere with the existing link syntax.

    [attachment:17 title:"A cool link"]

PR is welcome :) I think it can be implemented entirely within `wiki/plugins/attachments/render.html` and `wiki/plugins/attachments/markdown_extensions.py`. But please add tests!
