### ISSUE TITLE
AttributeError: 'Manager' object has no attribute 'get_empty_query_set'

### ISSUE THREAD

**Issue by ljholish** [django-wiki/django-wiki#216]
Trying to add an article via the admin on a fresh virtualenv install gives me this error:

http://dpaste.com/hold/1499687/

Same problem running the testproject with prepopulated sqlite db.

Python 2.7.3
Django 1.6
django-wiki installed from github

Any pointers appreciated. Thanks.

**Comment by cXhristian** [comment]
From what I can tell get_empty_query_set isn't used anywhere in the code anymore so this should be fixed.

**Comment by benjaoming** [comment]
:+1:
