### ISSUE TITLE
Initial installation fails with 'django.db.utils.ProgrammingError: relation "notify_subscription" does not exist'

### ISSUE THREAD

**Issue by spookylukey** [django-wiki/django-wiki#224]
The error is that the migrations for 'wiki' do not depend on the 'django_notify' app.

In particular, you get this error on wiki:0007_auto__add_articlesubscription. It just needs to add:

    depends_on = [("django_notify", "0004")]

**Comment by adw0rd** [comment]
You resolved this problem for the 0.0.24 release? But I downloaded last version (0.0.24.2, from here https://pypi.python.org/pypi/wiki) and I see "django_notify" into "wiki/south_migrations/0007_auto__add_articlesubscription.py".

Why you revert this fix https://github.com/django-wiki/django-wiki/commit/84f7508050698fdeb7088c3cdd5637c0d37ddf8b?

**Comment by benjaoming** [comment]
@adw0rd I'm not sure, it seems like something done shortly after the bug was closed... maybe by mistake. I'm investigating now.

Meanwhile, quickfix: Just disable south and run `syncdb`, you'll get through the migrations without problems.

**Comment by adw0rd** [comment]
@benjaoming thank you!

**Comment by benjaoming** [comment]
Okay, I've tested it... and it works with South and Django 1.7.. all migrations have been run on a clean DB.

Are you actually running into any problems? Can you specify how you encounter them?

**Comment by benjaoming** [comment]
Ah sorry, this is also #394, closing this one again.
