### ISSUE TITLE
plug-in registry not persisting registered plug-ins

### ISSUE THREAD

**Issue by dannybrowne86** [django-wiki/django-wiki#280]
I'm playing around with current `master` branch and am running into an issue where the registry is not maintaining the list of loaded plug-ins.  For example, the attachments plug-in is getting loaded, but when the url patterns are being built, the plug-in urls are not being added to the patterns because `registry.get_plugins().values()` is returning `None` (the `_cache` is an empty list).
From debugging, I can see that the plug-in is indeed getting loaded earlier in the on-the-fly build process, but the `_cache` is empty when the it gets to building the list of url patterns.
Any suggestions on what I may be doing wrong?  I've tried to re-load the plug-ins within the urls module, but that does not seem to be working either.

**Comment by benjaoming** [comment]
No more info, closing.
