### ISSUE TITLE
TOC limits?

### ISSUE THREAD

**Issue by spinozagl** [django-wiki/django-wiki#291]
RuntimeError
Django version: 1.6.5
Python: 2.7.6
maximum recursion depth exceeded in cmp

.../..../wiki/plugins/macros/mdx/toc.py in build_correct, line 56

____________________

The toc in question is 4 levels deep. I've tried to poke around in toc.py without any success. Any pointers?
TOC is rendered well till line x and then if another line is added it raises the exception above.

**Comment by benjaoming** [comment]
Worksforme... even with 5 levels.
