### ISSUE TITLE
Blacklist slug/url patterns or set create privileges

### ISSUE THREAD

**Issue by pknowles** [django-wiki/django-wiki#297]
I'd like to have the wiki as the root of my site, but set aside a section `/blog` that is not managed by django-wiki. This is easily accomplished in `urls.py`, but there's nothing to stop someone entering `/blog` as the slug in a new article. I can think of 2 different solutions:
1. Blacklist certain slugs/urls
2. Only allow admins to create root level articles

Is this possible at the moment?

**Comment by benjaoming** [comment]
This issue was solved by @pknowles a while back with `CHECK_SLUG_URL_AVAILABLE` :)

See: #300
