### ISSUE TITLE
Feature request: Soft roots for URLPath trees

### ISSUE THREAD

**Issue by jluttine** [django-wiki/django-wiki#329]
I would like to be able to adjust that from which level the breadcrumbs start. In my case, I'd like to ignore the first page and start from the first article level below the front page. I have kind of separate wikis. Actually, my use case is such that I have different languages as:
mywiki.com/en/...
mywiki.com/fi/...
mywiki.com/de/...
So, for instance, in the Finnish wiki, the breadcrumbs should be shown starting from mywiki.com/fi/, not mywiki.com.

I have a very simple implementation which includes a tiny context processor and a few extra lines to breadcrumbs.html. The user can modify the starting level by setting BREADCRUMBS_LEVEL (or BREADCRUMBS_ROOT or whatever you would like to call that variable) and add the context processor to the list of context processors. By default, if it is not set, the current behaviour is what happens, that is, show the full breadcrumbs path. But wiki maintainers could change that if they want.

I'm curious if this would be considered useful for the wiki and could it have other use cases, and what the feature should be like in order to be most useful. My use case is that I want to have separate sub-wikis with independent breadcrumbs.

My implementation does not break anything existing nor does it require users to do anything, unless they want to change the root level of the breadcrumbs. If they want to change that, they need to set the variable and add a line to context processors list in settings.py.

Comments?

**Comment by benjaoming** [comment]
A PR could be welcome on this, but I think that the issue is a bit deeper and perhaps about #30
