### ISSUE TITLE
Wiki Bootstrap CSS should be under its own 'namespace'

### ISSUE THREAD

**Issue by cXhristian** [django-wiki/django-wiki#364]
Right now you can get weird styles using wiki-bootstrap and another bootstrap version on your site. 

For example using the class hidden-sm will not work as expected because the bootstrap version included in django-wiki is outdated and works different. 

Wrapping `@import "../bootstrap.less";` (and other relevant CSS) in wiki-bootstrap.less like this should work:

```css
.wiki {
    @import "../bootstrap.less";
}
```

Then all relevant wiki elements on the website has to be wrapped in a .wiki for wiki-bootstrap to kick in. 

The Boostrap version should also be upgraded since it's pretty outdated (2 years old) and not a final release.

**Comment by tbabej** [comment]
+1, this also causes issues on my website. I never knew enough LESS to fix it though, so I just lived with it for now.

**Comment by benjaoming** [comment]
I'm -1 for the suggestion. My reason would be that if you want (as I really think everyone should) to customize the look of the wiki, you can just symlink the wiki-directory or copy the modifications. If you put the whole default Bootstrap inside a .wiki class that you do not intend to make use of, it would make for a lot of unused styling and make it harder to both have your own rules and still customize the wiki.

But putting a README file in the LESS tree now for more clarity. And I'm moving the custom rules to their own file for cleaner linking that does not try to `import ../bootstrap.less`.

**Comment by cXhristian** [comment]
A problem I see with that method is when updating to newer Bootstrap versions that break backwards compatibility. 
Django-wiki is at the moment using Bootstrap 3 RC1 which uses some different class names than 3.2 (for example visible-* vs visible-*-(block|inline|inline-block). Things like that requires changes in the template files in django-wiki.

Including two bootstrap versions on the website is not ideal, but in my opinion that would lead to less issues when using different Bootstrap versions. As it is now we have Bootstrap RC1 and Bootstrap 3.2 running with only a few minor issues and a namespace would solve those. 

Using a single Bootstrap version might work now (I haven't tested it), but in the future it could easily break. And I'd rather not have to maintain my own CSS to make django-wiki work with new Bootstrap versions. We don't have any custom CSS for the wiki that I am aware of.

**Comment by benjaoming** [comment]
Yeah, that could be problematic, but as you say, your own simple solution about nesting it into .wiki solves the issue. So it's pretty easy to create your own extra `my_bootstrap.less` which would wrap `import "path/to/wiki-boostrap.less";` in the appropriate CSS class.

As I see it, the commit solves the issue of custom wiki styles being forced together with a specific bootstrap. Now it's possible to maintain another bootstrap tree and import only the wiki styles.

We'll just have to get better at updating the wiki's bootstrap versions.

**Comment by cXhristian** [comment]
Yeah, that's a decent solution. :)

Unless you're already working on it I can upgrade the Bootstrap version for django-wiki.

**Comment by benjaoming** [comment]
Please do :) I'm trying to get rid of the last issues before releasing this 0.0.24 :)

**Comment by benjaoming** [comment]
See #366
