### ISSUE TITLE
Wiki pages on multiple sites

### ISSUE THREAD

**Issue by mhozza** [django-wiki/django-wiki#370]
It would be nice to have an option to make page and it's subpages be visible on multiple sites. Or somehow add url paths for all sites at once.

In our setting we run several sites on single django instance. Most content is different but we have some parts, we want to be shared across all sites. But if someone creates sub article on such part, url path only for current site is created and therefore page is not visible in other sites.

One possible way to implement this is to have manytomany site field on urlpath model and inherit the value from parent when creating new article.

**Comment by benjaoming** [comment]
Another typical problem is posed by multi-lingual usage where it's nice to separate entire trees, but keeping track of relations between versions of the same article but in different languages.

#329 deals with this.

I'm not quite sure about what's a good solution to this. Keep in mind that tree lookups have to fast and efficient for searchability, permission lookups, browsing of tree structures etc. So having an ambiguous tree structure that goes "if the site ID is set, then the parent is X, and if its unset, then the parent is Y" makes it either hard to maintain or hard to make lookups.

**Comment by benjaoming** [comment]
So I'm closing this, but the cross-reference in the other open issue will keep it alive. Thanks for explaining your situation and use case, @mhozza
