### ISSUE TITLE
Add custom stylesheet to base_site.html without overriding it completely

### ISSUE THREAD

**Issue by BrendanBerkley** [django-wiki/django-wiki#371]
Is this possible as is? There are no extra header blocks to hook into, and I can't get to the sekizai render_block in my base.html override because it's not in a block of any kind.

**Comment by benjaoming** [comment]
It is possible. Use sekizai's `{% addtoblock %}` but remember that it has to go *inside* an existing `{% block ... %}` that's rendered.

**Comment by BrendanBerkley** [comment]
::facepalm::

Sorry to trouble you. Thanks for all the work you do!

**Comment by benjaoming** [comment]
No worries, but easier to ask on IRC ;)

Have a nice day!
