### ISSUE TITLE
Images don't show up (error 404)

### ISSUE THREAD

**Issue by megapctr** [django-wiki/django-wiki#377]
I'm using Django 1.6.10 and wiki 0.0.24.1.
After creating and configuring a wiki project, I've added an article with some images and they don't show up. Article and manage-images pages and Images sidebar menu all don't display the image. The image detail modal says `This image failed to load.`

Here's the console output:
```
[28/Jan/2015 11:52:31] "GET /wiki/foobar/ HTTP/1.1" 200 8054
( . . . )
[28/Jan/2015 12:01:28] "GET /wiki/foobar/cache/37/a4/37a4b37bc00c496dedc2d9013146b5a7.jpg HTTP/1.1" 301 0
[28/Jan/2015 11:52:31] "GET /wiki/foobar/cache/37/a4/37a4b37bc00c496dedc2d9013146b5a7.jpg/ HTTP/1.1" 404 4876
```

I've checked the docs and default wiki settings for any clues on how to solve this issue, but didn't find anythig.

EDIT: I forgot to mention, the wiki assumes the image path is an article.
EDIT2: The issue is present without the `^wiki/` url prefix too.

**Comment by benjaoming** [comment]
`wiki/foobar/` doesn't sound like a valid `MEDIA_URL` setting, are you sure this is the right place, and does it match your file system layout? Please refer to this doc:

https://docs.djangoproject.com/en/1.7/ref/settings/#media-url

**Comment by megapctr** [comment]
Thank you. The unconfigured MEDIA_URL was causing the issue.

**Comment by Forethinker** [comment]
Django 1.7.7 | wiki 0.1 | pillow 2.8.1 | Ubuntu LTS 14.04.02 

I have set `MEDIA_URL = '/media/'` and `STATIC_URL='/static/'` in `settings.py`
I still get 404 error:

    [04/Apr/2015 08:30:08] "GET /media/cache/35/74/35746f441fbf54b5a57869693ab0c653.jpg/ HTTP/1.1" 404 4851 
    [04/Apr/2015 08:30:08] "GET /media/cache/e7/ef/e7efc5e41aba2a8276e023d0f40e0388.jpg/ HTTP/1.1" 404 4851 

I've made sure that these files do exist and their permission are set properly:

    -rwxrwxrwx 1 john john 2.5K Apr  4 01:18 media/cache/e7/ef/e7efc5e41aba2a8276e023d0f40e0388.jpg*
    -rwxrwxrwx 1 john john 8.6K Apr  4 01:18 media/cache/35/74/35746f441fbf54b5a57869693ab0c653.jpg*



These lines are under TEMPLATE_CONTEXT_PROCESSORS

    "django.core.context_processors.media",
    "django.core.context_processors.request",
    "django.core.context_processors.static",


Tried the following two solutions suggested by others:
    from django.conf import settings

    # ... your normal urlpatterns here

    if settings.DEBUG:
        # static files (images, css, javascript, etc.)
        urlpatterns += patterns('',
            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT}))

and

    from django.conf import settings
    from django.conf.urls.static import static

    urlpatterns = patterns('',
        # ... the rest of your URLconf goes here ...
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

and still no luck. Do you guys have any ideas?
