### ISSUE TITLE
Help/Instructions upgrading from 0.0.23 to 0.0.24.1

### ISSUE THREAD

**Issue by orblivion** [django-wiki/django-wiki#381]
I'm trying the new 0.0.24.1 from pip, upgrading from 0.0.23 and I've come across the following issues (so far). It would be nice if there were an upgrade guide:

* Replacing django_notify with django_nyt. I did the simple replacement in settings.py and urls.py. The site was viewable after this, though I haven't been able to test notifications yet.
* Try editing an article, error, django_nyt tables don't exist. No matter I run migrations. Here's what I get:

`Error in migration: wiki:0001_initial .... django.db.utils.ProgrammingError: relation "wiki_article" already exists`

Looking into the package directory, I see both migrations and south_migrations, both of which have migrations 0001-0013. Looking at github, 23 has migrations and 24 has south_migrations. It seems that the pip upgrade process just dumps new things in assuming everything will be okay.

But, I try installing with a new virtualenv. Interestingly, it doesn't complain this time about django_nyt when I edit an article, perhaps because that part of it migrated successfully before it hit he migration error. But, no notification pops up. However when I try migrating just for the heck of it, I get the same error above.

This is what I have so far, but perhaps there's more that will come up when I fix it.

Thanks.

**Comment by orblivion** [comment]
```
select * from south_migrationhistory;
 id |     app_name      |                   migration                   |            applied            
----+-------------------+-----------------------------------------------+-------------------------------
  1 | django_notify     | 0001_initial                                  | 2014-11-26 14:20:40.242108-08
  2 | django_notify     | 0002_auto__add_field_notification_occurrences | 2014-11-26 14:20:41.461625-08
  3 | django_notify     | 0003_auto__add_field_subscription_latest      | 2014-11-26 14:20:41.836656-08
  4 | django_notify     | 0004_auto__chg_field_notification_url         | 2014-11-26 14:20:42.97547-08
  5 | django_nyt        | 0001_initial                                  | 2015-02-03 05:30:57.379441-08
  6 | django_nyt        | 0002_auto__add_field_notification_user        | 2015-02-03 05:30:57.400174-08
  7 | django_extensions | 0001_empty                                    | 2015-02-03 05:56:33.544625-08
(7 rows)
```

That's kindof interesting. If I run migrations on 23, there's no error and the site works. Is it defaulting to syncdb for 23 for some reason?

**Comment by benjaoming** [comment]
Thanks for bringing up this annoying lack of instructions in the docs. I've tried fixing them with c2816c4fb116cdec1397021e8188d5927e4728dc and 6daab127584d6e4a6bbd10e49cf11430cfea37b0

Let me know if you find this sufficient.

> Looking at github, 23 has migrations and 24 has south_migrations. It seems that the pip upgrade process just dumps new things in assuming everything will be okay.

If you run South 1.0.1+, there should be a builtin feature to use south_migrations instead of just "migrations" module when available. This is to avoid conflits with django.db.migrations.

**Comment by orblivion** [comment]
I followed the instructions as listed, I still get the same error. (though in full disclosure, I just imported a database from Heroku which seemed to be giving me some funny business. but since it's the same error I'm guessing Heroku's db isn't causing it).

I renamed the "migrations" directory to "not_migrations" and it still does it. I think it's something else. 

Running "migrate --list" I think I see the problem, somehow I didn't try that before. wiki has a bunch of migrations which have not run. I try it on 23, and wiki doesn't even have migrations. So, it seems that part of the process requires faking to a certain version.

**Comment by orblivion** [comment]
So basically, when I switch from 23 to 24, I think I need to run:

`./manage.py migrate wiki --fake <some_version>`

Which version is that? (And then, probably put it in the upgrade instructions as well, assuming this isn't somehow due to a mistake I made).

**Comment by benjaoming** [comment]
Your problem might be that you installed the DB without South and then tried to run the migrations after, in which case they will fail because everything is already "installed". Would that be the cause?

**Comment by orblivion** [comment]
Do you mean that I installed wiki 23 before installing south? Meaning, I created the models with syncdb when I should have used south? Otherwise, I'm not sure what you mean by "install the DB". I was running wiki 23, and I had been using south for my project in general. But in version 23, wiki app didn't have any migrations listed for it:

```
> ./manage.py migrate wiki --list
/..../local/lib/python2.7/site-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

The app 'wiki' does not appear to use migrations.
./manage.py migrate [appname] [migrationname|zero] [--all] [--list] [--skip] [--merge] [--no-initial-data] [--fake] [--db-dry-run] [--database=dbalias]
```

**Comment by benjaoming** [comment]
Yes "installed the DB without South" = "not having `south` in `INSTALLED_APPS` and running `syncdb`" :)

Which version of south have you been using? If you use 1.0 or older, it won't automatically find `wiki.south_migrations` but instead think that `wiki` doesn't have migrations and then just let it install the database normally with `syncdb`, hence same behaviour.

But would you think this is an issue that you can reliably recreate and that it should be fixed? Because I really just wanna release 0.1 as soon as possible...

**Comment by orblivion** [comment]
> If you use 1.0 or older, it won't automatically find wiki.south_migrations

But this is version 23 where I don't see the wiki migrations; version 23 has `migrations`, not `south_migrations`, so the version of south shouldn't matter. If I upgrade to 24, I do see the migrations, and that's where the problem starts. Maybe the problem is that I didn't have south at all? If not, it seems like this is more of a bug in 23 than 24; any changes to the upgrade guide would just be to compensate for that.

That said, to answer your question directly:

```
In [1]: import south, wiki                               

In [2]: south.__version__, wiki.VERSION                                   
Out[2]: ('1.0.2', '0.0.23')
```

> But would you think this is an issue that you can reliably recreate and that it should be fixed? Because I really just wanna release 0.1 as soon as possible...

I'll see if I can come up with repro steps. It's likely enough my own fault, but if not I certainly would want you to move on.

As far as my own project, looking more closely now, you didn't add any migrations between 23 and and 24, so I can just --fake all of them and move on. But I would like to figure out what went wrong in case it's a bug.

**Comment by orblivion** [comment]
Okay, I just tried it from scratch and it does not reproduce. I must have installed wiki before south. Thanks!

**Comment by orblivion** [comment]
(Though it's strange that south doesn't pick up on this...)

**Comment by benjaoming** [comment]
Sorry, I didn't fully consider what you wrote.. you're right, if you did run migrations on .23 then .24 shouldn't complain about migrations no matter the south version.

Glad that you can't reproduce it ;) But if you do happen to be able to create a flawed migration history that's incompatible with .24, do say.

Thanks for attending to it.... I will now attend to releasing the 0.1 version, it's really extremely overdue and not very "release often" kind of approach I wish django-wiki could do :)

**Comment by orblivion** [comment]
That's good, because close by on my agenda is upgrading to Django 1.7 :)
