### ISSUE TITLE
How add extra field to Article?

### ISSUE THREAD

**Issue by Infernion** [django-wiki/django-wiki#385]
Hi guys!
First I want to say my appreciation for your work! Thank you!

I need add extra tag field for Article Model. Can you tell me how i can implement this feature?

**Comment by tkliuxing** [comment]
If you want use tag system, may add this app in your INSTALLED_APPS : [django-universaltag](https://github.com/tkliuxing/django-universaltag), or another django tags application, just search `django tags` at [pypi](https://pypi.python.org/pypi?%3Aaction=search&term=django+tags&submit=search)

Forgive me in broken English ;-)

**Comment by benjaoming** [comment]
Yes,as @tkliuxing says, you need to use another model, since "adding a field" would really mean to copy the whole source code to make a one line change :)

**Comment by Infernion** [comment]
Thank you guys! 
I'll try use django tag app :)

**Comment by bbcreatv** [comment]
Hi, If using another model, should it be as a plugin? Would it be as one to one? Really want to figure this out as well.

**Comment by benjaoming** [comment]
@bbcreatv the question you ask indicates that maybe it's better to start off with some Django basics. There's nothing unusual about django-wiki's model structure, so you would create your own model, possibly inheriting from Article or with a OneToOneField. This implementation detail is entirely up to you and what suits your project the best.

**Comment by bbcreatv** [comment]
@benjaoming maybe you should not be so judgmental? I have a modified version of the image plugin. If you can point me in the right directio that would great, if not I'll figure it out I'm sure. Thank you.

Here is my code:
wiki_plugins.py

` class TagPlugin(BasePlugin):

    slug = settings.SLUG
    sidebar = {
        'headline': _('Tags'),
        'icon_class': 'fa-picture-o',
        'template': 'sidebar.html',
        'form_class': forms.SidebarForm,
        'get_form_kwargs': (lambda a: {'instance': models.Tag(article=a)})
    }

    # List of notifications`

models.py

`   @python_2_unicode_compatible
    class Tag(RevisionPlugin):

    def can_write(self, user):
        if not settings.ANONYMOUS and (not user or user.is_anonymous()):
            return False
        return RevisionPlugin.can_write(self, user)

    def can_delete(self, user):
        return self.can_write(user)

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')
        db_table = 'wiki__plugins_tags_tag'  # Matches label of upcoming 0.1 release
        if settings.APP_LABEL:
            app_label = settings.APP_LABEL

    def __str__(self):
        if self.current_revision:
            return ugettext('Tag: %s') % self.current_revision.tagrevision
        else:
            return ugettext('Current revision not set!!')


@python_2_unicode_compatible
class TagRevision(RevisionPluginRevision):

    tags = TaggableManager()



    def inherit_predecessor(self, tag, skip_image_file=False):
        """
        Inherit certain properties from predecessor because it's very
        convenient. Remember to always call this method before
        setting properties :)"""
        predecessor = tag.current_revision.imagerevision
        self.plugin = predecessor.plugin
        self.deleted = predecessor.deleted
        self.locked = predecessor.locked
        self.tag = predecessor.tag
        if not skip_image_file:
            try:
                self.tags = predecessor.tags

            except IOError:
                self.tags = None

    class Meta:
        verbose_name = _('tag revision')
        verbose_name_plural = _('tag revisions')
        # Matches label of upcoming 0.1 release
        db_table = 'wiki_plugins_tags_tagrevision'
        if settings.APP_LABEL:
            app_label = settings.APP_LABEL
        ordering = ('-created',)

    def __str__(self):
        return ugettext('Tag Revsion: %d') % self.revision_number
`

forms.py
from wiki_plugins_tags import models


    class SidebarForm(PluginSidebarFormMixin):
        def __init__(self, article, request, *args, **kwargs):
            self.article = article
            self.request = request

            super(SidebarForm, self).__init__(*args, **kwargs)
            self.fields['tags'].required = True

        def save(self, *args, **kwargs):
            SidebarForm.save_m2m()
            if not self.instance.id:
                tagged = models.Tag()
                tagged.article = self.article
                kwargs['commit'] = False
                revision = super(SidebarForm, self).save(*args, **kwargs).save_m2m()
                revision.set_from_request(self.request)
                tagged.add_revision(self.instance, save=True)

                return revision

            return super(SidebarForm, self).save(*args, **kwargs)

        class Meta:
            model = models.TagRevision
            fields = ('tags',)


    class RevisionForm(forms.ModelForm):
        def __init__(self, *args, **kwargs):
            self.tags = kwargs.pop('tags')
            self.request = kwargs.pop('request')
            super(RevisionForm, self).__init__(*args, **kwargs)
            self.fields['tags'].required = True

        def save(self, *args, **kwargs):
            if not self.instance.id:
                kwargs['commit'] = False
                revision = super(RevisionForm, self).save(*args, **kwargs)
                revision.inherit_predecessor(self.tags, skip_image_file=True)
                revision.deleted = False  # Restore automatically if deleted
                revision.set_from_request(self.request)
                self.tags.add_revision(self.instance, save=True)
                return revision
            return super(RevisionForm, self).save(*args, **kwargs).save_m2m()

        class Meta:
            model = models.TagRevision
            fields = ('tags',)

**Comment by benjaoming** [comment]
I think it's better if you open up this question on StackOverflow, since your inquiry is way more suitable for a community dedicated to help people out with support issues and reuse the information generated from previous answers. Github simply isn't built for this.

> I am using django-taggit but cant save the tags with .save_m2m()

Remember when you ask for support that it's hard to understand a question like that without a Traceback.

Sorry that you got the impression that I'm judgemental. But let's not get into some kind of bad vibe, please understand that you are asking support favours in a closed Github issue.

Good luck getting it solved and great you're using the software!

**Comment by bbcreatv** [comment]
Okay, I think what you said is fair to say. No bad vibes :) Sometimes in desperation or pressure you make these posts and forget that its a support issue as well. 

Thanks for taking the time out to reply and I appreciate that you get all sorts of posts etc. I will make a post on stackoverflow and hopefully figure it out.

Thanks for the software. It really is great, and the more I learn about it the more I realise this.

**Comment by benjaoming** [comment]
Please feel free to use this tag, perhaps we can build something :)

http://stackoverflow.com/questions/tagged/django-wiki

**Comment by bbcreatv** [comment]
Done :) Lets see what happens [http://stackoverflow.com/questions/35364644/building-tags-plugin-for-django-wiki-using-django-taggit-cannot-save-with-save](stackoverflow)
