### ISSUE TITLE
Ability to override branding in page title (<title> tag)

### ISSUE THREAD

**Issue by azaghal** [django-wiki/django-wiki#387]
Currently it is not possible to easily override the branding inside of the <title> tag (found in base_site.html).

It would be useful to be able to easily replace the default value ` - django-\/\/  i K |` with a custom one. The ` - ` should probably be enclosed with a block in order to allow people to completely remove wiki name if they wish to.

**Comment by benjaoming** [comment]
This has been fixed as per above commit.
