### ISSUE TITLE
Allow hyphens in wiki slug

### ISSUE THREAD

**Issue by cXhristian** [django-wiki/django-wiki#391]
What's the reason for replacing hyphens with underscores?
I agree that spaces should be replaced with underscores as spaces in urls simply look bad. 
Hyphens on the other hand look fine and serve a different purpose than underscores. E.g. Wikipedia uses underscores for spaces and leave all hyphens as they are.

**Comment by mrmikee** [comment]
Need hyphens as part of slug.  

For example we use other WIKI's for building pages for servers.  The pages have a url like `http://wiki.domain.com/hosts/datacenter-server-001`.  This gives us the ability to reference the page via a dynamically generated NOTES URL in our server monitoring app Nagios.

Without the ability to use hyphens in the slug, this functionality is broken for django-wiki for us and is a roadblock that prevents us from migrating to django-wiki.

**Comment by benjaoming** [comment]
Awesome! Thanks @cXhristian hope it does what people intend for this, it's been a bit confusing how to auto-create these slugs.
