### ISSUE TITLE
Markdown extension HeaderId is likely to cause issues

### ISSUE THREAD

**Issue by cXhristian** [django-wiki/django-wiki#393]
HeaderId basically takes the header(h1, h2, etc) and uses the slug for it as id attribute. 

With generic titles this is likely to cause issues with custom css on the website. For example we had some extra padding on `<section id="wiki">` to adjust the menu (removed now). 
But we also had a markdown header `Wiki` which of course generated the markup `<h1 id="wiki">Wiki</h1>`. I think you can see the problem. 

A possible fix would be to prefix all HeaderId attributes with something like wiki_.

**Comment by tkliuxing** [comment]
BTW, HeaderId extension have not support unicode string e.g. simplified chinese.

This source:
```markdown
##  岔道 ##

## 信号灯 ##
```
will output:
```html
<h2 id="_1">岔道</h2>
<h2 id="_2">信号灯</h2>
```
My solution is to use attr_list extension:
```markdown
##  岔道 {: #岔道}

## 信号灯 {: #信号灯}
```
will output:
```html
<h2 id="岔道">岔道</h2>
<h2 id="信号灯">信号灯</h2>
```
