### ISSUE TITLE
Possible to add HTML

### ISSUE THREAD

**Issue by bbcreatv** [django-wiki/django-wiki#398]
Is it possible to add HTML. For example I was to add a div as a container for paragraph. I have tried many different syntax but I keep getting [HTML REMOVED]

**Comment by mhozza** [comment]
Put this in your settings file:
```
WIKI_MARKDOWN_KWARGS = {
    'safe_mode': False,
}
```

**Comment by benjaoming** [comment]
@bbcreatv please do not ask support questions on the Issue tracker.

Mailing list and IRC details are in the readme.

Thanks :)

**Comment by bbcreatv** [comment]
My apologies. Thanks @mhozza. That worked perfectly :)
