### ISSUE TITLE
Django 1.7 migrations are incomplete, fail after makemigrations

### ISSUE THREAD

**Issue by hwkns** [django-wiki/django-wiki#399]
My project uses Django 1.7.5 and Python 3.4.  I installed `django-wiki` from the current `master` branch, added the necessary settings, and ran `manage.py migrate`, and everything worked.  But my project's model definitions are in constant flux right now, so I re-create my initial migrations fairly often.  The most recent time I did this, it generated a second migration for `django-wiki`:

```
$ manage.py makemigrations
Migrations for 'wiki':
  0002_auto_20150308_0558.py:
    - Remove field article from articleplugin
    - Remove field articleplugin_ptr from reusableplugin
    - Remove field articles from reusableplugin
    - Delete model ReusablePlugin
    - Remove field articleplugin_ptr from revisionplugin
    - Remove field current_revision from revisionplugin
    - Remove field plugin from revisionpluginrevision
    - Delete model RevisionPlugin
    - Remove field previous_revision from revisionpluginrevision
    - Remove field user from revisionpluginrevision
    - Delete model RevisionPluginRevision
    - Remove field article_revision from simpleplugin
    - Remove field articleplugin_ptr from simpleplugin
    - Delete model ArticlePlugin
    - Delete model SimplePlugin
```

And this migration failed to run, with the following error:
```
Running migrations:
  Applying wiki.0002_auto_20150308_0558...Traceback (most recent call last):

...

django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'wiki.SimplePlugin'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more
```

Are those models really intended to be concrete?  Or should they be abstract mixins instead?

**Comment by benjaoming** [comment]
I haven't seen the error before. It suggests that an app label or something in the model's path has changed, because all those fields etc. are still there, just look in the models...

> Are those models really intended to be concrete?

Yes, this is to ensure that plugin data can be accessed without regards to any specific model types.

**Comment by hwkns** [comment]
@benjaoming you're right, and after some more digging I've found the problem:

https://github.com/django-wiki/django-wiki/blob/master/wiki/models/__init__.py#L12-L13

If I add `from .pluginbase import *` here, then `manage.py makemigrations wiki` says no changes were detected, and everything still works properly.

**Comment by benjaoming** [comment]
So Django has changed the way models are resolved, before it was enough to import in the inheriting class' module. Thanks for fixing this!!
