### ISSUE TITLE
TOC extension cause plugins.macros not to load

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#406]
```
12:03:15 PM - iver: [11:21:51] hi. is there any special configuration for getting the macros plugin to work? apart from listing it in installed_apps?
12:03:15 PM - iver: [11:23:21] images, links and help show up in the sidebar but macros does not. [TOC] does not do anything. i get no errors...
12:03:15 PM - iver: [11:48:04] importerror on itertext from markdown.extensions.headerid in the toc extension
12:03:15 PM - iver: [11:48:41] manually removing the loading of the toc extension in the plugin lets me use article_list, at least
```

**Comment by adw0rd** [comment]
Hi @benjaoming, I not understand how to use TOC? The documentation I have not found an answer how to use it... 

I copied from http://demo.django-wiki.org/_source/ 

    # Markdown: Syntax
    
    [TOC]

but not work. What am i doing wrong?

**Comment by benjaoming** [comment]
I don't know :) But using django-wiki from source and debugging the source
might give the answer?

**Comment by adw0rd** [comment]
@benjaoming I must install something plugin or something else for using TOC? Or it must work by default?

**Comment by benjaoming** [comment]
@adw0rd It's part of the 'macros' plugin.

**Comment by adw0rd** [comment]
@benjaoming yes, TOC work only for the 0.1dev, but not work for the 0.0.24.2. Thanks!

**Comment by benjaoming** [comment]
@adw0rd no 0.0.24.2 works for older versions of python-markdown as well, just downgrade that package and you'll be fine.
