### ISSUE TITLE
Installing new version 0.0.24.2

### ISSUE THREAD

**Issue by alsanuz** [django-wiki/django-wiki#409]
Hi, I have a problem, when I try install the last version of wiki (0.0.24.2) with "pip". 

Upposedly this version supports Django 1.7 but it's uninstalled my version of Django (1.7.7) and reinstall Django with old version 1.6.11.

**Comment by benjaoming** [comment]
Hi @alsanuz 

Thanks for the report. 0.24.2 does not fully support Django 1.7 but it actually works fine according to my own experience.

You can either

1. Try out 0.24.2 with Django 1.7 and hope there's no issues
1. Run from the dev version by installing it with git `pip install git+https://git@github.com/django-wiki/django-wiki.git` -- and please do help out to get Django 1.7 support working
1. Wait for 0.1 to be released

Please refer to the release notes for an overview...

http://django-wiki.readthedocs.org/en/latest/release_notes.html
