### ISSUE TITLE
Git app gets along with django-wiki

### ISSUE THREAD

**Issue by programacion-web** [django-wiki/django-wiki#411]
Hi folks, thanks for development

I have an installation of django wiki (works great), I want to add it to the wiki a git manager and track system.

The wiki is very nice, I would like to do something basic like github with django, it is only for 5 friends.

Any ideas or an app that gets along with django-wiki or experiences.

thanks

**Comment by benjaoming** [comment]
Can you clarify a bit more, what you need to do, and if it's a loose discussion, maybe you wanna bring it to the IRC or mailing list?

It sounds like you wanna make a django project, install some different apps and make a menu in your HTML templates where there's a 'wiki' button? But maybe it's worth trying to get to grips with django and its basics? Sorry if I'm off target here.

Closing as it's not an issue with django-wiki.

Thanks :)

**Comment by programacion-web** [comment]
Now I have django-wiki and it works great

but I want to see if convina well with any style gitlab browser or git github but for django or supplement django-wiki

or from django-wiki how do call my githubs existing?

thanks
