### ISSUE TITLE
Plugin: DIsqus comment

### ISSUE THREAD

**Issue by tkliuxing** [django-wiki/django-wiki#413]
This Plugin only add a javascript to base.html template.
It's achieved in each page can comment.
Has been achieved in this site: http://wiki.oyhy.me

![p8oaf6lwqnxegaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/652939/7336914/ea2883d8-ec45-11e4-8e7e-cc2da2a8c433.png)

**Comment by benjaoming** [comment]
@tkliuxing looks nice, it's a matter of customizing your local project templates, right?

Btw. congrats on being the first 100% translated language :)

**Comment by benjaoming** [comment]
Okay, so this approach will likely be described as a section in the docs on how you can use a template override to add your own Disqus comment block to all your articles.
