### ISSUE TITLE
Log access

### ISSUE THREAD

**Issue by bvanalderweireldt** [django-wiki/django-wiki#414]
Hi,

How would you implement a custom system to log every access on the blog ?

using the Django logging library ?

Benoit

**Comment by benjaoming** [comment]
Hi @bvanalderweireldt 

You mean "wiki", right?

How do you want to log things, and what are you going to use the log for? Analytics?

Every article has a history already for editing purposes.

I don't know what you mean by "the Django logging library".

**Comment by bvanalderweireldt** [comment]
I mean logging every article read access history (user, link, date and ip)

By Django logging I mean the default logger.

**Comment by benjaoming** [comment]
You could write your own template tag that takes the request and article objects as an argument. Unless you use some kind of caching, your template tag would be evaluated on every render. Then you can decide if it should be evaluated in wiki/article.html or wiki/base_site.html.. just do a template override.

That, or just use Piwik og Google Anal.
