### ISSUE TITLE
How i can connect external plugin

### ISSUE THREAD

**Issue by Infernion** [django-wiki/django-wiki#415]
Hi, me just wondering how i can connect external plugin that i wrote. When I add to wiki.plugin directory it's working like a charm, but when I try to connect from my django project I got no success :(

What is a right way to connect external plugin?

Thanks

**Comment by benjaoming** [comment]
Sorry it might seem legit since many people are using the issue tracker for asking questions.. but that's not what it's for :) Please use the IRC or the mailing list for this.

Thank you :)

**Comment by Infernion** [comment]
Sorry, in future I'll ask questions in another place :)
