### ISSUE TITLE
In 0.0.24.2, slug recommendation is still capitalized, but validation requries lower case

### ISSUE THREAD

**Issue by orblivion** [django-wiki/django-wiki#417]
This seems like an easy to spot bug, but I couldn't find it in the issues. Apologies if it's a repeat.

When creating a new article, I type in a title. It recommends a slug with the words from the title capitalized. ("Hello world!" -> "HelloWorld"). But then when I submit, I get a popup, "Please match the requested format: Lowercase letters, numbers, and underscores." Hopefully that verbatim, maybe there's a newline in there. I couldn't easily copy it.

**Comment by benjaoming** [comment]
Cannot reproduce, have you run "collectstatic" ?

**Comment by orblivion** [comment]
Wow, I forgot about that. *However* now that I have, it still happens, unfortunately. Reproducing a project from scratch, it does not happen. ¯\_(ツ)_/¯
