### ISSUE TITLE
No manage.py

### ISSUE THREAD

**Issue by maketoh** [django-wiki/django-wiki#423]
I am trying to install and run django-wiki.
I am following http://django-wiki.readthedocs.org/en/latest/installation.html
I am in my `/usr/lib/python2.7/site-packages/wiki`
I added to INSTALLED_APPS.
Now there is no manage.py to run the next step. How is it supposed to be?
Without manage.py how can in do manage.py runserver.
I am new to django and django-wiki.
Appreciate all help. I asked in IRC but no help. thanks

**Comment by benjaoming** [comment]
Please do not use Github for support. Thanks for your understanding.

https://github.com/django-wiki/django-wiki/blob/master/CONTRIBUTING.md

**Comment by benjaoming** [comment]
If you want answers on IRC, don't log off ;)

**Comment by maketoh** [comment]
sorry. I wasn't aware.
