### ISSUE TITLE
Keep getting logged out

### ISSUE THREAD

**Issue by bbcreatv** [django-wiki/django-wiki#434]
Using Django-CMS and django-wiki everytime I leave the wiki and view my main site I keep getting logged out of the wiki. These are 2 complete seperate installations. I'm presuming that maybe its a cookie thing?

**Comment by benjaoming** [comment]
Doesn't sound like a problem with django-wiki, since all this stuff is handled with django.contrib.auth and django.contrib.sessions

Check how you store sessions, your auth cookie etc. And yes, auth sessions are stored in a cookie, but that cookie has to match a session id in your session backend.

**Comment by bbcreatv** [comment]
Thanks @benjaoming, that fixed it. I changed the SESSION_COOKIE_NAME
