### ISSUE TITLE
Related articles or linked articles

### ISSUE THREAD

**Issue by bbcreatv** [django-wiki/django-wiki#435]
Apologies if this has already been covered but I cant seem to find any info. Is it possible to get a dynamic list of linked or related articles for an article in a separate TOC. Would I have to created another TOC macro? Basically I want to have 2 sidebars. One with basic internal article links - like on the current wiki demo and one with any links or related articles. Thanks.

**Comment by benjaoming** [comment]
This is not a bug, and not a feature request... it's a support request.

When you click New Issue, there's this:

![screenshot from 2015-06-23 13 11 12](https://cloud.githubusercontent.com/assets/374612/8304772/5a6ad098-19a9-11e5-908b-540b530c8e33.png)

Please read it.
