### ISSUE TITLE
TOC and Main Content

### ISSUE THREAD

**Issue by bbcreatv** [django-wiki/django-wiki#436]
Why is the table of contents not seperated from the main content? It makes it very difficult to do a simple Left/Right layout. For example if I add a class to the TOC like large-4-columns I have to enable HTML in the Wiki to add a class to the main content..

I think this is ok to ask here, as its a legitimate development issue.

**Comment by benjaoming** [comment]
If you want, you can always create your own template, extending existing templates and add your own TOC outside of the main contents.

http://django-wiki.readthedocs.org/en/latest/customization.html#templates

**Comment by bbcreatv** [comment]
Thanks for the quick reply Benjamin. Really don't want to waste your time but can the TOC for each article only be gotten through markdown. 
Kind of lost on what way to go to try and make this work.
If you'd like me to transfer this to the group or IRC that's no problem.

**Comment by benjaoming** [comment]
The markdown in case parses the article's contents and builds a new element. You can do the same... or you can write a work-around JavaScript code that just moves the element in the DOM to another location.. `$('#toc').parent($('#new_parent'))` or something like that (pseudo JS).

**Comment by bbcreatv** [comment]
Ah of course! For some reason I thought it was populated differently, That worked perfectly. Can't believe it was that simple...Thanks for your help :+1:
