### ISSUE TITLE
Replace attachment should not delete older revisions unless "Remove Previous" is checked

### ISSUE THREAD

**Issue by thomastu** [django-wiki/django-wiki#441]
Currently in ```wiki/plugins/attachments/views.py```, line 189 - 195 will delete older revisions if self.can_moderate is true.  

(snippet for convenience)
```
        if self.can_moderate:
            older_revisions = self.attachment.attachmentrevision_set.exclude(
                id=attachment_revision.id,
                created__lte=attachment_revision.created,
            )
            # Because of signalling, the files are automatically removed...
            older_revisions.delete()
```

I propose the following solution/change in behaviour:
If replace is checked, we replace ONLY the oldest revision.
If replace is not checked, we just add the new upload to the file history.  

i.e. :  
```
        if self.can_moderate:
            oldest_revision = self.attachment.attachmentrevision_set.exclude(
                id=attachment_revision.id,
                created__lte=attachment_revision.created,
            ).latest()
            # Because of signalling, the files are automatically removed...
            if form.cleaned_data['replace']:
                oldest_revision.delete()

```

**Comment by thomastu** [comment]
I guess there's also some ambiguity as to whether or not anyone should be able to replace the attachment or only users who can moderate.

**Comment by benjaoming** [comment]
Agreed -- on first-take I would say that only moderators can change
revision history, because it's kept such that we can guard the wiki against
untrusted changes. So the form widget should only show when can_moderate is
True.

**Comment by benjaoming** [comment]
Oh great, this seems fixed a long time ago :)
