### ISSUE TITLE
How do I change the default permission for new users...

### ISSUE THREAD

**Issue by audioburn** [django-wiki/django-wiki#443]
...So that new users have to be approved to edit and create articles, but by default are not allowed?

I already tried adding WIKI_CAN_WRITE = False in my settings.py (for my app) to no avail. 

This is not defined in the docs or anywhere else, and IRC brought nothing so asking here.

Please and thank you, the app is amazing so far besides this issue.

**Comment by benjaoming** [comment]
Dear audioburn

Thanks for the kind words. For IRC, you need to stick around long enough for the few active people to see your message. There's also a mailing list that you can write.

Github issues are for errors and feature requests, it easily becomes to hard to maintain this project when people ask for support on Github.

When you click New Issue, there's this which explains more in detail that you shouldn't ask here:

![screenshot from 2015-06-23 13 11 12](https://cloud.githubusercontent.com/assets/374612/8722633/f71cfd56-2bc6-11e5-8d87-8be82be82df5.png)
