### ISSUE TITLE
Introduce upper bounds for dependencies

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#444]
Markdown is currently just required to be >2.2.0, however installing django wiki 0.1 in a distant future would not work if there isn't an upper bound on the version.

From experiences if installing old versions of django-cms, I'd say that we need to be clear about these upper bounds, otherwise the release breaks in 2 years, and somewant might need it.

**Comment by thomastu** [comment]
There seems to be an [upperbound for python 2.7](https://github.com/django-wiki/django-wiki/blob/master/setup.py#L68) but not python >2.7?  Could we just use the same upperbound for all python versions?

**Comment by benjaoming** [comment]
That upper bound is more restrictive than necessary, would be nice to keep things loose, django-mptt has been the most likely dependency so far to break things.
