### ISSUE TITLE
Ordered list doesn't render properly

### ISSUE THREAD

**Issue by davidthewatson** [django-wiki/django-wiki#445]
I am running django-wiki on Mac OS X 10.10.4 with a django 1.8 project and PostgreSQL database. 

Here's what pip reports from my virtualenv:

    -e git://github.com/django-wiki/django-wiki.git@23705786796424a3b36be77c1e78d7316f89bb00#egg=wiki-master

I can display an ordered list fine with:

    1. Dog
    1. Cat
    1. Mouse

That is:

0. Dog
0. Cat
0. Mouse

However, if the ordered list is preceded by an unordered list:

    - Dog
    - Cat
    - Mouse
    
    1. Dog
    1. Cat
    1. Mouse

Then the ordered list is rendered as an unordered list:
 
 - Dog
 - Cat
 - Mouse

 - Dog
 - Cat
 - Mouse

**Comment by benjaoming** [comment]
Wow, didn't know this could happen. You've found an error in the Markdown library for Python.

```
➜  ~  cat | markdown_py
Does it work?

 - Dog
 - Cat
 - Mouse

 1. Dog
 1. Cat
 1. Mouse


<p>Does it work?</p>
<ul>
<li>Dog</li>
<li>Cat</li>
<li>
<p>Mouse</p>
</li>
<li>
<p>Dog</p>
</li>
<li>Cat</li>
<li>Mouse</li>
</ul>%                   
```

**Comment by benjaoming** [comment]
Closing and cheering on the Markdown devs. If you like, you could go and help them out @davidthewatson - and thanks for reporting!

**Comment by benjaoming** [comment]
Okay we're referred to the markdown.extensions.sane_lists extension, I'll add that as a default extension.
