### ISSUE TITLE
Saving an article without title returns error

### ISSUE THREAD

**Issue by Gheoan** [django-wiki/django-wiki#466]
* Django 1.8.4
* Python 3.4.3
* Windows 10
* How to reproduce: 
 1. Go to an already created article.
 2. Click Edit.
 3. Clear the title field
 4. Save
* Using django-wiki from master branch

**Comment by benjaoming** [comment]
```

  File "./wiki/forms.py", line 198, in clean
    if cd['title'] == self.initial_revision.title and cd[
```
