### ISSUE TITLE
I don't get the joke: Why is the module named just "wiki"?

### ISSUE THREAD

**Issue by guettli** [django-wiki/django-wiki#480]
Quoting README

> Why is the module named just "wiki"? Because "pip install wiki" returns "No distributions at all found for wiki"! :)

I don't get the joke.

**Comment by benjaoming** [comment]
There were not deistributions with that name, so we had to take it -- if you want, feel welcome in the IRC channel!

**Comment by guettli** [comment]
... do you mean

>  Because "pip install wiki" return**ed** "No distributions at all found for wiki"

then I get it.

**Comment by benjaoming** [comment]
You seem to be quite competent at spotting mistakes, please feel encouraged to write PRs rather than issues :)
