### ISSUE TITLE
Support {{{ block }}}

### ISSUE THREAD

**Issue by guettli** [django-wiki/django-wiki#481]
I prefer three curly braces to indentation.

For me it easier to type and easier to read.

Especially I see immediately where the end of the block is.

I guess most non geek people understand it immediately at first sight.

What do you think?

Do you want to support this?

If yes (would be great), how to implement it?

**Comment by benjaoming** [comment]
I don't like stuff that expands the language of Markdown into undocumented and unconventional territory. I guess you have this idea from StackOverflow?

We could also use ``` because it would align with the intention to have GFM.

See also #134

**Comment by guettli** [comment]
This ``` already works. At least in current django-wiki master.
Did you know that?

**Comment by benjaoming** [comment]
Well then everything is fine I guess!? :)

**Comment by guettli** [comment]
yes, all is fine. I close this.
