### ISSUE TITLE
Not logged in users see "new article below {root-site-name}"

### ISSUE THREAD

**Issue by guettli** [django-wiki/django-wiki#483]
At the moment not logged in users see "new article below {root-site-name}".

Is this a bug or a feature?

**Comment by benjaoming** [comment]
I have no idea what you mean, can you explain this in detail?

**Comment by guettli** [comment]
![django-wiki-create-article-although-not-logged-in](https://cloud.githubusercontent.com/assets/414336/10800540/9a0ce926-7db2-11e5-9b62-41d6661c45ff.png)

I creaed a screen shot.

Since the "edit" button is not visible, if you are not logged in, it would be symetric to not show "new article below {root-site-name}"

**Comment by benjaoming** [comment]
Ah, okay do you mean that by mistake there is a link to create a new article for users who shouldn't have access to do so?

**Comment by guettli** [comment]
Yes, that's what I mean. In my case (screen shot) the user was not logged in at all. The edit-button is not visible. I think the "new article below ..." should not be visible. I just wanted to tell you. It is not very important for me.

**Comment by benjaoming** [comment]
What happens if you click it?

**Comment by guettli** [comment]
You get redirected to the login page.

**Comment by benjaoming** [comment]
That seems cool, then the flow is nice and easy:

1. You're not logged in and click the button to create an article
1. You're asked to login
1. You get redirected to the article creation page.

No problems here :)

**Comment by guettli** [comment]
Why does this flow not apply to the "edit" button? It gets hidden if you are not logged in. I don't understand it.

**Comment by benjaoming** [comment]
Ah yes, good point... I guess that's because it gets replaced by a "View Source" button, kind of inspired by Mediawiki. Anything you'd like to see changed?

**Comment by guettli** [comment]
Yes, I would like to see the change of the status of this issue. Currently it is closed. Since you say "good point" I think it should be re-opened. But since I won't fix this issue it is up to you or an other developer to decide.

**Comment by benjaoming** [comment]
I'd say it's a non-issue since there are arguments for and against.. and more important matters to prioritize.
