### ISSUE TITLE
Creating links between pages (Link wizard)

### ISSUE THREAD

**Issue by guettli** [django-wiki/django-wiki#484]
django-wiki seems to support links between pages with [[..]].

At work we use dokuwiki. It has a nice way to create links. A pop-up opens and you can
enter a search term. Then a list of the matching pages gets displayed. You just need to click on a row and the corresponding link gets created.

Do you understand what I mean?

Here is an page describing the pop up better: http://www.inmotionhosting.com/support/edu/dokuwiki/writing-content-dokuwiki/internal-external-links-doku

Something like this would be handy.

Is there already a plugin which provides a link wizard?

**Comment by benjaoming** [comment]
Yes

![screenshot from 2015-10-28 13 33 54](https://cloud.githubusercontent.com/assets/374612/10788550/939ba6de-7d78-11e5-9dd9-5866af3ada91.png)
