### ISSUE TITLE
Broken interwiki links [[...]] are not highlighted

### ISSUE THREAD

**Issue by guettli** [django-wiki/django-wiki#485]
Broken interwiki links [[...]] are not highlighted.

It would be nice if you see immediately which links are broken. 

Dokuwiki displays these links red underlined.

Is this a bug or feature?

**Comment by benjaoming** [comment]
It's a feature. Please use the link plugin for this stuff as the `[[ Link ]]` notation is not a part of the official Markdown syntax nor a really operational notation for storing data about links.

Argument 1

@the-glu is working on a Move feature #461 . This enables you to move articles. We can automatically fix stuff that is made using the link plugin if we design this properly.

Argument 2

There is a whole UI for searching articles in the Sidebar while editing. This sort of stuff is possible using our own conventions.

Argument 3

This is against using `[[ ... ]]` as our own notation: It is already in use so people will expect it to work in a specific way. I would recommend to not use it at all.

**Comment by benjaoming** [comment]
No rebuttals received :) Going to close this then, but thanks for coming up with the suggestion and feel welcome if you encounter other ideas or issues.

**Comment by Mortal** [comment]
How about highlighting Markdown-style links `[...](...)` to other wiki pages on the same wiki? E.g. when `/foo/bar/` contains `[example](../baz)`, it would be nice that the link is colored red if `/foo/baz/` does not exist in the wiki.
