### ISSUE TITLE
Changing password (or user account page)

### ISSUE THREAD

**Issue by jluttine** [django-wiki/django-wiki#490]
I may have missed something, but I can't find a link to a page where a user could change his/her password. And maybe some other user account settings like email address. Should it be a part of django-wiki by default or do admins need to create this feature themselves?

**Comment by benjaoming** [comment]
Correct, account handling has never been an intended feature. However, the password change might be so common, useful, and even warranted for good security practices that we should have it? You are welcome to post a PR for this feature -- remember a test in that case :)

**Comment by jluttine** [comment]
Or would a plugin be better?

**Comment by benjaoming** [comment]
Hmm, that would be a big refactor... I'm about to go on leave and finish 0.1, so it would be bad timing.. but I would really welcome a "password change" page within the current structure if you're able to work on it.

**Comment by jluttine** [comment]
Ok! I probably don't have the time for it now but I'll keep this in mind when I'll be working again on my wiki site project next time.

**Comment by y0no** [comment]
It will be really great to include this feature  :+1:

**Comment by benjaoming** [comment]
Coming up in next release, thanks to @inflrscns for the work!
