### ISSUE TITLE
Permission differentiation does not work.

### ISSUE THREAD

**Issue by cheremovsky** [django-wiki/django-wiki#494]
I created two user groups and two articles, which can be read and edited by the members and can not be read by others. Then I created two users with of these groups with no additional permissions.
However, both users can read and edit and do whatever they want with articles of the other group.
How could I fix it?

**Comment by benjaoming** [comment]
Ensure that users X and Y are not superusers. Ensure that you are actually logged in as these users while testing.

If you want to re-post this as an issue (and not a support request), you should specify it more technically and make sure you can recreate it.... here's the beginning part:

1. I run a fresh install django-wiki
1. I create two groups A and B, each with one user X and Z.
1. Then I create two articles Test1 and Test2. Test1 is owned by group A and user X, and "others" have no access. Test2 is likewise owned by group B and user Y and "others" have no access.
1. I then log in as user X. **PROBLEM**: I can read and write to article Test2.

Is this indeed the case?
