### ISSUE TITLE
Upgrade for Bootstrap 4

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#518]
Bootstrap 4 introduces severe changes.

It's currently in Alpha 2, so we have some time to prepare still.

http://v4-alpha.getbootstrap.com/

One definite choice IMO is to leave out flex boxes because quite predictably, IE does not support it properly. I thought in 2016, IE would've stopped having all the traditional CSS problems. But no.

**Comment by y2kbadbug** [comment]
I would say maybe add some kind of support for it, but since it's brand new, upgrading it could conflict with sites using bootstrap 3 trying to integrate it.

**Comment by benjaoming** [comment]
I experienced a lot of renamed classes from alpha2 to alpha3, so am also a bit sceptical of doing this before it's in beta.

**Comment by benjaoming** [comment]
Still lots of changes in Bootstrap 4 alpha releases... they've dropped IE9 support in Alpha 6: http://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/

**Comment by benjaoming** [comment]
Now very close to going to beta stage: https://github.com/twbs/bootstrap/milestone/41

**Comment by mhozza** [comment]
It's released now :)

**Comment by benjaoming** [comment]
OMG! :dancer:

**Comment by atombrella** [comment]
Seems to have been merged in #1035

**Comment by benjaoming** [comment]
Yes it's true, thanks! While this part is done, now we could now open a new issue for Bootstrap 5 :)
