### ISSUE TITLE
Reverse for 'logout' not found

### ISSUE THREAD

**Issue by mizi** [django-wiki/django-wiki#545]
0.1.1 breaks URL resolving. 'wiki:logout' URL is no longer defined if ACCOUNT_HANDLING is set to False, but 'wiki:logout' is still used unconditionally in base_site.html, which causes the following exception:

> Exception Type:	NoReverseMatch
> Exception Value:	
> Reverse for 'logout' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

**Comment by benjaoming** [comment]
Ack!

**Comment by mizi** [comment]
Thanks! :)

**Comment by benjaoming** [comment]
Released in 0.1.2
