### ISSUE TITLE
Simple shortstop

### ISSUE THREAD

**Issue by Jzarecta** [django-wiki/django-wiki#548]
I tried to install django-wiki from pip and start a project and set up wiki (and other modules) on my installed_APPs but got the following error:
`RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

**Comment by benjaoming** [comment]
> .. `and isn't in an application in INSTALLED_APPS`

hint? ;)

Add "django.contrib.sites" to your INSTALLED_APPS? ;)

**Comment by Jzarecta** [comment]
I do have that since the very start.

**Comment by cXhristian** [comment]
Do you have SITE_ID set? E.g `SITE_ID = 1`.

**Comment by Jzarecta** [comment]
Yes:
```
STATIC_URL = '/static/'
SITE_ID = 1
APP_LABEL = 'wiki'
```

**Comment by Jzarecta** [comment]
Here is my whole settings.py
http://dpaste.com/17T0065

**Comment by Jzarecta** [comment]
Ah error changed, the past one is fixed. Thanks.

**Comment by benjaoming** [comment]
Good your problem was fixed, for more support use IRC or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-wiki)
