### ISSUE TITLE
SimpleMDE editor support

### ISSUE THREAD

**Issue by SaeX** [django-wiki/django-wiki#551]
I'm trying to figure out whether a WYSIWYG editor exists for this project or can be plugged in easily. 

I understand [MarkItUp](http://markitup.jaysalvat.com/examples/markdown/) is supported, but that's not a true WYSIWYG editor, as it e.g. shows `**` in front of bold text, instead of showing the actual text in **bold**. My middle-aged, non-technical users will find this confusing.
The latter is achieved by alternative WYSIWYG editors like e.g. [TinyMCE](https://www.tinymce.com/) or [CKEditor](http://ckeditor.com/demo) or [StackEdit](https://stackedit.io/editor).

I noticed CKEditor has a [Markdown add-on](http://ckeditor.com/addon/markdown). StackEdit does Markdown by default.

**Comment by benjaoming** [comment]
It doesn't make sense as the plugins rely on being able to define their own place holder type tags.

The reason for choosing Markdown is precisely to encourage source code editing which we all know is superior to wysiwyg ;)

> My middle-aged, non-technical users will find this confusing.

No they won't just guide them gently, they will feel proud and empowered once they know Markdown.

**Comment by teury** [comment]
https://github.com/onepill/django-simplemde

https://simplemde.com 😂😂 😯

**Comment by SaeX** [comment]
@teury: nice! 
How does this integrate with `django-wiki`? I assume no `SimpleMDEField` should be used - is it as simple as calling `$('.simplemde-box')[0].SimpleMDE` in Javascript?

**Comment by benjaoming** [comment]
Closing this in favor of #537 - let's try to have the discussion in one place, @syslo is investigating different editor alternatives.

**Comment by cookyman74** [comment]
d

**Comment by Carltonpituitary** [comment]
The answer’s evident https://jqxwidgets1.github.io/EQ5mmU9wz_Bd7GQaNRkNpeR8ahY6GZ2WUbEtnEwpvBIlaZfr4_I5aEsNkmAFmphFKGyZmuPNNeo/
