### ISSUE TITLE
Slug field js error: ReferenceError: downcode is not defined

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#554]
When creating new articles, the slug field is no longer auto-populated. 

Django 1.9

**Comment by teury** [comment]
Error # slug  https://demo.django.wiki/0/

if you put a single number in the slug creates an error

**Comment by benjaoming** [comment]
Opened up #558 for that.

**Comment by benjaoming** [comment]
Fixed in #591
