### ISSUE TITLE
Removing "Powered by django-wiki, an open source application under the GPLv3 license"

### ISSUE THREAD

**Issue by Arken94** [django-wiki/django-wiki#555]
Hello there! I am not sure where else to pose this question so I decided to ask it by creating an issue (although it is no issue), so sorry for any confusion. However, when using django-wiki in a commercial, production environment what is the allowability of removing the "Powered by django-wiki, an open source application under the GPLv3 license" statement at the bottom of each page?

**Comment by benjaoming** [comment]
Sure that's allowed, just overload the template, it's a normal django app :)

https://docs.djangoproject.com/en/1.9/ref/settings/#template-dirs
