### ISSUE TITLE
Is there a way to configure settings to use s3 for media?

### ISSUE THREAD

**Issue by dkarchmer** [django-wiki/django-wiki#556]
I tried to use django-storages with

```
WIKI_IMAGES_STORAGE_BACKEND = 'storages.backends.s3boto.S3BotoStorage'
```

but does not seem to work. Is there an existing image storage backend to have all media stored on AWS S3?

Thanks,

**Comment by benjaoming** [comment]
@dkarchmer try being more specific than "does not seem to work". Are you reporting a bug? Or are you requesting a new feature?

If it's a support request, you should ask somewhere else - see [the Readme](https://github.com/django-wiki/django-wiki#community).
