### ISSUE TITLE
The image inserted is not shown

### ISSUE THREAD

**Issue by lgmcode** [django-wiki/django-wiki#557]
Hello, this is a nice wiki system. But I wonder why the image inserted in the demo page [https://demo.django.wiki/](url) is not shown. Could you figure this out? Thank you.

**Comment by teury** [comment]
1. Cache. https://demo.django.wiki/media/cache/3a/f7/3af75ba972a5ff8350a373fb112238fb.jpg
2. image,  https://demo.django.wiki/media/wiki/images/1/a1b5813b5f934663a502c727230c700b/djangowikilogo.png

TRanslate.

It must be a problem with the cache.
but before it looked good .

**Comment by benjaoming** [comment]
Ah yes, the automated update script was having issues. Thanks for telling! The problem should be fixed now, please fell welcome to open up new issues if the demo page is down!
