### ISSUE TITLE
Slug validation should deny numbers-only

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#558]
@teury wrote:

> if you put a single number in the slug creates an error

...meaning that the form accepts '1' as a slug, but the url pattern doesn't match. The point is that a number is interpreted as an Article ID and not a slug path, so any pure number shouldn't be accepted as a slug.

**Comment by teury** [comment]
Fix error numerical URLs.

Django-wiki/Wiki/URLs.py

Def get_article_urls(self):
.   urlpatterns =[
.       url('^P<article_id>\d+)/$',
.            self.article_view_class.as_view(),
.           name ='get'),
# Change 
    Def get_article_urls(self):
   urlpatterns =[
       url('^P<article_id>\d+)/get$',



\d+)/"He can be whatsoever Digits
"
