### ISSUE TITLE
Create docker-image

### ISSUE THREAD

**Issue by BirgerK** [django-wiki/django-wiki#560]
Hi there,

I'm interested in using this project, so I read the installation-guide. Then I was like "u seriouz?". Seems like this project needs lots of configuration for get it running.

If there is a docker-image it would be much easier to use it!

With a docker-image, as an user you could focus on "where shall it run" and on "with which" config. You can just pass some params (like sql-host and sql-db) as environment-variables to your docker-container and you don't have to care about that much necessary installation-stuff.

Nightly regards

**Comment by benjaoming** [comment]
> Then I was like "u seriouz?".

LOL... well fortunately, that's life, and we don't just advice people to run some random Docker image. 

TBH, I would not hire people or trust them with my data if they were running random Docker images.

I would welcome a DockerFile for the `testproject` or as a documentation example but I wouldn't encourage people directly to just fetch binary files.

Also, this: https://www.youtube.com/watch?v=PivpCKEiQOQ :P

**Comment by benjaoming** [comment]
Btw there's a demo server, you know?

http://demo.django.wiki/

**Comment by BirgerK** [comment]
ofc, you're right. You should not give your data to a blackbox. At most Docker images/repositories from DockerHub you're able to see the dockerfile or/and the git-repository is linked. ofc you should check it before you run it!

I think a docker-image provided by the project-developers should be trustworthy. What I wanted to state here.

(Sorry, don't know what `testproject` means here)

Yeah, I saw your demo and that's why I want it! ;)

**Comment by benjaoming** [comment]
Hi @BirgerK ,

It's true that we can put up a Docker image and endorse it, but I'm afraid it'll just be put into production. I don't wanna support that kind of scenario.

If you wanna run this project as a development / demo, these are the steps:

    mkvirtualenv yourtest
    git clone ...
    cd django-wiki/
    pip install -e .
    python testproject/manage.py runserver

Done ;)

But if you want to deploy it for any real life issues, I think reading the docs is a _must_.

Don't let this stop you from creating your own Docker repo and share it though, you're totally free to do so! :)

Btw. I think [this project template](https://github.com/django-wiki/django-wiki-project-template) is a better way to share easy deployments and bootstrapping of projects. It just needs a little update, and it could come alive again?

**Comment by benjaoming** [comment]
Someone has already created a Dockerfile here:

https://hub.docker.com/r/camandel/django-wiki/~/dockerfile/

**Comment by blackandred** [comment]
I made a production-ready container that is building for each new release automatically.

https://github.com/riotkit-org/docker-django-wiki
