### ISSUE TITLE
Markdown Safe Mode is Deprecated

### ISSUE THREAD

**Issue by prikhi** [django-wiki/django-wiki#571]
I was looking into the possible options that `markdown.Markdown` could take and I found this note about `safe_mode` being deprecated:
https://pythonhosted.org/Markdown/release-2.6.html#safe_mode-deprecated

I am generating wiki pages from models that have multiple WYSIWG edited fields that return HTML instead of Markdown. So to make that work I will have to disable `safe_mode` and probably use Bleach with a list of approved tags.

If that kind of change would be accepted, I could refactor my work from being project-specific into a PR to django-wiki. If so, it would be good to know the desired settings API.

**Comment by benjaoming** [comment]
Thanks for reporting! And great, let's get rid of this practice and introduce a better one.

That should also be the last straw in supporting Python 2.6, which has made us conditionally use an even older version of Markdown:

https://github.com/django-wiki/django-wiki/blob/master/setup.py#L67

Is there any way to achieve the previous behavior without introducing Bleach as a new dependency?

**Comment by prikhi** [comment]
I've used `html.parser.HTMLParser` to strip tags before: http://stackoverflow.com/a/925630/1998376
This could probably be modified to replace tags w/ text, or to escape all tags as well.
