### ISSUE TITLE
Can upload files (pdf, txt) but images don't upload.

### ISSUE THREAD

**Issue by arlyon** [django-wiki/django-wiki#572]
Like title, images don't get uploaded to the server. No server issues in the terminal. Media directory works fine otherwise. Maybe it's something to do with PIL? or one of the other image processors? There's not much info I can give. Any way to turn on extra logging? `THUMBNAIL_DEBUG = True` doesn't help.

**Comment by benjaoming** [comment]
Hey @arlyon 

You need to give much more info. Are you running a development server? Does it happen only in production? What's the log out put? Can you locate the file on your drive?

I recommend asking these questions on IRC or StackOverflow until you know it's an issue - see the README and the guidelines for contributing:

![screenshot from 2016-09-28 11-45-30](https://cloud.githubusercontent.com/assets/374612/18908743/1a92e106-8571-11e6-9b49-430fd8f9f2be.png)

**Comment by arlyon** [comment]
ubuntu ver 16.04 LTS
python ver 3.5.2
django ver 1.9.9

I asked if there were any additional logs that could explain why the wiki isn't able to upload images specifically (and if pillow/pil was the problem). Like I mentioned, media upload works fine otherwise. Other apps on the same server work fine. The image does not exist on drive, since it doesn't get uploaded. Uploading attachments in the wiki app works fine. It is in dev. Nothing comes up with either thumbnail debug or debug set to true.

I'm not sure what log files I can give you because that's what my question is.

**Comment by benjaoming** [comment]
Do you mean that you use the Attachment or the Images plugin to upload your image files?

In attachments, there's a strict default set of file extensions allowed:

![screenshot from 2016-09-28 12-34-30](https://cloud.githubusercontent.com/assets/374612/18910386/0b137ba8-8578-11e6-90a0-3e118b41f1da.png)

**Comment by arlyon** [comment]
I am trying to upload images.

> Uploading attachments in the wiki app works fine.

![image](https://cloud.githubusercontent.com/assets/8715352/18910410/289d37fe-8578-11e6-9ddd-c353de144cde.png)

Try to upload an image, the form is posted and yet the image is not uploaded.

**Comment by benjaoming** [comment]
I tried and it works, too:

https://demo.django.wiki/Test/_edit/

**Comment by arlyon** [comment]
Ok

**Comment by arlyon** [comment]
I am trying to submit a bug report. Is there any additional logging I can enable that will help me identify what is causing the image upload bug I am experiencing so that I can make it easy to fix? Currently the failed upload produces no errors.

I understand it is working on the demo site, but that doesn't really help me solve the problem.

**Comment by benjaoming** [comment]
If - like you say - the image isn't to be found on your disk, it's worth debugging the requests and the response code. Django-wiki logs everything in the `wiki*` name space, you can configure logging using [LOGGING](https://docs.djangoproject.com/en/1.10/topics/logging/).

**Comment by arlyon** [comment]
So it turns out the form was being sent but fails `form.is_valid()`

ValueError: The ImageRevision could not be created because the data didn't validate.

`form.errors` returns `<ul class="errorlist"><li>unsaved_article_title<ul class="errorlist"><li>This field is required.</li></ul></li></ul>` which doesn't make sense because I haven't modified the article at all.

**Comment by benjaoming** [comment]
Could you share the image file you're trying to upload if that's what's causing the err?

**Comment by arlyon** [comment]
It's just a plain png file.

![image](https://cloud.githubusercontent.com/assets/8715352/18916952/933b0d84-8596-11e6-96eb-794213706364.png)

**Comment by benjaoming** [comment]
> (github's image upload converts to png)

Well, then there's no point ;)

So are you saying it happens to any picture that you upload?

And does it work for you on the demo site or not?
