### ISSUE TITLE
markdown image tag is not working: Directory index forbidden

### ISSUE THREAD

**Issue by johnfwhitmore** [django-wiki/django-wiki#573]
When I upload an image in an wiki page it's getting up loaded to the server to in the location:

media/wiki/images/9/3ebe4e2f840a4437b3de1d35c1b06ac2/P9260018.JPG

I can point my browser at that file directly using it as a URL and the image gets displayed in my browser. So the image is there and is being served by the web server (Nginx). However when the image is embedded in a wiki page with "[image:1]" I get "image not found" being displayed instead of the image.

I've looked at nginx logs I'm getting two error lines:

2016/10/04 17:56:35 [error] 1236#0: *1 directory index of ".../media/wiki/images/9/3ebe4e2f840a4437b3de1d35c1b06ac2/" is forbidden, request: "GET /media/wiki/images/9/3ebe4e2f840a4437b3de1d35c1b06ac2/ HTTP/1.1", 

2016/10/04 18:00:18 [error] 1236#0: *11 open() ".../media/wiki/images/9/P9260018.JPG" failed (2: No such file or directory), request: "GET /media/wiki/images/9/P9260018.JPG HTTP/1.1", 

So it appears that the directory don't have permission to be indexed but on my server there is permission in the linux file system. Since django-wiki created this directory structure on the server I'd assume that it would set up the permissions required.

**Comment by benjaoming** [comment]
Thanks for the thorough report @johnfwhitmore - is there a chance that your uwsgi application workers run as a different user from nginx? It looks like nginx can read the files but the django application layer can't...

**Comment by johnfwhitmore** [comment]
They have been different users, but since django-wiki has created the directories under my media directory with fairly open permissions I thought it would make no difference:

$ ls -l media/
total 12
drwxrwxr-x 3 john john 4096 Sep  6 12:41 photologue
drwxr-xr-x 3 john john 4096 Sep  9 21:23 uploads
drwxr-xr-x 3 john john 4096 Oct  4 17:30 wiki

$ ls -l media/wiki/
total 4
drwxr-xr-x 3 john john 4096 Oct  4 17:30 images

Those permissions look fairly open but nginx has been running under user "www-data" and gunicorn has been running under my user name. I've changed that so that both nginx and gunicorn are running under my username. That change has not changed the output in the web page as the image is still "not found" but it has cleared the Nginx error messages. I've now no idea what is the perceived problem.

**Comment by benjaoming** [comment]
Please also check the permissions inside those directories.

And read about umask, your problem might be that the directory or disk is running an unconventional umask: https://en.wikipedia.org/wiki/Umask

**Comment by johnfwhitmore** [comment]
Thought I had it. Tried to point the browser at the media directory and got "permission denied" so made a small change to nginx configuration adding "autoindex on" to the media directory. This now means that I can look at the contents of my media directory and all sub directories down to the image directory:
media/wiki/images/9/3ebe4e2f840a4437b3de1d35c1b06ac2
and view the image:
wiki/images/9/3ebe4e2f840a4437b3de1d35c1b06ac2/P9260018.JPG

That has not changed the output by the wiki page at all. Still "image not found"

**Comment by johnfwhitmore** [comment]
Thought I had it. Tried to point the browser at the media directory and got "permission denied" so made a small change to nginx configuration adding "autoindex on" to the media directory. This now means that I can look at the contents of my media directory and all sub directories down to the image directory:
media/wiki/images/9/3ebe4e2f840a4437b3de1d35c1b06ac2
and view the image:
wiki/images/9/3ebe4e2f840a4437b3de1d35c1b06ac2/P9260018.JPG

That has not changed the output by the wiki page at all. Still "image not found" I don't think that umask setting is the issue as I can now look at the entire media directory structure.

Just had a thought, django-wiki is probably not trying to display the image but rather pre-process that image in some way.

**Comment by benjaoming** [comment]
Just remembered - when displaying images, they are rendered through a thumbnail library for Django called `sorl.thumbnail`, and it also needs access to create `MEDIA_ROOT/cache`. I can't see this directory in your directory listing, indicating that you haven't set the right permissions on `MEDIA_ROOT` itself.

**Comment by johnfwhitmore** [comment]
I have the thumbnail lib:
sorl-thumbnail            - Thumbnails for Django
  INSTALLED: 12.3
  LATEST:    12.4a1

And I'm not sure about the cache directory. Django-wiki created the wiki directory in MEDIA_ROOT, so not sure why it wouldn't just create cache directory if it needed it. I've created it and made sure it has permissions but still no joy.

**Comment by benjaoming** [comment]
What's the permissions on your MEDIA_ROOT?

**Comment by johnfwhitmore** [comment]
drwxrwxr-x 6 john john 4096 Oct  5 15:48 media

And processes are running as john

**Comment by benjaoming** [comment]
Okay, next thing to notice: All article data rendering is cached. Make sure you navigate to the article and use "Preview" to render data without caching.

**Comment by johnfwhitmore** [comment]
Checked without caching and it makes no difference the image is still not found. 

Is there any way that I can turn on logging in the wiki to see what it's doing?

**Comment by benjaoming** [comment]
Did you look at the code and find log statements you want printed? ;)

If - like you say - there's something being logged that you wish to read, then it's all the conventional way... Django-wiki logs in the `wiki*` name space, you can configure logging using [LOGGING](https://docs.djangoproject.com/en/1.10/topics/logging/).

I get a sense that no thumbnails are generated, so you might also wanna check that you have Pillow compiled with libjpeg etc. Read the Pillow docs: https://pillow.readthedocs.io/en/3.4.x/installation.html

**Comment by johnfwhitmore** [comment]
Checked without caching and it makes no difference the image is still not found. 

Is there any way that I can turn on logging in the wiki to see what it's doing?

**Comment by johnfwhitmore** [comment]
Looking at the code, specifically "plugins/images/markdown_extensions.py"... I'm looking at a wiki article with one image:
wiki/images/1/c91ee8f8d5fb4d58866239197bf660d9/P9300022.JPG
markdown_extensions.py ImagePreprocessor run takes the [image:1] and replaces it with:
html <figure class="thumbnail" style="width: 250px;"><div class="caption"><em>Image not found</em></div><figcaption class="caption">{{{IMAGECAPTION}}}</figcaption></figure>

That looks wrong, but I'm new here. So looking at the template it's attempting to render "plugins/images/templates/wiki/plugins/images/render.html" that template is expecting a context which includes:
{{ revision.image.url }}
{{ thumb.url }}
{{ revision.get_filename }}

Back to the ImagePreprocessor method and it passes a context to the template of:
                        context={
                            'image': image,
                            'caption': caption_placeholder,
                            'align': alignment,
                        })

The two lists don't seem to match up at all? So as a newbie I just did an install using pip and that's giving me wiki==0.1.2 so perhaps I've grabbed, or pip has grabbed the wrong version?

**Comment by benjaoming** [comment]
You need to wrap your copy-pasted code snippets in the right GH flavoured markdown tags.

https://guides.github.com/features/mastering-markdown/

As I've said earlier, all this stuff works for me and is also working on demo.django.wiki

Did you figure out if your Pillow installation actually supports JPEG / PNG?

**Comment by johnfwhitmore** [comment]
Sorry, my bad, hit the trigger without a preview. Pillow is installed and working. I was trying to ask a question about the code. I used pip to install wiki which installed version 0.1.2 so I might have the wrong version. My question concerns the code in "plugins/images/markdown_extensions.py". That code is processing the [image:1] markdown and replacing that directive with the html:

    <figure class="thumbnail" style="width: 250px;">
        <div class="caption"><em>Image not found</em></div>
        <figcaption class="caption">{{{IMAGECAPTION}}}</figcaption>
    </figure>

That looks wrong to me. My question relates to the context data which the template "plugins/images/templates/wiki/plugins/images/render.html" is expecting to receive and the the context data which the method "ImagePreprocessor" in the file "plugins/images/markdown_extensions.py" is passing to the template. To my mind the two just don't match up at all. The template is expecting context data of:

- {{ revision.image.url }}
- {{ thumb.url }}
- {{ revision.get_filename }}

Where as the preprocessor method is passing in the context data of:
- 'image': image
- 'caption': caption_placeholder
- 'align': alignment

I may have completely misunderstood the code but given the mismatch of context data the correct html is not going to be inserted into the resulting wiki document?

**Comment by benjaoming** [comment]
You've probably missed this statement:

    {% with image.current_revision.imagerevision as revision %}

**Comment by benjaoming** [comment]
I wrote this:

> Did you figure out if your Pillow installation actually supports JPEG / PNG?

You wrote:

> Pillow is installed and working.

Does this mean you read the instructions for Pillow and checked that it was build against the right libraries?

Also, as I said: This is working and has been working for a long time. You are welcome to look for errors in the _codebase_, but the error/discrepancy is probably in your local setup. Suggesting that there's a problem in the context data is the same as suggesting that ALL installations of django-wiki won't support image thumbnails which I'm telling you is not the case.

**Comment by johnfwhitmore** [comment]
I tested Pillow from the Python command line, loading both a jpeg file and a png file then using the thumbnail method to make a thumbnail. It all working without any errors so I decided that Pillow was happy with jpeg, png and thumbnails.

~~~~{.python}
Python 3.5.1 (default, Dec 09 2015, 07:29:36) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> j = Image.open("../media/wiki/images/1/c91ee8f8d5fb4d58866239197bf660d9/P9300022.JPG")
>>> p = Image.open("../media/wiki/images/1/0471de91ebee44dc8a215a572d8b2ee0/top.png")
>>> from __future__ import print_function
>>> print(j.format, j.size, j.mode)
JPEG (1920, 1080) RGB
>>> print(p.format, p.size, p.mode)
PNG (1008, 550) RGBA
>>> p.show()
>>> j.show()
>>> j.show()
>>> size = (128, 128)
>>> j.thumbnail(size)
>>> p.thumbnail(size)
>>> print(p.format, p.size, p.mode)
PNG (128, 69) RGBA
>>> print(j.format, j.size, j.mode)
JPEG (128, 72) RGB
>>> p.show()
>>> j.show()
~~~~~~~

**Comment by benjaoming** [comment]
Okay thanks for explaining, so here is what I gather:

1. You have a working Pillow installation
1. You have been using the _Preview_ function to avoid caching while testing
1. There are no images in `MEDIA_ROOT / cache` - the directory doesn't even exist
1. The permissions for `MEDIA_ROOT` are correct.

This is all very strange!

I'm thinking now if stuff is broken because of a new version of `sorl.thumbnail`.. the one that I know is working is 12.3, the latest stable, are you using a different version?

**Comment by benjaoming** [comment]
...also, could you check in your database if it has the tables for `sorl.thumbnail` created, it's called `thumbnail_kvstore`?

**Comment by ViggieSmalls** [comment]
I have/had the same problem!
I made a totally fresh installation of django-wiki in a virtualenv using 
`pip install git+git://github.com/django-wiki/django-wiki.git`
according to the documentation on http://django-wiki.readthedocs.io/en/latest/installation.html
Setting THUMBNAIL_DEBUG = True ([hint1](http://stackoverflow.com/questions/4356995/sorl-thumbnail-not-working)) in my settings.py file brought up the issue benjaoming noticed. There is no table `thumbnail_kvstore`. Making the migrations for sorl-thumbnail manually ([hint2](http://stackoverflow.com/questions/35129908/django-1-9-sorl-thumbnail-memcached)) does fix the issue:
```
manage.py makemigrations thumbnail 
manage.py migrate
```
Now I get at least a link to my photo. But then comes the next problem. The uploaded image can't be found. Clicking it opens a Window which says:

> This image failed to load.

When I go on the Admin Interface to Wiki Images -> Images -> Image:strand.jpg and click on the link next to Currently what i get is this:

> The requested URL /admin/wiki_images/image/2/change/wiki/images/1/a9d0392a75004edb8eea6e3e443cc20a/strand.jpg/change/ was not found on this server.

But the image **is** in that directory! What is wrong?

**Comment by ViggieSmalls** [comment]
Update: I added MEDIA_ROOT and MEDIA_URL to settings.py:
```
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, '')
```
Now what I get when clicking on the image link:
> This image failed to load.
And in admin section:
> This article was not found, and neither was its parent article.
This time it's a PNG.

**Comment by benjaoming** [comment]
```
MEDIA_ROOT = os.path.join(BASE_DIR, '')
```

You're appending an empty string instead of the name of the directory?

**Comment by ViggieSmalls** [comment]
Well, to be fair, it is the same thing as `MEDIA_ROOT = BASE_DIR `, you're right :D 
Still, doesn't work =(

**Comment by benjaoming** [comment]
@ViggieSmalls @johnfwhitmore - it's vital to update article caching every time you change a setting that affects the path resolution of images. Otherwise the article contents will be rendered with the old `Image not found` message. Only re-rendering it through a preview or a new revision is useful when debugging.

Anyways, have you solved the issue any of you?

**Comment by johnfwhitmore** [comment]
Sorry I've been busy, so only getting back to you now. The web site that I
was working on already had a django app installed for managing photographs.
photologue I just used that app to add the photos creating a new markup
token to add images into wiki documents from photologue. I have never fixed
the problem as I could not get to the bottom so just went with the work
around.

**Comment by benjaoming** [comment]
Thanks for the report-back @johnfwhitmore - will close this issue, but it contains a lot of nice hints and information to anyone facing similar problems. Could be nice with some kind of FAQ in the docs.

**Comment by benjaoming** [comment]
We actually have an FAQ section, but it was never filled in :) -> http://django-wiki.readthedocs.io/en/master/tips/index.html
