### ISSUE TITLE
Easier to integrate into previous designs

### ISSUE THREAD

**Issue by y2kbadbug** [django-wiki/django-wiki#578]
I see that you guys have added customization support as in setting the site and configuring the menus.  However, I am trying to implement the wiki app into my entire Django website which has its own navigation bar, a sidebar, footer, etc.

Are there any modifications that can be easily made to integrate smoother?

**Comment by duvholt** [comment]
http://django-wiki.readthedocs.io/en/latest/customization.html

By overriding `base.html` you can include the parts you want. By extending your own equivalent of `base_site.html` you can remove all the extra markup for navbar etc.
Take a look at [base_site.html](https://github.com/django-wiki/django-wiki/blob/master/wiki/templates/wiki/base_site.html) to see which blocks you can include. 

Remember to add `{% render_block "js" %}` and `{% render_block "css" %}`for JS and CSS.

**Comment by y2kbadbug** [comment]
These customizations do not seem intended for sites that already have their own designs implemented.  I will accept this as a "won't fix", however, it still is an issue for people who have already implemented their own design and want to use the wiki without heavily modifying your templates.

Thanks.

**Comment by duvholt** [comment]
Maybe I wasn't clear enough. 

An example of a project with it's own design implementing the wiki blocks: 

https://github.com/dotKom/onlineweb4/blob/develop/templates/wiki/base.html

Result: https://online.ntnu.no/wiki/online/

Simply create a new template called `wiki/base.html` and extend whatever base template you already have. Then add empty template blocks for `wiki_contents` etc,
