### ISSUE TITLE
Getting Started on Windows

### ISSUE THREAD

**Issue by berot3** [django-wiki/django-wiki#581]
Could you please point out, for the newbs under us, how to proceed after _pip install Pillow_ and _pip install wiki_.

I am not even sure if it installed correctly. according to the docs [1] there should be a manag.py.
But all I could find was "\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\django\conf\project_template\manage.py-tpl"...

[1] http://django-wiki.readthedocs.io/en/latest/installation.html

**Comment by ViggieSmalls** [comment]
It is actually everything written in the link you posted.
`pip install wiki` has some issues. Rather install from the repository 
`pip install git+git://github.com/django-wiki/django-wiki.git`
then run `pip startproject testwiki`
Go to `settings.py` and adjust the variables INSTALLED_APPS, TEMPLATES, SITE_ID according to the instructions.
And don't forget to edit `urls.py`, also according to the instructions.
Run 
```
python manage.py makemigrations
python manage.py makemigrations thumbnail #needs to be done separately, or you can't insert images.
python manage.py migrate
```
And create a superuser for the project:
`python manage.py createsuperuser`
Now you can proudly start the development server with
`python manage.py runserver`
Watch Youtube Videos for more basic knowledge.

**Comment by benjaoming** [comment]
@berot3 you need to create a django project first. That implies becoming familiar with Django.

I'm closing this, please use mailing list or IRC channel for support requests in the future.
