### ISSUE TITLE
Django 1.10.4

### ISSUE THREAD

**Issue by y2kbadbug** [django-wiki/django-wiki#588]
It appears that the latest version of Django Wiki is not compatible with Django 1.10.4:

  File "/home/dshafer/django/lib/python2.7/site-packages/wiki/models/__init__.py", line 54, in <module>
    if 'django.contrib.auth.context_processors.auth' not in django_settings.TEMPLATE_CONTEXT_PROCESSORS:
  File "/home/dshafer/django/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'TEMPLATE_CONTEXT_PROCESSORS'

It appears that the problem is this is being called regardless of the 1.8 check:

if 'django.contrib.auth.context_processors.auth' not in django_settings.TEMPLATE_CONTEXT_PROCESSORS:
    raise ImproperlyConfigured(
        'django-wiki: needs django.contrib.auth.context_processors.auth in TEMPLATE_CONTEXT_PROCESSORS')

**Comment by benjaoming** [comment]
@y2kbadbug - it's fixed in the current master and 0.2b2 prerelease

https://github.com/django-wiki/django-wiki/commit/d9d05f63bde76dbc957e7c2032d5c71aa7e4d62a
