### ISSUE TITLE
Bleach converts ">" to "&gt;" breaking blockquotes

### ISSUE THREAD

**Issue by nickfsolly** [django-wiki/django-wiki#596]
Blockquotes are no longer working as bleach converts `>` to `&gt;`

We can't do a simple find/replace as not all `>` characters represent a blockquote.

Thanks all.

**Comment by nickfsolly** [comment]
This issue also affects Markdown email links in the form `<joe@bloggs.com>`

**Comment by benjaoming** [comment]
Yes, you're right.

Googling this, I find that everybody bleaches *after* parsing with python-markdown. My problem when implementing it, was that I couldn't reliably figure out which tags to whitelist from the Markdown-generated contents.

**Comment by benjaoming** [comment]
@nickfsolly not sure how pressing your use case is, but would you be able to give feedback regarding the tag and attribute whitelist proposed in #598 ?

**Comment by nickfsolly** [comment]
@benjaoming had a look at #598 and, for my usage, it looks great.  Thanks for your support.

**Comment by benjaoming** [comment]
Fixed in #598, released in 0.2.1
