### ISSUE TITLE
S3 Storage not working 

### ISSUE THREAD

**Issue by daesu** [django-wiki/django-wiki#602]
Hi all, 

I have a Django project and have set the storage to S3 in the project settings as so;

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

Using Django 1.9.2 with Python 3.4 and django-wiki 0.2.1

This is giving the following error when used with django-wiki;

```
'str' object has no attribute 'get_valid_name'
```
```

Exception Type:	AttributeError
Exception Value:	
'str' object has no attribute 'get_valid_name'
Exception Location:	/home/riain/virtualenvs/laci/lib/python3.4/site-packages/django/db/models/fields/files.py in generate_filename, line 329

```

**Update**

The issue appears to be in the wiki images plugin models where the storage is specified as SETTINGS.DEFAULT_STORAGE 

It is expecting a path (str) whereas for django-storages it should be an instance of a storage object such as an instance of .S3BotoStorage for S3.

**Comment by benjaoming** [comment]
Hmm, what's the correct fix for this? To check the type first and allow both `str` and `Storage` instances?

**Comment by benjaoming** [comment]
ping @daesu

**Comment by daesu** [comment]
@benjaoming Apologies, I didn't see your comment at the time.

If it's still relevant to you, what I did was create a custom S3BotoStorage and used that. (See below)

```
class S3CustomStorage(S3BotoStorage):
    def _normalize_name(self, name):
        return name
```

Note: this was quite a while ago so may no longer be an issue.

**Comment by benjaoming** [comment]
@daesu there have been a few fixes for S3 since 2017. See:

https://django-wiki.readthedocs.io/en/master/release_notes.html

I don't have reports that indicate that S3 storage isn't working - so I would suggest to reach out to people who have done PRs and ask them what backends they're using etc.

**Comment by zyonash** [comment]
Hi @daesu - were you able to get S3 working as a backend for the django-wiki?  We're trying to leverage this functionality and we can't seem to get it working.  See: https://github.com/django-wiki/django-wiki/issues/1062

Thanks!
