### ISSUE TITLE
Bleach strips all styles (could be configurable)

### ISSUE THREAD

**Issue by black3r** [django-wiki/django-wiki#603]
Hi,

in our project we sometimes rely on django-wiki allowing the article writers to use their custom styles in an article.., with new django-wiki using bleach, this stopped working. It is possible to allow `style` attribute for all allowed tags, but bleach also requires a list of styles to allow, which defaults to an empty list, and is not configurable in current django-wiki release.

Would it be possible to add another setting for allowed styles, like the settings for allowed tags and attributes?

**Comment by benjaoming** [comment]
Yes, I would totally welcome that change. Would you be able to do a PR, adding this as a setting?

Sorry that this Bleach stuff has caused so many issues up until now :(
