### ISSUE TITLE
Installation of 0.2.3 using pip seems to be missing a file

### ISSUE THREAD

**Issue by black3r** [django-wiki/django-wiki#625]
specifically the glyphicons font from bootstrap, located at: `/wiki/static/wiki/bootstrap/fonts/glyphicons-halflings-regular.woff2` within the repository

causes a bug when calling `collectstatic`.. I've verified it by manually downloading the `.whl` archive from pypi and it seems to be missing there.., maybe something went wrong while publishing, since the file is in the repository in the `0.2.3` tag?

**Comment by mhozza** [comment]
I guess the MANIFEST should include also `.woff2` in addition to `.woff` and others.

**Comment by benjaoming** [comment]
Yes, thanks for spotting this!

**Comment by benjaoming** [comment]
Released as `0.2.4`, I was hoping to do `0.2.3.post1` but `wiki.core.version.get_version` (taken from Django) didn't seem to support this for `final` releases.
