### ISSUE TITLE
404 on initital user create with /wiki

### ISSUE THREAD

**Issue by Xelinor** [django-wiki/django-wiki#650]
Python Version: 3.5.2
Django version: 1.10
Wiki version: 0.2.4

Wiki URL's are configured to direct to /wiki as indicated in the installation instructions.

When a user goes to the wiki and creates an account, they are able to successfully, at which point they are directed to the login page. On that initial login, they are sent to http://foo.net/accounts/profile/

This results in a 404 error. Django debug giving:

```
Using the URLconf defined in foo.urls, Django tried these URL patterns, in this order:
^$ [name='index']
^admin/
^wiki/
^notifications/
The current URL, accounts/profile/, didn't match any of these.
```

If they return to http://foo.net/wiki they are logged in and are able to log out/in normally without trouble.

**Comment by benjaoming** [comment]
You should set this in your project's settings:

```
LOGIN_REDIRECT_URL = reverse_lazy('wiki:get', kwargs={'path': ''})
```

**Comment by Xelinor** [comment]
In the settings.py file for the whole project? I did that and it gives the same error...or is it supposed to be somewhere else?

**Comment by benjaoming** [comment]
Your django project is some folder that has a "manage.py" file and then it has a settings.py file, yes. You can read about it here: https://docs.djangoproject.com/en/1.11/ref/settings/#login-redirect-url

**Comment by Xelinor** [comment]
Ah, nevermind, had to restart apache and then it took effect. Works like a charm. Thank you!

**Comment by benjaoming** [comment]
Glad you found the solution!

As with any other repository on Github please read [the guidelines for contributing](https://github.com/django-wiki/django-wiki/blob/master/CONTRIBUTING.md). Thank you for your understanding and please help spread the word and stick around the support community (IRC/mailing lists) if you want to help others or have others help you.

![image](https://user-images.githubusercontent.com/374612/27585192-7b055c6c-5b3b-11e7-94a3-aab372de32a4.png)

**Comment by Xelinor** [comment]
It seems the same issue occurs when using the wiki to change a user password. It attempts to go to foo.com/_accounts/settings/

It does successfully update the password, it's just when it attempts to reload the page it is trying to direct to the root page rather then to the wiki page.

**Comment by benjaoming** [comment]
Thanks for noticing @Xelinor - yes, this looks like an issue, seems to redirect url has been hard coded :(
