### ISSUE TITLE
fixes for catastrosphic backtracking in search and haystack

### ISSUE THREAD

**Issue by Qarterd** [django-wiki/django-wiki#653]
I ran into what amounts to an infinite loop due to a regex in the search results view when searching with more than one keyword. I went ahead and fixed it as well as added support for highlighting multiple keywords when using haystack's AutoQuery. I'll leave it to the devs here as to how to properly integrate this fix through the plugin system. This was tested with Elasticsearch 2.4:

https://gist.github.com/anonymous/1858a56fe28be4008a2eb9f28eadd589

**Comment by benjaoming** [comment]
Thanks for the report and the Gist!

I'll have a look at how to implement your new version of `get_content_snippet`.

As for the haystack plugin, I'm not using it myself, and it doesn't really come with any tests, so the only way to update this part, is if someone with Haystack experience can do a PR and confirm that it works.

**Comment by benjaoming** [comment]
(or add a tox env that uses the haystack plugin, that'd be super cool)
