### ISSUE TITLE
RevisionPluginRevisions

### ISSUE THREAD

**Issue by jcl240** [django-wiki/django-wiki#659]
I am trying to create a plugin with its own revisions, however every time I try to add a new revision the old revision seems to be lost from the database. I'm not sure if I am misunderstanding the Revision system or if there is a deeper issue with the way revisions are being saved. Any help or pointers in the right direction would be appreciated. Here is the code where I try to create a new revision:

```
oldRevision = self.current_revision.supersenserevision

revision = SupersenseRevision(name=oldRevision.name,
                                             description=oldRevision.description,
                                             animacy=oldRevision.animacy,
                                             counterpart=oldRevision.counterpart,
                                             template="supersense_article_view.html")

revision.set_from_request(request)
revision.inherit_predecessor(self)
self.add_revision(revision, save=True)
revision.save()
self.save()
```

I am calling this function from a form's save function. Could this somehow be an issue with the references to objects that I am passing in and out of the function? 

Everything else seems to work fine (aka values are being updated and saved), its just that the old revision is no longer retrievable so I can't visualize the history.

**Comment by jcl240** [comment]
Here are the models:
`class Metadata(RevisionPlugin):

    def __str__(self):
        if self.current_revision:
            return self.current_revision.metadatarevision.name
        else:
            return ugettext('Current revision not set!!')

    class Meta():
        abstract = True
        verbose_name = _('metadata')

class MetadataRevision(RevisionPluginRevision):
    template = models.CharField(max_length=100, default="wiki/view.html", editable=False)
    name = models.CharField(max_length=100, primary_key=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return ('Supersense Revision: %s %d') % (self.name, self.revision_number)

    class Meta:
        abstract = True
        verbose_name = _('metadata revision')


class Supersense(Metadata):

    def newRevision(self, request):
        oldRevision = self.current_revision.supersenserevision
        revision = SupersenseRevision(name=oldRevision.name,
                                             description=oldRevision.description,
                                             animacy=oldRevision.animacy,
                                             counterpart=oldRevision.counterpart,
                                             template="supersense_article_view.html")
        revision.set_from_request(request)
        revision.inherit_predecessor(self)
        self.add_revision(revision, save=True)
        revision.save()
        self.save()
        return self


    def setCounterpart(self, newCounterpart):
        revision = self.current_revision.supersenserevision
        oldCounterpart = self.current_revision.supersenserevision.counterpart

        if newCounterpart is not oldCounterpart:
            revision.counterpart = newCounterpart
            revision.save()


    def __str__(self):
        if self.current_revision:
            return self.current_revision.supersenserevision.name
        else:
            return ugettext('Current revision not set!!')
    class Meta:
        verbose_name = _('supersense')

class SupersenseRevision(MetadataRevision):
    animacy = models.DecimalField(max_digits=2, decimal_places=0)
    counterpart = models.ForeignKey(Supersense, null=True, blank=True)

    def __str__(self):
        return ('Supersense Revision: %s %d') % (self.name, self.revision_number)

    class Meta:
        verbose_name = _('supersense revision')`

**Comment by benjaoming** [comment]
Is a new ID added in the database or do new revisions overwrite the old one?

**Comment by jcl240** [comment]
No a new ID is added, it seems that the issue is that the relation between the previous revision's RevisionPluginRevision object and the previous revision's supersenserevision object is not being maintained.

**Comment by jcl240** [comment]
Fixed!!!! Didn't realize that I had set name = models.CharField(max_length=100, **primary_key=True**)

**Comment by benjaoming** [comment]
Super, glad you had it fixed, glad you're writing plugins :+1:
