### ISSUE TITLE
Pygments

### ISSUE THREAD

**Issue by JeremyBolster** [django-wiki/django-wiki#665]
Could we add support for some nicer css in \<code\> blocks to allow for language specific syntax highlighting? Such as using the css generated from http://pygments.org/

**Comment by benjaoming** [comment]
Do you mean specifically for the inline `<code>` tag? AFAIK, no one does that?

There is syntax highlighting available, it's automatically enabled when you install `pygments` ;)

**Comment by JeremyBolster** [comment]
I should've looked the end of the docs, https://django-wiki.readthedocs.io/en/latest/tips/index.html Do you know how one would specify the programming language in markdown? In a code tag I could specify bash, python, java etc. 

PS. I'll try and add a quick install guide to the github wiki sometime this week.

**Comment by benjaoming** [comment]
Sounds good, please modify anything in the docs that you find sub-optimal, it's always great with fresh eyes!!
