### ISSUE TITLE
Feature request: small CRUD methods to manage articles

### ISSUE THREAD

**Issue by vincent-lg** [django-wiki/django-wiki#666]
When using Django for other purposes and trying to interface with Django-wiki, it can be somewhat difficult to create, edit or update wiki pages.  It's a relatively simple matter, and should (in my opinion) be placed in the views itself.  This would be even useful when using several apps in Django.  The four common (CRUD) needs would be:

- To create articles using the API.
- To retrieve articles (using their URIs or combined slugs).
- To update article's content (creating a new revision).
- To delete an article.

Although the last one is easily supplied, the three first needs are a bit complicated to implement.  I come from the "Evennia":https;//github.com/evennia/evennia project which uses Django.  Having a wiki in the game seemed really great, and Django-wiki was the first, natural choice.  Creating wiki entries from the game itself was a second must-have, and I created a few functions that (maybe) will show the idea much better than this long explanation.

**If you think this is a good idea, I will be happy to open a pull request.**

```python
"""Wiki operations.

This module contains operations to effectively communicate with the
wiki.  It would be a kind of top-level manager with over-simplified
operations to get, create and update wiki pages.

"""

from evennia import PlayerDB
from wiki.models import Article, ArticleRevision, URLPath

def get_URI(uri):
    """
    Return the wiki article (Article) to a given URI.

    Args:
        uri (str): the URI (a page URI).

    Returns:
        article (Article or None): the article, if found, or None.

    Example:
        article = get_URI("/facts")

    """
    try:
        path = URLPath.get_by_path(uri)
    except URLPath.DoesNotExist:
        return None

    return path.article

def create(path, title, content, user=None, message=""):
    """
    Create a new wiki page.

    Args:
        path (str): the page's new path (must be unusued).
        title (str): the title of the new page.
        content (str): the new page's content.
        user (Player, optional): the new page's owner.
        message (str, optional): the new revision's message.

    Returns:
        article (Artidcle): the new article.

    Notes:
        If `user` is unset, use Player #1 (the superuser).

        The provided path is an URI.  The parent is taken to be the
        one before the last '/' sign.  For example: 'a/b/c/' as a
        path would mean 'a/b' is taken to mean the parent, and 'c'
        is taken to be the article's new slug.

    """
    path = path.strip("/")
    if "/" in path:
        parent_path, slug = path.rsplit("/", 1)
    else:
        parent_path = ""
        slug = path
    parent = URLPath.get_by_path(parent_path)

    user = user or PlayerDB.objects.get(id=1)
    newpath = URLPath.create_article(
        parent,
        slug,
        title=title,
        content=content,
        user_message=message,
        user=user,
        ip_address="127.0.0.1",
        article_kwargs={'owner': user,
                        'group': None,
                        'group_read': True,
                        'group_write': True,
                        'other_read': False,
                        'other_write': False,
                        })

    return newpath.article

def update(article, content, user=None, message="", title=None):
    """
    Update an article, creating a new revision.

    Args:
        article (Article): the article object.
        content (str): the new content of the article.
        user (Player, optional): the user responsible for the update.
        message (str, optional): the message of the update.
        title (str, optional): the new article's title.

    Note:
        If `user` isn't set, get the player #1 (the superuser).
        If `title` is unset, will use the current article's title.

    """
    user = user or PlayerDB.objects.get(id=1)
    current = article.current_revision
    title = title if title is not None else current.title
    revision = ArticleRevision()
    revision.inherit_predecessor(article)
    revision.title = title
    revision.content = content
    revision.user_message = message
    revision.deleted = False
    revision.ip_address = "127.0.0.1"
    article.add_revision(revision)
    return revision
```

Thanks for your wonderful work,

**Comment by benjaoming** [comment]
Hi @vlegoff 

Thanks for opening this!

Re: some specific stuff:

```
def create(path, title, content, user=None, message=""):
```

In the above, I would prefer to have the `parent` specified together with a slug. This way, you force all the logic of path resolution to be handled in `get_by_urlpath` (the one you called `get_URI`).

Nice that you are using this Google Style Docstring stuff.. I haven't tried it with Sphinx, you can generate docs by running `make docs` and see how it looks.

Thinking very briefly about this, I think that it would be great to call this module `api` to be very clear that this is the stuff that's definitely intended not to break.. but it also implies some false promises about enumerating it, at which point I would think it starts to look clumsy.

How would you feel about working with `wiki.shortcuts` ? This would be a bit like `django.shortcuts`.

**Comment by vlegoff** [comment]
@benjaoming: thank you for your comment.  I thought at first a suite of methods in the manager would be great, then I learned doing this in the view might be a better place (I still have some trouble with Django's approach of MVC).  There's already a `Create` and `Edit` view which I could extend to add simple methods to create/update.  But I still feel this might not be the right place.  Having a new, simplified way of accessing these information (like a suite of shortcuts, as you suggested) might be the best choice.  I still need to learn about the Django structure that would be necessary, in order to not post too many mistakes.

Regarding the `slug` and `parent` in the `create` function, you mean to have separate arguments?  I must say I went the easy route, and using the `URLPath` API might not be the best one anyway.  The documentation was formatted for the project on which I was (where I had written these methods) but of course, I will adapt to what you are using.  Having nice documentation is always great.

Thanks again,

**Comment by benjaoming** [comment]
@vlegoff regarding the `parent` and `slug` arguments, yes I mean to let them replace the `path` argument:

```
def create(parent, slug=None, ...):
```

Mind you that since `URLPath` is *not* mandatory for an article, the shortcuts should also handle articles that don't belong to any URL :)

**Comment by benjaoming** [comment]
@vlegoff any news about your proposal? :)
