### ISSUE TITLE
Fix for settings page in Django 1.10.4+

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#687]
Report by @tomaszgy in #682:

> Hey, guys, thanks for a quick patch! Unfortunately, now when clicking on `Settings` button we're getting another error:
> ```python
> TypeError at /wiki/_settings/
> build_attrs() got an unexpected keyword argument 'name'
> ```
> 
> It seems like it's due to a change in `build_attrs()` method arguments in Django after 1.10.4:
> https://github.com/django/django/blob/master/django/forms/widgets.py#L243
> 
> No `**kwargs` anymore.

**Comment by tomaszgy** [comment]
Hello, I'm copy-pasting my comment from #682:

> Just realized that error occured with wiki 0.2.4 and Django 1.11.3 which is not a supported combination. Very sorry for the confusion!
