### ISSUE TITLE
wh I have modified the base_site.html. but it not does not work ?

### ISSUE THREAD

**Issue by daicoolb** [django-wiki/django-wiki#688]
Here are my changes in base_site.html 

```
    <title>{% block wiki_pagetitle %}{% endblock %}{% block wiki_site_title %} - Video Trace based on Deeplearning-\/\/  i K |{% endblock %}</title>     
 
```

 ```
    {% block wiki_header_branding %}
          <a class="navbar-brand" href="{% url 'wiki:root' %}">Video Trace based on Deeplearning-\/\/ i K |</a>
          {% endblock %}
```
but when I run "python manage.py runserver"
these changes does not work, can you tell me why ?

**Comment by yeisonvargasf** [comment]
Hi @daicoolb, all templates inherit from 'base.html' so you customization must be there.

**Comment by daicoolb** [comment]
I have know the reason now . Thanks for your remind. My change is not in the correct location.

**Comment by benjaoming** [comment]
@daicoolb please read the guidelines before posting issues, thanks

![image](https://user-images.githubusercontent.com/374612/30564537-8223b23e-9cc5-11e7-9fa9-5ec21866e98d.png)
