### ISSUE TITLE
ip setting not work

### ISSUE THREAD

**Issue by daicoolb** [django-wiki/django-wiki#696]
when I set the ip server is 0.0.0.0:8000, if I browse the 127.0.0.1:8000 , it works , but it does not work on the computer's ip, e.g. :***.***.***.***:8000

If I directly set the ip server is computer's ip , it also does not work. what's the problem.

**Comment by teury** [comment]
if you want a quick exit.
(vps ip)      ./manage.py runserver  ip:port


if you are going to deploy.
use this method >> http://michal.karzynski.pl/blog/2013/06/09/django-nginx-gunicorn-virtualenv-supervisor/
