### ISSUE TITLE
wiki.plugins.links: links to wiki articles don't respect fragment (#) part of the URL

### ISSUE THREAD

**Issue by citxx** [django-wiki/django-wiki#701]
links plugin cannot find an article, if URL fragment is added to its path.

## Reproduction steps

1. Create an article at path `/article-1` and with the following content:

    ```
    # Some header {: #some-header }
    ```

1. Create another article at path `/article-2` and with the following content:

    ```
    [link to Article 1](wiki:/article-1)

    [link to a header of Article 1](wiki:/article-1#some-header)
    ```

1. Observe the second link generated in the second article

**Observed result:** the link is generated without `href` attribute.
**Expected result:** the link should lead to the first article with the `#some-header` fragment attached to the URL.

## System information

```
$ django-admin.py --version
1.10.5
$ python --version
Python 3.5.2
$ uname -a
Linux citxx-yoga-ubuntu 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**P.S.** I have some problems with getting a working django project with the master django-wiki branch. But I can try a bit harder if you want me to test it :) #

**Comment by benjaoming** [comment]
Fixed in #733
