### ISSUE TITLE
Upgrade bleach>=2.1

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#702]
There seems to be security issues in the major bleach release, but also there seems to be backwards incompatible stuff.

**Comment by last-partizan** [comment]
Maybe even drop bleach alltogether? and replace with https://github.com/matthiask/html-sanitizer, or something else?

I'm trying to upgrade my project to python3, and bleach uses pinned dependency on html5lib with version incompatible with latest xhtml2pdf.

**Comment by last-partizan** [comment]
Yeah, probably html-sanitizer is a bit overkill.

I looked at issues at bleach, and found this https://github.com/mozilla/bleach/issues/255
They was thinking about replacing html5lib, but looks like it not gone too far.

Updating bleach here would fix my incompatibility, so i'll take a look. What do i need to know before i start?

**Comment by benjaoming** [comment]
@last-partizan 

For the upgrade, it's very important that configuration options aren't changed. I don't think that they will change.

Other than that, coverage is reasonably high.. so I would think it works when the tests say so :)

**Comment by last-partizan** [comment]
Updated bleach, but looks like now they removing tags from strings like `</html>only_this`, instead of escaping.
So, one test fails.

What should we do? I think bleach is correct in this case, and it's better to fix test to expect `only_this`.

**Comment by benjaoming** [comment]
@last-partizan if you open a PR for your changes, you will see results of automated tests etc :)

**Comment by last-partizan** [comment]
Done)

**Comment by benjaoming** [comment]
Fixed in #860 - thanks @last-partizan !!
