### ISSUE TITLE
Change zh-CN to zh-hans

### ISSUE THREAD

**Issue by Tantalus13A98B5F** [django-wiki/django-wiki#711]
`wiki` use the language code `zh-CN` for simplified Chinese, however `django.contrib.admin` use the code `zh-hans`. Given there can only be one language code set, one cannot use `admin` and `wiki` both in simplified Chinese at the same time. A simple renaming can fix this problem.

**Comment by benjaoming** [comment]
Hi @Tantalus13A98B5F - thanks for this issue report.

It's a bit annoying, because it means migrating a lot of user permissions in CrowdIn. But I will see what can be done.

**Comment by benjaoming** [comment]
Sorry, am a bit confused about the standards here and why the Django Admin is zh_Hans and not zh_CN. So I just made a link, so all the zh_CN is automatically also zh_Hans.

Do you have further guidance?
