### ISSUE TITLE
Recommended method for adding custom Markdown macros?

### ISSUE THREAD

**Issue by nschneid** [django-wiki/django-wiki#740]
I am planning to implement some specialized macros for my app. Is it better to add them to the existing macros plugin (https://github.com/django-wiki/django-wiki/tree/master/src/wiki/plugins/macros) or to create a separate plugin?

**Comment by benjaoming** [comment]
Sorry for the lack of input. Plugins are always at your disposal, and you are always welcome to open PRs for built-in stuff.

Please comment here, if you would like the issue re-opened regarding the builtin macros.
