### ISSUE TITLE
Is there a simple option for utf-8 slug enabling?

### ISSUE THREAD

**Issue by JohnJeong4p** [django-wiki/django-wiki#745]
Hi,

I am john jeong from south korea.
And now, I am doing some BM for my application.
But django-wiki doesn't support utf-8 slug default.
Is there an simple option to switch it?

"위키" is "wiki" in korean. But with current django-wiki, can not make [[위키]] to jump 위키 article. I hope there is a way to swith it.

**Comment by benjaoming** [comment]
This is already reported in #576
