### ISSUE TITLE
Create article template does not change

### ISSUE THREAD

**Issue by FerhatSaritas** [django-wiki/django-wiki#746]
First of all thank you guys for this great app. We appreciate what you do.

We are trying to use a custom 'create article' template. We did it easily for creat root but for some reason everytime we use a custom template for the overriden 'Create' class it opens the default templates.

Our code for the overriden 'Create' class looks like this:
`class UGACreate(Create):
    template_name = 'uga/create-root.html'

    @method_decorator(get_article(can_write=True, can_create=True))
    def dispatch(self, request, article, *args, **kwargs):
        return super(UGACreate, self).dispatch(request, article, *args, **kwargs)
`
We think we only need to override the template_name and the dispatch function. Maybe we got something wrong. We already created a root article and only want to access the create article page through the URL "localhost:8000/_create". We didn't know where to ask so excuse us if this is the wrong place to ask these kind of questions. 
Thanks for reading.

**Comment by benjaoming** [comment]
Are you just trying to replace a template?

Read here: https://docs.djangoproject.com/en/1.11/howto/overriding-templates/

As this isn't an issue but a support request, I will close it. Kindly ask you to read the instructions of the repository when opening new issues:

![image](https://user-images.githubusercontent.com/374612/33726839-81fd34e8-db76-11e7-96db-43fcf24c07f8.png)
