### ISSUE TITLE
Custom login pages do not seem to be possible ?

### ISSUE THREAD

**Issue by olymk2** [django-wiki/django-wiki#752]
From what i can tell if you use ACCOUNT_HANDLING = true then the code seems to use this.

In src/wiki/views/accounts.py
https://github.com/django-wiki/django-wiki/blob/274b09c74496a5dc571a0a0a352cc8887de586e9/src/wiki/views/accounts.py#L84
```
if not settings.ACCOUNT_HANDLING:
    return redirect(settings.LOGIN_URL)
```

In src/wiki/conf/settings.py
https://github.com/django-wiki/django-wiki/blob/d7b1c760322dc0d4a83a4635dd1d3ddc236c2895/src/wiki/conf/settings.py#L238
```
if ACCOUNT_HANDLING:
    LOGIN_URL = reverse_lazy("wiki:login")
```

So if i enable Account handling i get redirected to the wiki's login page, if i disable the account handling then i dont get the redirect, but because I have my own login page I have inconsistancy in particular my custom page has allauth support so users who authenticate with all auth cant login on the wiki login page.

From what i can tell I can not change this, is this the case ? Seems the code in src/wiki/conf/settings.py should not be there or shoudl at least check to see if LOGIN_URL is set ?

perhaps i am missing something ?

**Comment by benjaoming** [comment]
Have you set this?

https://docs.djangoproject.com/en/1.11/ref/settings/#login-url

**Comment by olymk2** [comment]
Yes i have this in my common settings.
```
LOGIN_URL = 'account_login'
```
I have searched my project and thats the only place its set, obviously common is loaded into all environment setting files.

**Comment by benjaoming** [comment]
Not sure what your error precisely is, but `'account_login'` is not a URL, you should either create a `reverse_lazy` proxy object or define a string with an absolute path.

The stuff you mentioned above makes absolute sense, so I suggest you ponder it again or describe for me what should be wrong.

The stuff about redirecting is working just fine. It's the Django authentication decorators (`login_required` etc.) on django-wiki's class views that trigger a redirect to `settings.LOGIN_URL`, this is standard django stuff.

Closing this, because it's not an issue. We have other channels for this, like IRC, where you can quickly just ask "is it me or is X broken".

**Comment by olymk2** [comment]
LOGIN_URL value is valid because as it says in the docs i can take a named_url and account_login is just the name url path.

It not sure on the order but it at least seems that the wiki settings are overriding my settings because I have to set ACCOUNT_HANDLING to true to get the redirects within the wiki to work.

Did not realize there was an IRC channel, I may just clone the repo and take out the setting in the wiki config and see if it then uses the default i have set.

**Comment by benjaoming** [comment]
You should set `WIKI_ACCOUNT_HANDLING=False` in your settings.

Have added an additional badge to the README, so hopefully IRC is more noticeable.

**Comment by olymk2** [comment]
I have tried that, looking at the logic here 
https://github.com/django-wiki/django-wiki/blob/d7b1c760322dc0d4a83a4635dd1d3ddc236c2895/src/wiki/conf/settings.py#L230

It uses WIKI_ACCOUNT_HANDLING to set the value of ACCOUNT_HANDLING which will set the correct urls to the ones i require but it also disables the redirects because of the code at this point which only redirects if ACCOUNT_HANDLING is true.

https://github.com/django-wiki/django-wiki/blob/274b09c74496a5dc571a0a0a352cc8887de586e9/src/wiki/views/accounts.py#L84

**Comment by benjaoming** [comment]
No offense, but I think maybe consider reading the code again and ponder when redirects occur and why the bundled \*login\* page redirects in case account handling is \*disabled\* ;)

**Comment by olymk2** [comment]
Cheers, i have obviously been looking at this for to long sorry for wasting your time :)

I will try again I have it working at the moment but only through forking and removing the wiki:login bit, i shall revert to master and try again.

**Comment by benjaoming** [comment]
> I have tried that

So did I, and it works for me, pages redirect to my custom login page, which I would think is the intention. But you have to put `WIKI_ACCOUNT_HANDLING = False`

**Comment by olymk2** [comment]
Got it working, by doing that and also removing LOGIN_URL setting so perhaps it was because i was using the urls name before that cause it to go wrong works now so thanks for the help @benjaoming
