### ISSUE TITLE
Missing migrations

### ISSUE THREAD

**Issue by georgekpg** [django-wiki/django-wiki#771]
I have found this issue both in master revision and in release 0.3

python manage.py makemigrations --dry-run
Migrations for 'wiki':
  /venv/lib/python3.6/site-packages/wiki/migrations/0003_auto_20180206_1353.py
    - Alter field current_revision on article
    - Alter field current_revision on revisionplugin
    - Alter field parent on urlpath
Migrations for 'wiki_attachments':
  /venv/lib/python3.6/site-packages/wiki/plugins/attachments/migrations/0003_auto_20180206_1353.py
    - Alter field current_revision on attachment

**Comment by benjaoming** [comment]
I actually noticed and fixed it.... last night :) https://github.com/django-wiki/django-wiki/pull/770 

Would you mind reviewing or commenting on this? It's quite sensitive not to add migrations that could have irreversible consequences on people's data :)

**Comment by georgekpg** [comment]
I am hot sure if I am right, but I have found this commit https://github.com/django-wiki/django-wiki/commit/cd7e4a687e38bc9494522b150b8c02bf3c093e2f#diff-729f2c5582f9f70aaaebe2e44b4b4efa

It makes changes in models and also in initial migration, and these changes does not correspond each other:

in src/wiki/models/article.py, line 31:
on_delete=models.SET_NULL,
in src/wiki/migrations/0001_initial.py, line 186:
on_delete=models.CASCADE),

This is the reason, why django wants another migration

By the way, this is tricky way of making changes, I think, that you may change initial migration only if you does not have already running production system.

**Comment by benjaoming** [comment]
@georgekpg the changes made to `0001_initial` only reflect the defaults of Django, so it should not be a problem.

But there are 3 changes in the models that necessitate another migration, and *that's* the problem.

Please correct me if I'm wrong: See my comment in the PR: https://github.com/django-wiki/django-wiki/pull/772#issuecomment-363411536

**Comment by georgekpg** [comment]
@benjaoming, if that changes in initial migration where not intended to reflect these three changes of models, then you should simply add the missing migration.

As I can see from sqlmigrate management command output, it will recreate three foreign keys but this will not affect any user data.

**Comment by benjaoming** [comment]
I closed the pull request, see the final comments.

Would rather want to restore the original behavior. The warning of missing migrations will also go away in this case.

**Comment by benjaoming** [comment]
Fixed and released in 0.3.1 -- feedback appreciated :)
