### ISSUE TITLE
A user must have a default settings object

### ISSUE THREAD

**Issue by daicoolb** [django-wiki/django-wiki#782]
what is this problem ?

Request Method: | POST
-- | --
http://www.daicoolb.ml/_plugin/notifications/
1.10.8
ValueError
A user must have a default settings object
/usr/local/lib/python2.7/dist-packages/django_nyt/models.py in save, line 138
/usr/bin/python
2.7.12
['/home/ubuntu/wikipro',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/home/ubuntu/wikipro/testproject',  '/home/ubuntu/wikipro']
Thu, 15 Feb 2018 02:04:38 +0800

**Comment by daicoolb** [comment]
At the same time , I find other users can use the notification function , only the "admin" user can not use this function correctly ? can anybody know why ?

**Comment by benjaoming** [comment]
Hi @daicoolb 

This is a support request, please do not post these as issues.

**Comment by benjaoming** [comment]
Ref: https://github.com/django-wiki/django-wiki/issues/765

**Comment by daicoolb** [comment]
@benjaoming , I have seen your reference , my problem is how to use the command to avoid this question ? can you show how to use it correctly ?
