### ISSUE TITLE
how to make the wiki be adapted with Android and IOS's website?

### ISSUE THREAD

**Issue by daicoolb** [django-wiki/django-wiki#783]
I find the display template will not be adapted with Android and IOS's website. Can anybody give a solution to make it be adapted with Android, IOS and PC's website ?

**Comment by benjaoming** [comment]
I already told you in #782 that Github issues are not for support questions.

![image](https://user-images.githubusercontent.com/374612/36302630-6918a4ec-1309-11e8-89b3-1a611cdf9cb7.png)

**Comment by daicoolb** [comment]
Sorry
