### ISSUE TITLE
Factor out wiki.core.compat

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#796]
If necessary, use `wiki.compat` instead

https://github.com/django-wiki/django-wiki/blob/master/src/wiki/core/compat.py

CC: @rsalmaso

**Comment by rsalmaso** [comment]
You want to move wiki.core.compat to wiki.compat?

**Comment by benjaoming** [comment]
@rsalmaso yes, no need for two `compat` modules :)

**Comment by rsalmaso** [comment]
Some cleanup in https://github.com/django-wiki/django-wiki/pull/802
