### ISSUE TITLE
WIKI_MARKDOWN_HTML_ATTRIBUTE(_WHITELIST) documentation bug 0.3.1

### ISSUE THREAD

**Issue by neic** [django-wiki/django-wiki#841]
In the [documentation for stable (0.3.1)](http://django-wiki.readthedocs.io/en/releases-0.3.1/settings.html#wiki.conf.settings.MARKDOWN_HTML_ATTRIBUTES) the variabel `WIKI_MARKDOWN_HTML_ATTRIBUTE_WHITELIST` 
 is listed as `WIKI_MARKDOWN_HTML_ATTRIBUTE`.

This was fixed for 0.4.x in dbca4ad10420736b9c88147b80f85a7239fe8166 by renaming the variable in the code to match the documentation.

This could be solved by a backport and a 0.3.2 release. If there is a stable 0.4.x release planned in the near future there is no need.

**Comment by benjaoming** [comment]
Thanks for inquiring @neic - 0.4 is by far the priority, so let's put all the efforts there :)
