### ISSUE TITLE
Not able to install on a fresh django CMS

### ISSUE THREAD

**Issue by superandrew** [django-wiki/django-wiki#867]
I configured following the docs the urls.py file like that:
```# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^', include('cms.urls')),
)

urlpatterns += [
    url(r'^notifications/', include('django_nyt.urls')),
    url(r'^wiki/', include('wiki.urls'))	
]
```

But no matter if I use '' or '^wiki/' i have this error:

```

Request Method: | GET
-- | --
http://<example.com>/en/
1.11.13
ImproperlyConfigured
The included URLconf '<module 'wiki.urls' from '/home/dh_tqhgj9/<example.com>/venv/lib/python3.6/site-packages/wiki/urls.py'>
```
My django CMS is running with passenger on dreamhost, and if I don't include the urls I can add an article from the admin page but when I save I have an error related to namespace

```

Request Method: | POST
-- | --
http://cms.officina.cc/en/admin/wiki/article/add/
1.11.13
NoReverseMatch
'wiki' is not a registered namespace
```
I must admit that right now I am a django cms noob, so maybe there is something wrong with my setup.

**Comment by benjaoming** [comment]
Dear @superandrew - please read the guidelines before posting support questions:

![image](https://user-images.githubusercontent.com/374612/40204908-6e0e3e36-5a2a-11e8-901c-2bbec2f5500a.png)

**Comment by superandrew** [comment]
dear @benjaoming  I actually followed blindly this guide https://django-wiki.readthedocs.io/en/master/installation.html twice, on a mac and on a linux machine, on a fresh django cms. So basically the issue I am reporting here refers to what I consider to be a documentation that can be improved. I will ask for help on IRC, hope to see you there :)

**Comment by superandrew** [comment]
(I think) the problem was related to the wiki version being installed with version 0.3 instead of 0.4a4

**Comment by benjaoming** [comment]
@superandrew thanks for sharing your experience - yes that sounds like the explanation since the default namespace has just been added, and thus the instructions for adding to the urlconf are different:

https://django-wiki.readthedocs.io/en/releases-0.3.1/installation.html#include-urlpatterns
