### ISSUE TITLE
multiple inline-images in markdown not show

### ISSUE THREAD

**Issue by realli** [django-wiki/django-wiki#868]
Hi, I have this issue when I want to insert a Image column in table, Insert multiple image within table causing some image not show.

Screenshots:

![default](https://user-images.githubusercontent.com/3313107/40520277-879b54d8-5ff7-11e8-871b-0b88601a20cc.png)
![default](https://user-images.githubusercontent.com/3313107/40520284-9756d17c-5ff7-11e8-8e17-94762946f204.png)

**Comment by Steckelfisch** [comment]
![django-wiki-issue-868-change-view](https://user-images.githubusercontent.com/529551/78030113-e2a97600-7361-11ea-8b2d-9cde63c5809d.jpg)


![django-wiki-issue-868](https://user-images.githubusercontent.com/529551/78029863-88101a00-7361-11ea-87b4-e19d725e7ab8.jpg)

**Comment by Steckelfisch** [comment]
I can not reproduce.
Django: 3.0.4
Markdown: 3.1.1

**Comment by Steckelfisch** [comment]
this is with two images, with only one image I had six versions displayed

**Comment by benjaoming** [comment]
Thanks for investigating @Steckelfisch - The markdown library was updated since this issue was filed, so likely it was fixed upstream.

The Linux Nutella glass made me happy :)
