### ISSUE TITLE
Issue with S3 and cached images

### ISSUE THREAD

**Issue by superandrew** [django-wiki/django-wiki#873]
I am not sure how to recreate this problem, but it is pretty sistematic both in development and in production, and I think it is a bug in how S3 cache is handled.

When I add an image, I can see it in the article. However, after a while image disappears, because it is not linked on S3/media folder but in S3/cache folder and that folder is probably invalidated from time to time (or maybe by django itself, I am not sure).

@benjaoming if there is some inspection or you have idea on somewhere to take a look at, I'd be happy to help

**Comment by benjaoming** [comment]
@superandrew is this still valid?
