### ISSUE TITLE
Special block to extend CSS with addtoblock

### ISSUE THREAD

**Issue by alsroot** [django-wiki/django-wiki#876]
It would be handy to have particular block to add `{% addtoblock "css" %}` instructions in an extending template (which is a sekizai [restriction](http://django-sekizai.readthedocs.io/en/latest/#restrictions)) instead of using any first available to make template code more obvious.

Actually the same for "js" sekizai block.

**Comment by benjaoming** [comment]
@alsroot thanks for the report -- sorry, I don't quite understand what you mean. Can you add some example code to illustrate the problem?

**Comment by benjaoming** [comment]
> I'm overriding the `wiki_body` block which might remain empty afterwards.

You can add `{{ block.super }}`:

```
{% block wiki_body %}
  {% addtoblock "css" %}
    <link rel="stylesheet" href="{% static 'myapp/style.css' %}" />
  {% endaddtoblock %}
  {{ block.super }}
{% endblock %}
```

I would think that the case of needing to use `addtoblock` in a template without blocks is perhaps a bit narrow?

Adding a `wiki_base` block, doesn't that just prolong the issue? Someone will request `wiki_base_base` for the same reasons :)

I would probably just refer to using `block.super` and not change anything. Please let me know if that works for you...

**Comment by alsroot** [comment]
Thanks for the `block.super` hint.
Well, extending page-level CSS stuff in an arbitrary html block still sounds not so straightforward.
But yes, thats up to django-wiki devs anyway.

**Comment by benjaoming** [comment]
Heh, I don't think that everything in templates is about looking for the most perfectly beautiful solution.. in a way, it is also front-end territory and subject to dangers of growing complex and ugly :) In this case, I think it's fine... you don't wanna know the ways I've modded django-admin :D
