### ISSUE TITLE
why cannot create a catalog？

### ISSUE THREAD

**Issue by jake2009** [django-wiki/django-wiki#879]
not have a catalog is very not convenient。

markdown also have a catalog

**Comment by benjaoming** [comment]
Thanks for opening an issue.

Sorry, I am not able to understand this issue. If you are not a native English speaker, please consider writing an understandable issue description in your own language, and have Google Translate convert it to English.

**Comment by jake2009** [comment]
I mean the wiki cannot create a catalog

**Comment by jake2009** [comment]
I am sorry about My poor English...

**Comment by jake2009** [comment]
![default](https://user-images.githubusercontent.com/14817761/42141377-5acb53ac-7ddb-11e8-96a5-0a84e3b8f64c.png)
May be other way？
if a wiki is empty than show all articles in this level

**Comment by nschneid** [comment]
@jake2009 by "catalog" do you mean a table of contents/list of articles?

**Comment by jake2009** [comment]
![default](https://user-images.githubusercontent.com/14817761/42202871-997195d6-7ecf-11e8-843b-c6e67a86d3fe.png)
there is catalog.

I mean directory of os。

If you open a catalog，it show table of contents/list of articles

**Comment by benjaoming** [comment]
Yes, what @neic says seems to answer the question :)

@jake2009 thanks for asking, good luck with the wiki :)

**Comment by jake2009** [comment]
thank u very much
