### ISSUE TITLE
Can Wiki work with SITE_ID = None?

### ISSUE THREAD

**Issue by flaiming** [django-wiki/django-wiki#888]
Hi, does django-wiki works on Django instance with multiple sites, which means that SITE_ID is set to None? So far I was unable to make it work with this setting - fails on ``Site.objects.get_current()``

Only solution I currently see is to replace ``Site.objects.get_current()`` everywhere in django-wiki code to ``get_current_site`` shortcut https://docs.djangoproject.com/en/1.11/ref/contrib/sites/#get-current-site-shortcut .

**Comment by benjaoming** [comment]
You are the first that I hear from having multiple sites using the new pattern.

You are most welcome to PR the refactor to `get_current_site`!

**Comment by flaiming** [comment]
Well, turns out that I don't really need multisite functionality after all :) Therefore closing.
