### ISSUE TITLE
Image tags are replaced inside <code>

### ISSUE THREAD

**Issue by citxx** [django-wiki/django-wiki#899]
If you put an image tag inside backticks it gets replaced with an image, but probably shouldn't. Example: `` `[image:47 size:large]` ``

**Comment by benjaoming** [comment]
I think this might be fixed by #896 - if you have time, you could give input to @Mortal about the PR? It's just a few days old.

**Comment by Mortal** [comment]
Agreed - I'm working on a fix for this. The issue is that parsing of [image...] happens in preprocessing, before backticks are parsed. However, if I recall correctly, the image tag allows adding a caption afterwards, which is a bit tricky to refactor into a so-called inline processor.

**Comment by Mortal** [comment]
This issue is now fixed by #896.
