### ISSUE TITLE
[Bug] NotImplemented is not an exception

### ISSUE THREAD

**Issue by cbsteh** [django-wiki/django-wiki#911]
https://github.com/django-wiki/django-wiki/blob/a144a3110cc688d796895aa1caddc4db1a4b62c6/src/wiki/plugins/images/models.py#L122

I think this is a bug as 'NotImplemented" is not an exception but a singleton. Delete lines 120-124?

[Docs](https://docs.python.org/3.6/library/constants.html#NotImplemented)

**Comment by benjaoming** [comment]
Thanks for reporting this! It would seem to have broken image deletion entirely, this really needs testing.
