### ISSUE TITLE
"Back to article" button links to itself on protected articles

### ISSUE THREAD

**Issue by duvholt** [django-wiki/django-wiki#914]
It works like expected on special pages like `_create`, but not on wiki articles the user doesn't have access to. 
For example https://demo.django.wiki/HiddenArticle/ links to `/HiddenArticle/`. 
It should probably link to `../` or not display the back button if that doesn't make sense.

**Comment by benjaoming** [comment]
I get the login page? How does the "permission denied" thing arise?

**Comment by duvholt** [comment]
Ah, forgot to include that. 
You need to login as a user without access to the page. For example the `test` user with the password `test`.
