### ISSUE TITLE
sekizai error python 3.6

### ISSUE THREAD

**Issue by teury** [django-wiki/django-wiki#922]
![1](https://user-images.githubusercontent.com/5114048/47404817-c0e3a280-d71c-11e8-9708-51b25883adfc.png)
![2](https://user-images.githubusercontent.com/5114048/47404822-c50fc000-d71c-11e8-8cb3-8e031523f04a.png)

It is to report what looks like an error in python 3.6
sekizai, has stopped updating, which is a bad idea to use this long-term dependency.

**Comment by dexbleeker** [comment]
I'm also having this issue. `WIKI_MESSAGE_TAG_CSS_CLASS` is unmodified.

**Comment by teury** [comment]
I'm using version 0.4.x, unmodified.

This error occurs when an alert message is triggered.

{% wiki-messages %}

**Comment by benjaoming** [comment]
@teury what's the output from running this?

```
python manage.py shell
from django.conf import settings
print(settings.MESSAGE_TAGS)
```

**Comment by teury** [comment]
@benjaoming 
**Shell**
{10: 'alert-info', 20: 'alert-info', 25: 'alert-success', 30: 'alert-warning', 40: 'alert-danger'}

Everything works correctly  ##cc9c741
