### ISSUE TITLE
No subscript support for editor?

### ISSUE THREAD

**Issue by cbsteh** [django-wiki/django-wiki#923]
I noticed the editor supports superscripts such as when I enclosed text within the `<sup></sup>` tags but using the subscript tags `<sub></sub>` do not show the enclosed text in subscript. Instead, the subscript tags themselves get displayed along with the enclosed text.

At first, I thought it was something I did in my project to mess things up, but testing this on your demo Wiki page produces the same result.

Any idea how to get the editor to support subscripts as well? I've tried the third-party extension subscript plugin -- but same outcome.

Thank you.

**Comment by benjaoming** [comment]
Hi!

We use python-markdown to parse and render the markdown. This has nothing to do with the editor.

So in the Markdown specification, there is unfortunately no mentioning of `<sub>` or any alternatives.

The right things to do is:

1) Get an extension to work
2) Get involved in Common Mark. They want to finalize specs and parsers for an improved version of Markdown. I would hope that the wiki would transition to this. Here is some old discussion from 2014: https://talk.commonmark.org/t/why-there-is-no-syntax-for-subscript-and-supscript/586

I hope you figure it out. What do you need to write as a subscript?

**Comment by cbsteh** [comment]
Seems way too much trouble just to implement the subscript tags. It is not a major issue for me. I raised this issue because it is peculiar that one would support superscripts but not subscripts. I just wanted an option for my users to enter subscripts, such as writing down CO2, H2O, NO2, and CH4.

Anyway, thanks for the feedback, and great job with this wiki.

**Comment by cbsteh** [comment]
I am opening this issue just long enough to report a workaround that allows django-wiki to render correctly valid HTML tags such as `<sub></sub>`, `<ins></ins>`, and `<del></del>`, as well as custom HTML tags deployed by some [third-party markdown extensions](https://github.com/Python-Markdown/markdown/wiki/third-party-extensions). 

Make a copy of `render.html` found in `wiki\templates\wiki\includes\`, and place this copy in your project. Modify the first few lines of this file as follows:

```
{% load wiki_tags i18n cache sekizai_tags static %}
{% load fixtags %}    <!-- new --> 

{% addtoblock "js" %}
  <script type="text/javascript" src="{% static "wiki/js/article.js" %}"></script>
{% endaddtoblock %}

<div class="wiki-article">
  {% autoescape off %}{% fixtags content|default:"" %}{% endautoescape %}   <!-- new -->
</div>
...
```

Create a custom template tag in a new file called `fixtag.py`:

```
from django import template

register = template.Library()

@register.simple_tag
def fixtags(content):
    tags = {
        '&lt;sub&gt;': '<sub>',
        '&lt;/sub&gt;': '</sub>',
        '&lt;ins&gt;': '<ins>',
        '&lt;/ins&gt;': '</ins>',
        '&lt;del&gt;': '<del>',
        '&lt;/del&gt;': '</del>',
    }
    for old, new in tags.items():
        content = content.replace(old, new)
    return content
```

I am using this workaround for displaying text in subscripts, underlines, and strikethroughs. Again, I am not sure if this is the best way, but it fits my purpose.

**Comment by benjaoming** [comment]
Thanks for sharing the work-around @cbsteh 

While it's definitely not the correct way of fixing the issue, it may be valuable to others.

What's the issue about making the `markdown_subscript_extension` work?

**Comment by cbsteh** [comment]
The problem is not with any of the extensions because the problem can be replicated without any of the them installed. For some reason, unrecognized HTML tags are rendered with `&lt;` and `&gt;` for angle brackets `<` and `>`, respectively.

So, if I was to directly write `H<sub>2</sub>O`, it will be stored correctly as `H<sub>2</sub>O`, but when rendered to a HTML page, it is converted as `H&lt;sub&gt;2&lt;/sub&gt;O`. The same issue occurs for other valid HTML tags such as `<ins></ins>` and `<del></del>` -- but not for `<sup></sup>`.

**Comment by benjaoming** [comment]
> For some reason

Ah no, in this case, try setting `WIKI_MARKDOWN_HTML_WHITELIST = ["sub", "sup", "del", "ins"]` in your project's settings - does that work?

**Comment by benjaoming** [comment]
https://django-wiki.readthedocs.io/en/master/settings.html#wiki.conf.settings.MARKDOWN_HTML_WHITELIST

**Comment by cbsteh** [comment]
Great! That'll do!
