### ISSUE TITLE
Allow opening, rather than downloading, of attachments

### ISSUE THREAD

**Issue by nicolazilio** [django-wiki/django-wiki#933]
It'd be awesome to have the option to open an attachment, rather than download it, which is the current default behaviour.

This would be particularly useful, for example, for pdf docs.

**Comment by benjaoming** [comment]
Is this only useful for PDFs? And is it because you want to use your browser's inline PDF viewer?

You can investigate in `wiki.core.http` if `send_file` can be configured via some mimetype mapping to send a different `Content-Disposition` header. Otherwise, I would suggest checking out if you can install `django-sendfile` and somehow configure it.

**Comment by nicolazilio** [comment]
Yes exactly.

I will try overriding `send_file` like you pointed out.

Thanks a lot for the suggestion

**Comment by benjaoming** [comment]
PRs for improved configurability are always welcome :)

**Comment by benjaoming** [comment]
Okay, closing this as people can probably figure out something... or someone is always welcome with a PR.

**Comment by nicolazilio** [comment]
Ah, I forgot about this, sorry! I solved it quite easily, by changing the last few lines of send_file 

    if filename:
        filename_escaped = filepath_to_uri(filename)
        response["Content-Disposition"] = "attachment; filename=%s" % filename_escaped

to

    if filename:
        filename_escaped = filepath_to_uri(filename)
        if 'pdf' in mimetype.lower():
            response["Content-Disposition"] = "inline; filename=%s" % filename_escaped
        else:
            response["Content-Disposition"] = "attachment; filename=%s" % filename_escaped

**Comment by benjaoming** [comment]
That seems fairly simple, don't mind adding this if you open a PR @nicolazilio :)
