### ISSUE TITLE
Safari on iOS gives TypeError in modal.html

### ISSUE THREAD

**Issue by henrikhorluck** [django-wiki/django-wiki#952]
Going to an edit a page in Safari on iOS gives a TypeError when evaluating `ui.element`

Error message: `undefined is not an object (evaluating 'ui.element')`

Steps: 
1. Create Django-wiki-user
2. Log in with said user
3. Go to an editable page
4. Click edit
5. Scroll down
6. Observe TypeError in console, two at a time, repeating as you scroll

Example console:
<img width="803" alt="Screenshot 2019-05-02 at 11 51 33" src="https://user-images.githubusercontent.com/36937807/57067976-ba884180-6cd0-11e9-827c-f11cc65b2846.png">

https://github.com/django-wiki/django-wiki/blob/621f6085c3aa029c4469c7ad0c2aa70f15e5f407/src/wiki/templates/wiki/includes/modals.html#L14

I have confirmed it replicates 100% on django-wiki 0.4.1 and 0.4.4. I have not been able to replicate in Safari for macOS, Chrome or Firefox.

**Comment by benjaoming** [comment]
Am sorry, but unless someone sorts out a PR for the current Bootstrap stuff, this won't be fixed. I think the project should work towards a Bootstrap upgrade etc.
