### ISSUE TITLE
Django 2.2.x coverage

### ISSUE THREAD

**Issue by davidzwa** [django-wiki/django-wiki#954]
**First things first**
Great library, much love! Took us 5 minutes to setup. Super nice.

**Request**
Upgrade django coverage/support to >=2.2.x
There are dependency resolve conflicts which do not allow me to install beyond 2.1.x. I can get more detail about the conflicts, but PyCharm is pretty vague about it right now.

**Why?**
There is a vulnerability in django admin, which was solved after 2.1.9 

**I got this warning from github:**
Django vulnerability found in Pipfile.lock yesterday
Remediation
Upgrade django to version 2.1.9 or later.

**Comment by benjaoming** [comment]
You are welcome to help out here: https://github.com/django-wiki/django-wiki/pull/951

**Comment by benjaoming** [comment]
Hi @davidzwa - thanks for the report

Does it mean that you are running on Django 2.2? We are trying to figure out whether the test failures in #951 are because of issues with Travis or actual issues with Django 2.2 support.

**Comment by davidzwa** [comment]
Ah I just saw 2.1.9 runs for us locally, so the vulnerability can at least be avoided.

About helping, you seem to have CI trouble?

**Comment by benjaoming** [comment]
You can see in the conversation in #951 what the unclarity is: Tests running locally, but SQLite SQL errors on Travis.

**Comment by davidzwa** [comment]
I am considering writing an Angular frontend (headless) to this wiki. So I will try and get into it. Closing this issue since it is resolved for 1.9.1

**Comment by benjaoming** [comment]
@davidzwa if it takes plugins into account, it would be nice - but the plugin system is currently designed only with normal views in mind, so not sure how DRF would fit in. Of course, most of the responsibility could be delegated to plugins, such that they are individually responsible for providing DRF.

**Comment by davidzwa** [comment]
Still interested! So I will first get more familiar with Django, DRF, Marshmallow (and forking/PR'ing) and then get back when our PWA is up and running. I will make a separate issue.

**Comment by davidzwa** [comment]
Reopening, because right now I have to use `pipenv install --skip-lock` (django 2.2.4)

**Comment by benjaoming** [comment]
What's the exact issue here?

There is a cronjob running tests periodically. The latests tests ran yesterday, they also have Django 2.2: https://travis-ci.org/django-wiki/django-wiki/jobs/574874476

```
py35-django22 installed: attrs==19.1.0,beautifulsoup4==4.8.0,bleach==2.1.4,coverage==4.5.4,cssselect==1.1.0,Django==2.2.4,django-classy-tags==0.9.0,django-functest==1.0.4,django-js-asset==1.2.2,django-mptt==0.9.1,django-nyt==1.1.3,django-sekizai==1.0.0,django-webtest==1.9.7,EasyProcess==0.2.7,furl==2.0.0,html5lib==1.0.1,lxml==4.4.1,Markdown==3.0.1,orderedmultidict==1.0.1,Pillow==6.1.0,pluggy==0.6.0,py==1.8.0,pyquery==1.4.0,pytest==3.4.2,pytest-cov==2.4.0,pytest-django==3.1.2,pytest-pythonpath==0.7.3,pytz==2019.2,PyVirtualDisplay==0.2.4,selenium==3.141.0,six==1.12.0,sorl-thumbnail==12.5.0,soupsieve==1.9.3,sqlparse==0.3.0,urllib3==1.25.3,waitress==1.3.0,webencodings==0.5.1,WebOb==1.8.5,WebTest==2.0.33,wiki==0.5.dev20190717135042
```

**Comment by davidzwa** [comment]
I think the dependencies didnt resolve @benjaoming, will look into it soon as it blocks our project's django from updating.

**Comment by benjaoming** [comment]
@davidzwa have you pinned all your dependencies? In that case, I think pip should tell you which package is incompatible. If you haven't pinned a certain package, pip might complain that the installed one isn't compatible and you have to run `pip install -r requirements.txt --upgrade` to force unpinned packages to be upgraded.
