### ISSUE TITLE
[Future, WIP] Build DRF/headless capable wiki.

### ISSUE THREAD

**Issue by davidzwa** [django-wiki/django-wiki#955]
Introduce headless Wiki for integration into Vue/Angular/React/Svelte.

More specific roadmap added later.

- Decide on REST API framework (https://voidfiles.github.io/python-serialization-benchmark/, https://github.com/lyft/toasted-marshmallow)
- Construct Plugin and dependencies
- Analyze, discuss and setup list of required API endpoints
- Create viewsets and schema's for Article, Tree (basics)
- Create tests for viewsets (CRUD, hidden fields)
- Analyzing current Forms/Validation and re-usable Code
- Create serializable endpoints Wiki
- Allow other plugins to hook into endpoints

**Comment by benjaoming** [comment]
@davidzwa all of this is super interesting - do you have any updates on this work?

**Comment by davidzwa** [comment]
My time is limited due to other commitments. What do you think about the marshmallow framework? I've worked with it over the summer, it has some quirks but works very nice and just got into version 3.

**Comment by benjaoming** [comment]
@davidzwa indeed! solving a bug or adding tests to uncovered code could be a good start

> Im also up to any other framework, as long as it is scalable and has LTS.

I don't have preferences, the only thing I think might be a good idea (if you agree?) would be to make RESTful APIs optional -- say by writing a plugin w/ an extra dependency on such framework.

**Comment by davidzwa** [comment]
Nice, if you have some low-hanging fruit, I'd be up for taking a look and getting familiar.

Oh, bit of a warning, TL;DR ahead.

_About the API idea_
So, if I'm correct, it would have your preference to make the API optional? That's perfectly possible, as long as it is maintained! So far I've made a django MVC based site and later added a DRF+marshmallow (3.0.0) based API. 
I had to write Schema's for all models, which was the not a lot of work but felt redundant. My experience lies with .NET/.NET Core as well, and re-usability, interfacing, extension and **smart decorators/attributes** is the standard over there. 
In contrast to migrating C#, implementing validation in DRF and marshmallow, and passing the right validation errors was a bit of a hassle and real CRUD actions was the most work. When the models needed to change, so did the Schema's and Validation functions. In our django-wiki case, we should focus on boiler-plate and re-using existing code so we maintain 1 package, not 2.

_Re-usability_
[My experience](https://github.com/studentenhuisDS4/ds4reboot/tree/develop/user) was that I was not able to shovel a lot of old code in the MVC-based approach to the DRF (let alone marshmallow) framework. The primary cause of that was bad code design (all Application+Business+Data code was in each Views.py file). We'd really need to take a close look at what hooks into the models/db-context you use. If you have good pointers to that, that'd save me a bit of looking around. If we can find something to re-use or shape the existing code into something re-usable.

The big issue is not doing it once, it's keeping it maintained with the wiki. So we'd need to carefully think about a smart way of keeping models and views-code in sync with the API plugin we're thinking of.

Hey you made it to the end! :)

**Comment by benjaoming** [comment]
> Nice, if you have some low-hanging fruit, I'd be up for taking a look and getting familiar.

There are roughly 18% of the codebase that isn't covered by tests, using this report could be a way to quickly discover something uncovered: https://codecov.io/gh/django-wiki/django-wiki/tree/master/src/wiki

There are 2 open [easy-picking](https://github.com/django-wiki/django-wiki/issues?q=is%3Aissue+is%3Aopen+label%3Aeasy-pickings) -- but I think part of the missing maintenance would be to use some more labels in the repo to formulate and discover those low-hanging fruits :)

> That's perfectly possible, as long as it is maintained!

The core plugins are maintained, insofar as there are tests for them :) I just removed a dajngo-haystack plugin that had no tests and surprise \o/ didn't work.

**Comment by benjaoming** [comment]
> I had to write Schema's for all models, which was the not a lot of work but felt redundant. 

It's clear that APIs won't write themselves, but they should maintain themselves as the models gradually change?

In regards to the MVC stuff, I'm not sure what to say. It seems there aren't any design principles that will tell you exact answers :) I think that for django-wiki's part, it should ship a nice default UI, but it everything should be very sensible to overwritten views, UIs etc.. and now also APIs!

I think this does imply bringing back some of the "fat models" ideas, but it can certainly also be about adding logic into managers and moving those out of the models to separate modules.

Keeping things slim and easy to unit test also seems like a good idea, as I can see that the tests are slowly growing their own bit of complexity.

I'm aware that this answer doesn't provide anything useful. But given that we have some specific choices laid out, I'm sure that we can define and pick nice options together :+1: 

I was reading this and chuckling a bit about confusion and no answers... https://codeinthehole.com/lists/why-your-models-are-fat/

**Comment by davidzwa** [comment]
It just hit me: if people use the wiki API plugin, it is their responsibility to use the endpoints properly and extend them in a suitable way. Would you like to include an example application which consumes the API to show them what the basic interfaces are? 
I think it could show the developer what our intended UI is with the wiki, so they have bit of an educated guess (or even a head-start). **Park this idea, for later.** :)

> I think this does imply bringing back some of the "fat models" ideas, but it can certainly also be about adding logic into managers and moving those out of the models to separate modules.

So, there's model Managers and managers like repositories. I think that you mean a manager like a repository which can abstract away a model? (Just like [your managers.py](https://github.com/django-wiki/django-wiki/blob/master/src/wiki/managers.py) I agree/prefer to split the model code into different managers as currently its one big file. 

So what kind of base endpoints would we need? 
- Article CRUD Endpoint (... split into smaller pieces?)
- Authentication (JWT)
- Role/permission CRUD Endpoint
- URL/Tree Query Endpoint
- Notification CRUD 
- (Push Notification CRUD, optional. I really like FCM haha)
- ([Swagger](https://github.com/axnsan12/drf-yasg), optional)
- ...

**Comment by duvholt** [comment]
I would just like to say that I think this is a great idea!
Writing websites using single page application frameworks like Vue, React, etc has gotten really popular and I don't see why django-wiki couldn't be used as just an API for wiki functionality in an existing SPA app. 

If these hypothetical APIs and an example application are created I would suggest adding some end-to-end tests to make sure basic functionality still works in the future.

**Comment by davidzwa** [comment]
> So what kind of base endpoints would we need?
> 
> * Article CRUD Endpoint (... split into smaller pieces?)
> * Authentication (JWT)
> * Role/permission CRUD Endpoint
> * URL/Tree Query Endpoint
> * Notification CRUD
> * (Push Notification CRUD, optional. I really like FCM haha)
> * ([Swagger](https://github.com/axnsan12/drf-yasg), optional)
> * ...

Starting on a first attempt now, so input would be great!

**Comment by davidzwa** [comment]
@benjaoming I need two packages. How do I add them as plugin-only?
- DRF
- Marshmallow

**Comment by benjaoming** [comment]
> I need two packages. How do I add them as plugin-only?

This can be documented for now but added as test dependencies (so that it will work when testing) ?

So for instance, same as for `django-sendfile` or the Haystack plugin (albeit it got deleted).

Another way would be to add it as `extras_requirements` in setup.py and make it installable with a special target, for instance `pip install "wiki[drf]"`. Try for instance `pip install -e .[devel]`

**Comment by davidzwa** [comment]
Exactly what I was looking for! Very nice solution. How do we provide the developer using the wiki with feedback that the module is not installed?

**Comment by benjaoming** [comment]
> How do we provide the developer using the wiki with feedback that the module is not installed?

That would be here: https://github.com/django-wiki/django-wiki/blob/master/src/wiki/checks.py

Something like:

```
if "wiki.plugins.rest_api" in settings.INSTALLED_APPS:
    try:
        import required_module
    except ImportError:
        ...
```

**Comment by davidzwa** [comment]
This is getting more awesome by the minute!

**Comment by benjaoming** [comment]
It's part of the Django checks framework, docs are here: https://docs.djangoproject.com/en/3.0/ref/checks/

**Comment by davidzwa** [comment]
Soon more time to continue this!

**Comment by aguedob** [comment]
Hi! Any update on this feature? I'm implementing a RN app and would like using Django-wiki in headless mode (DRF). I will be happy contributing!

**Comment by davidzwa** [comment]
@aguedob Im not involved in Django anymore at this moment. Please consider this issue free to be picked up in discussion with @benjaoming

**Comment by aguedob** [comment]
Hi again. Quick question (maybe for @benjaoming): Is there further documentation about implementing new plugins apart from the source code comments?  I see three kind of plugins: SimplePlugin, RevisionPlugin and ReusablePlugin, but none of those types matches covers a scenario like implementing a restful interface.

**Comment by davidzwa** [comment]
Interesting topic and definitely something I was also wondering about back then. 

One question I had back then was whether the view-based API for this project should be transformed into a REST API instead so that there wouldn't be two projects to keep in sync.
This requires the frontend to be converted with Javascript and API-calls (axios?). I've found this to be very nice in combination with webpack so that the views can still be rendered as they are right now, but instead the API would now do all CRUD operations.

Think about it ;)

**Comment by aguedob** [comment]
That's an interesting approach, but sounds massive. My application will need a React Native front for mobiles and also a web based one, that I was planning to implement it in React (for reusability reasons). I will start forking this project to work on this approach. I will keep this thread updated if I made some progress. So summarising: 

- Replace current views by DRF for the RESTful ApiViews and a ReactJS front (axios was also my choice for operations)
- JWT authentication

Thoughts?

**Comment by davidzwa** [comment]
- Dont forget CORS setup if its missing. 
- You could consider Marshmallow (if you like it) or extend DRF .
- If plugins is the route, consider how you're going to register the urls as a starting point.

**Comment by benjaoming** [comment]
@aguedob

Unfortunately, the basic pieces for plugin development don't have anything for APIs -- but they also would support any kind of API you'd choose to put -- as @davidzwa mentions, you can route anything in the plugin's urlpatterns, which is hopefully sufficient.

If you go the plugin-way (which is a great way!), then don't hesitate to open any separate PRs if you need basic plugin structures adapted for new scenarios. The current basic plugin models were build in a time when REST APIs didn't seem as obvious as they are today.

**Comment by davidzwa** [comment]
Might consider looking at how OctoPrint sets up plugins, because there it is super tightly integrated (yes in Flask, but still).
I think they created a BluePrintMixin to register the urls using REST API decorators
