### ISSUE TITLE
Strange error by migrate: Couldn't import Django.

### ISSUE THREAD

**Issue by catafest** [django-wiki/django-wiki#956]
I try to used the django-wiki see (google groups https://groups.google.com/forum/#!topic/django-wiki/Q7AZpSx2VF4):

Requirement already satisfied: wiki in c:\python373\lib\site-packages (0.4.4)
Requirement already satisfied: django-nyt<1.2,>=1.1.1 in c:\python373\lib\site-packages (from wiki) (1.1.3)
Requirement already satisfied: django-mptt<0.10,>=0.9 in c:\python373\lib\site-packages (from wiki) (0.9.1)
Requirement already satisfied: bleach<2.2,>=2.1 in c:\python373\lib\site-packages (from wiki) (2.1.4)
Requirement already satisfied: django-sekizai>=0.10 in c:\python373\lib\site-packages (from wiki) (1.0.0)
Requirement already satisfied: Django<2.2,>=1.11 in c:\python373\lib\site-packages (from wiki) (2.1.10)
Requirement already satisfied: sorl-thumbnail<13,>=12 in c:\python373\lib\site-packages (from wiki) (12.5.0)
Requirement already satisfied: Pillow in c:\python373\lib\site-packages (from wiki) (6.1.0)
Requirement already satisfied: Markdown<2.7,>=2.6 in c:\python373\lib\site-packages (from wiki) (2.6.11)
Requirement already satisfied: django-js-asset in c:\python373\lib\site-packages (from django-mptt<0.10,>=0.9->wiki) (1.2.2)
Requirement already satisfied: html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre in c:\python373\lib\site-packages (from bleach<2.2,>=2.1->wiki) (1.0.1)
Requirement already satisfied: six in c:\python373\lib\site-packages (from bleach<2.2,>=2.1->wiki) (1.12.0)
Requirement already satisfied: django-classy-tags>=0.3.1 in c:\python373\lib\site-packages (from django-sekizai>=0.10->wiki) (0.9.0)
Requirement already satisfied: pytz in c:\python373\lib\site-packages (from Django<2.2,>=1.11->wiki) (2019.1)
Requirement already satisfied: webencodings in c:\python373\lib\site-packages (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach<2.2,>=2.1->wiki) (0.5.1)

The error is:

(venv) C:\Python373\django_wiki_001>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available o
n your PYTHONPATH environment variable? Did you forget to activate a virtual env
ironment?

**Comment by benjaoming** [comment]
Hi, you have posted to the mailing list. That's the correct way, so thanks for doing that. Closing this, as it's a support request.
