### ISSUE TITLE
Inquiry into its features 

### ISSUE THREAD

**Issue by DonaldTsang** [django-wiki/django-wiki#958]
1. Does this Wiki have branching/forking for mirrors?
2. Does this Wiki have user permissions and management?
3. Does this Wiki have cross-links for pages to link without URL?
4. Does this Wiki have forum/chats for page discussion?
5. Does this Wiki have page versioning?
6. Does this Wiki have page categorization?

**Comment by nschneid** [comment]
User permissions, cross-links, versioning—yes.

The others do not have built-in support that I know of, and would require customization. For my site I built a plugin that uses [django-categories](https://readthedocs.org/projects/django-categories/) for page categorization.

**Comment by DonaldTsang** [comment]
@nschneid So branching/forking, forum/chats and page categorization (like the ones in Wikipedia) all needs plugins? So Django-Wiki is a few hairs short of being the next MediaWiki?

**Comment by nschneid** [comment]
As far as I know. Django-wiki is a fairly small project (in terms of numbers of contributors and users, size/complexity of the codebase, and number of features), unlike MediaWiki, which is massive.

Based on [this](https://github.com/django-wiki/django-wiki/graphs/contributors), it appears @benjaoming is the only main developer, though others have been involved at various points.

For my Markdown-centric project it was a great starting point, though adding more structured data (including categories) has required a lot of customization.

**Comment by DonaldTsang** [comment]
@nschneid well except MediaWiki, there is Tikiwiki and PmWiki for PHP and Wiki.JS for JS.

**Comment by benjaoming** [comment]
Yes, there are soooo many wikis out there. The choice of django-wiki should be based on one's intention to use Django. I hope this is reflected in the README, but feel free to comment on whether that README actually serve's its purpose.

I am currently more of a "maintainer" than a "developer", but anyone should feel very safe contributing to this project, we are people happy to help getting PRs merged.

**Comment by benjaoming** [comment]
Ah yes, one more thing: Maybe you are asking because the Demo link was broken? This was juuuuust fixed in #957 - demo is now at https://demo.django-wiki.org/

**Comment by DonaldTsang** [comment]
@benjaoming It is just that PHP is harder to script cleanly when compared to Python (JS/TS is another issue), which is why this repo is an option in the first place.

**Comment by benjaoming** [comment]
@DonaldTsang Yes, the programming language and framework base is very important for the choice of a wiki, to avoid running a separate environment solely for the wiki. I hope that the questions you're asking can be answered from using the demo server?

**Comment by benjaoming** [comment]
Closing this issue, as it is not an error report nor a feature description.

Please clarify if you need something changed in the README or documentation and need this re-opened.

**Comment by DonaldTsang** [comment]
@benjaoming I would suggesting treating this as a declaration of building new features.
