### ISSUE TITLE
Moving Attachments Storage - Error

### ISSUE THREAD

**Issue by mcrichards** [django-wiki/django-wiki#959]
We are attempting to move the storage of attachments to a private S3 bucket. We want the uploaded attachment urls to point to this S3 bucket when called on by a view template. Uploading the attachments works fine, but when the view template accesses the URL, the URL is returning with the default location in the django project, and not the S3 location to which it was uploaded. Interestingly, from the Django admin, we can retrieve attachments from S3 no problem, as the URL is correct. 

We added:
"WIKI_ATTACHMENTS_STORAGE_BACKEND = 'storages.backends.s3boto3.S3Boto3Storage' " 

Here is an example of a correct path from the Django Admin: /wiki/attachments/5/727a477d80180ccbcb7feb0ca2be633a/test.txt.upload
That path correctly links to the S3 bucket at: https://sixcycle-wiki-storage.s3.amazonaws.com/wiki/attachments/5/727a477d80180ccbcb7feb0ca2be633a/test.txt.upload?AWSAccessKeyId=[key]&Signature=[sig]&Expires=[date]

Here is what we are seeing from the view template: /wiki/5/plugin/attachments/download/5/
This erroneously attempts to link to: https://wiki-stg.sixcycle.com/wiki/5/plugin/attachments/download/5/

As you can see, the pathing is incorrect in the view template. Is there another config that needs to be updated to have URLs be updated to the new S3 location, to which the files are uploaded?

Thanks in advance for any assistance.

**Comment by benjaoming** [comment]
Hi @mcrichards 

`/wiki/attachments/5/727a477d80180ccbcb7feb0ca2be633a/test.txt.upload` is a secret path, meaning that the file may be served from there, but this is not supposed to be shared to people without permissions to view it.

The path `/wiki/5/plugin/attachments/download/5/` will redirect correctly logged in users with permissions to view the file to the destination. If this is on S3, then it should provide a redirect there.

**Comment by mcrichards** [comment]
I guess the issue is then that the redirect isn't happening correctly? 

Here is a successful attachment:

![image](https://user-images.githubusercontent.com/14281220/61227489-69de8d00-a6f2-11e9-9459-5996a906d649.png)

Here is the listing for it in the Django Admin. You will note that the URL is correctly pointed to S3 (see bottom of image for full path shown when hovering over URL in "File" section of screen). Clicking this URL correctly shows the attachment on S3:

![image](https://user-images.githubusercontent.com/14281220/61228008-6b5c8500-a6f3-11e9-947c-284b3f26f2c1.png)

Here is the resulting path when the file is added to the page. Note that it is NOT pointed to S3:

![image](https://user-images.githubusercontent.com/14281220/61227925-4700a880-a6f3-11e9-8cad-8cab30d58c25.png)

And here is the resulting error when that link is clicked (this is actually from a different link than shown in the above attachments, but the result is the same):

![image](https://user-images.githubusercontent.com/14281220/61228597-93001d00-a6f4-11e9-878d-8f082c8f47e5.png)

What needs to be done to address this and get the redirect that you referred to working properly?

**Comment by benjaoming** [comment]
Hi @mcrichards

It looks like you are using `DEBUG=True` in production? Never do that. It can reveal secrets about your website that will end up getting your database stolen.

> What needs to be done to address this and get the redirect that you referred to working properly?

If you take a closer look at the screenshot with the error, there is a nifty piece of information that's great to use to copy paste the exact error:

![image](https://user-images.githubusercontent.com/374612/61297384-717a6080-a7dc-11e9-95dc-54f6dbb88cbd.png)

The error posted as a screenshot is missing a full traceback.

**Comment by mcrichards** [comment]
Hi @benjaoming,

We are not using DEBUG=True in production. 

Here is the full traceback:

Environment:


Request Method: GET
Request URL: https://wiki-stg.sixcycle.com/wiki/5/plugin/attachments/download/28/

Django Version: 1.11.6
Python Version: 3.6.7
Installed Applications:
['authtools',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_auth',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites.apps.SitesConfig',
 'django.contrib.humanize.apps.HumanizeConfig',
 'django_nyt.apps.DjangoNytConfig',
 'corsheaders',
 'mptt',
 'sekizai',
 'sorl.thumbnail',
 'storages',
 'boto3',
 'wiki',
 'wiki.plugins.attachments.apps.AttachmentsConfig',
 'wiki.plugins.images.apps.ImagesConfig',
 'wiki.plugins.links.apps.LinksConfig',
 'wiki.plugins.videos.apps.VideosConfig',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'SixcycleWiki.authentication',
 'SixcycleWiki.rest',
 'django_thumbor',
 'dashboard',
 'relationships',
 'wikiextensions']
Installed Middleware:
['django.middleware.common.CommonMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'SixcycleWiki.middleware.LoginFromCookieMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/opt/python/current/app/wiki/decorators.py" in wrapper
  154.         return func(request, article, *args, **kwargs)

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/opt/python/current/app/wiki/plugins/attachments/views.py" in dispatch
  229.         return super().dispatch(request, article, *args, **kwargs)

File "/opt/python/current/app/wiki/views/mixins.py" in dispatch
  33.         return super().dispatch(request, *args, **kwargs)

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/opt/python/current/app/wiki/plugins/attachments/views.py" in get
  237.                         self.revision.file.path,

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/db/models/fields/files.py" in path
  65.         return self.storage.path(self.name)

File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/files/storage.py" in path
  111.         raise NotImplementedError("This backend doesn't support absolute paths.")

Exception Type: NotImplementedError at /wiki/5/plugin/attachments/download/28/
Exception Value: This backend doesn't support absolute paths.

**Comment by benjaoming** [comment]
Try setting `WIKI_ATTACHMENTS_LOCAL_PATH = False` in your Django project's settings.

See: https://django-wiki.readthedocs.io/en/master/settings.html?highlight=s3#wiki.plugins.attachments.settings.USE_LOCAL_PATH
