### ISSUE TITLE
images can not displayed

### ISSUE THREAD

**Issue by zhangzq** [django-wiki/django-wiki#960]
After I uploaded images for an article, I can see them with path `./wiki/images/17/1356c08cd62d4d389d5a615680e81373/images.png`.

But when I insert to this article with `[images:5]`，the url of images is `http://domains.com/wiki/article_slug/wiki/images/17/1356c08cd62d4d389d5a615680e81373/images.png/`, which is not an image and is treated as an unexisted article.

The attachments of article works, which have similar locations and urls.

django-wiki version is 0.5.0alpha (I install from master branch)。I didn't set any PATH, everything is by default.

**Comment by benjaoming** [comment]
Hi @zhangzq 

I am afraid this is a support request, and it isn't very nice as a maintainer to have to respond to Github issues asking for support.

Please use the channels for support, as is asked in the README and advertised through the Github interface when you create an issue.

https://github.com/django-wiki/django-wiki#community
https://github.com/django-wiki/django-wiki/blob/master/SUPPORT.rst
