### ISSUE TITLE
List at WikiMatrix

### ISSUE THREAD

**Issue by splitbrain** [django-wiki/django-wiki#968]
It would be nice to have this engine listed at WikiMatrix so people looking for a wiki can find and compare its features.

See https://www.wikimatrix.org/static/new-product for details on how to add django-wiki 

Ping me if you have any questions.

**Comment by benjaoming** [comment]
Funny, I stumbled on this website quite recently but never got around to contacting them.

**Comment by benjaoming** [comment]
Thanks for encouraging this!

**Comment by splitbrain** [comment]
@benjaoming I created the entry yesterday and linked your account. You should have gotten an automated mail. Let me know if you run into any trouble.

**Comment by benjaoming** [comment]
Thanks @splitbrain - I will have to write a script and an online resource in order to generate release version and date automatically, to complete the entry. Not going to maintainer that manually :)

**Comment by benjaoming** [comment]
I don't have time to complete this. If someone else wants to provide a script, I'd be happy to host it somewhere.

If not, I'll close the issue.
