### ISSUE TITLE
Problem with Foreign Keys to auth_user and django_contenttypes

### ISSUE THREAD

**Issue by pnoziska** [django-wiki/django-wiki#969]
I have a multiple-app Django site where each app migrates to its own database and the auth/admin/contenttypes apps migrate to 'default' , allowing for a SSO/single-admin on the site.  A custom AUTH_USER_MODEL is in place.

Django models with foreign keys to external databases will not migrate.  My other apps conform to this , but models Article and ArticleForObject use foreign keys to settings.AUTH_USER_MODEL and contentypes.ContentType, respectively.

My best-available workaround appears to be to change the models to substitute CharField() attributes using a string username for User and model name for ContentType.

Do you have a better suggestion?

**Comment by benjaoming** [comment]
> Django models with foreign keys to external databases will not migrate.

Doesn't that break a heap of things?

It sounds hard to fix in a general way: Using a string for the username will break db indexing, reverse relations etc.

**Comment by benjaoming** [comment]
I'm not sure, but the issue could perhaps also be with the notifications plugin, so you could try disabling that.
