### ISSUE TITLE
re_path alised to url

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#985]
Since the cleanup in https://github.com/django-wiki/django-wiki/pull/983, we accepted to use an alias that's not desirable for the longer term.. it's a bit confusing to people that don't know the history of Django before version 2.

The issue is to use `from django.urls import re_path` and correct the code. In some places, we might be able to use just `path`.

**Comment by tomasmor42** [comment]
Can I pick this up?

**Comment by benjaoming** [comment]
Fixed in #986 - thanks for the swift initiative @tomasmor42
