### ISSUE TITLE
Default superuser

### ISSUE THREAD

**Issue by dullbananas** [django-wiki/django-wiki#987]
What is the default superuser username and password?

**Comment by dullbananas** [comment]
This has to be added to the documentation

**Comment by dullbananas** [comment]
Or how do I make the superuser

**Comment by benjaoming** [comment]
The command is `python manage.py createsuperuser`

Django-wiki uses Django. Documenting various features of Django would make the documentation very long and hard to read.

There's a tutorial on getting started with Django here: https://docs.djangoproject.com/en/2.2/intro/tutorial01/

**Comment by dullbananas** [comment]
So it's a Django-specific user?

**Comment by dullbananas** [comment]
*feature

**Comment by benjaoming** [comment]
Yes, the whole user authentication system is running on Django

**Comment by dullbananas** [comment]
*laughs in Flask*
