### ISSUE TITLE
Markdown version bump needed for rest framework

### ISSUE THREAD

**Issue by olymk2** [django-wiki/django-wiki#989]
restframework requires markdown 3.1.1 resulting in this error with restframework.

https://stackoverflow.com/questions/57479412/attributeerror-at-ordereddict-object-has-no-attribute-register-in-django-r

**Comment by benjaoming** [comment]
Thanks for filing this @olymk2 - have you investigated this? Try opening a PR with the version bump and see how the tests react.

**Comment by olymk2** [comment]
I ended up just pointing pip at master as I needed things fixed, seems its fixed in master so we probably just need a release to actually fix things
