### ISSUE TITLE
Known issue: sorl-thumbnail does not support Django 3.0

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#992]
Need to create upstream support. Here's a recipe for adding Django 3.0 for their test framework.

https://github.com/jazzband/sorl-thumbnail/commit/22ccd9781462a820f963f57018ad3dcef85053ed

There are imports in Sorl that are broken in Django 3.0:

https://github.com/jazzband/sorl-thumbnail/blob/master/sorl/thumbnail/images.py#L10

**Comment by itsthejoker** [comment]
The fix has been merged and is available, but the maintainer has not created a release yet. See here for more information: https://github.com/jazzband/sorl-thumbnail/issues/601

**Comment by benjaoming** [comment]
Still waiting for a new release.

**Comment by pallavg** [comment]
Hello - has there been any movement on getting the dependencies supported for Django 3?

**Comment by slinkymanbyday** [comment]
sorl-thumbnail 12.6.2 is on PyPI and support django 3.0+

django-mptt  has 0.11 released on PyPI and should contain DJango 3.0 support.

is there anything else blocking django 3? would like to be able to activate my wiki again on my django 3 project.

**Comment by benjaoming** [comment]
working that out @slinkymanbyday
