### ISSUE TITLE
Group hierarchy

### ISSUE THREAD

**Issue by tobast** [django-wiki/django-wiki#999]
This is more a feature request than an actual issue.

We use `django-wiki` as a wiki in our school, with both private and public parts. A common usecase we have is that we would like a group of people to have their own private wiki for eg. some event, but we would also like to grant access to another whole group of students who should have access to a broad part of the students' events wikis (eg. students union). Moreover, this group changes every year, and we'd like to keep it up to date.

What would seem smooth, from a user experience perspective, would be to have a tree-like hierarchy of groups: stating that the wiki `some event` is owned by group `some event organizers`, which includes the groups `some event organizers'19` and the group `students union`, which itself includes the group `students union'19` and `students union'20` at the present time.

This seems smoother than allowing multiple groups per sub-wiki, since if we have dozens of such events, when the students union changes, we would just have to roll the `students union` group to be composed of `students union'19` and `'20` instead of previously `'18` and `'19`, instead of having to do this change on the many sub-wikis.

The only way we can do something functionaly similar in the current setup — if I'm not mistaken — is to manually add each member of the students union to each such sub-wiki, and remove them at some later point, which is kind of painful.

I am conscious that implementing such a behavior would require a huge change in the way `django-wiki` deals with groups (unless there is some elegant approach I can't see right now), but I think that in many contexts, this would smoothen the user experience with groups.

**Comment by benjaoming** [comment]
Hi @tobast 

Have you thought about writing this group and permission administration as your own separate functionality?

I think that you can automate these needs and maintain a flat structure of groups if you write the right functions to move and replace groups?

Having group hierarchy, or groups being members of groups, would mean a difficult rewrite or permission resolution, including detection of cyclic group membership.

**Comment by tobast** [comment]
Hi,

Yes, we've thought about doing it separately, but I thought that this feature would be actually meaningful for many `django-wiki` users, so I thought I'd reach out for you before doing this for ourselves only :)

I also think that a flat structure would definitely work, but would not be the most elegant way to write this, as this would imply to encode group membership in two separate models — the hierarchy and the actual `django.auth.models.Group` — and having the former update the latter upon change, which seems a bit ugly to me.

**Comment by benjaoming** [comment]
I think for sure that management of groups and group membership would be an interesting set of utility functions and perhaps administrative views.

I think it has to be scoped for flat hierarchy and formulated as a set of utility functions.

It was the same thought that guided these functions:

![image](https://user-images.githubusercontent.com/374612/70793591-ece83a00-1d9b-11ea-9c2c-c6da8a63f86e.png)

(both check boxes could also be swapped for separate buttons)

**Comment by benjaoming** [comment]
@tobast are you considering to work on an enhancement still?

**Comment by tobast** [comment]
@benjaoming I've implemented this on a separate project, since I seemed to understand that there was a reluctance in merging it upstream. At the moment, everything backend is implemented, but I have no frontend at all except `django-admin`.

I've implemented "the duct tape solution": a model called `WikiGroup` that can include both users and other `WikiGroup`s, and has a `ForeignKey` to a vanilla Django `Group`. Upon modification of the `WikiGroup` (and sanity checks), the list of all users in the `WikiGroup` (including through group inclusion) is committed to the Django `Group`.

Unfortunately, my work on this has been done directly on the git repo of the wiki I work on, in a private git, but if there's interest in my code, it should be trivial to extract the module and put it on a public git.

**Comment by benjaoming** [comment]
@tobast it sounds like you found a good solution for your case!

Management through django-admin and possible ModelAdmin actions could be a good improvement to managing permissions. But for any kind of utility functions for these groups, I think it should be written with respect to the common use-case. So I don't think that "groups in groups" can be done so it fits all.

Thanks for taking the time to discuss this! You're always welcome to re-open this issue or propose something else!
